// Code generated by asn1c-go from ASN.1 module "NBIOT-InterNodeDefinitions". DO NOT EDIT.

package rrc

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/per"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = per.NewBitBuffer
)

// ASConfigNB represents the ASN.1 type AS-Config-NB (SEQUENCE).
type ASConfigNB struct {
	SourceRadioResourceConfigR13     RadioResourceConfigDedicatedNBR13 `asn1:"tag:0,context,implicit"`
	SourceSecurityAlgorithmConfigR13 SecurityAlgorithmConfig           `asn1:"tag:1,context,implicit"`
	SourceUEIdentityR13              CRNTI                             `asn1:"tag:2,context,implicit"`
	SourceDlCarrierFreqR13           CarrierFreqNBR13                  `asn1:"tag:3,context,implicit"`
	SourceDLCarrierFreqV1550         *CarrierFreqNBV1550               `asn1:"tag:4,context,implicit,optional" json:"SourceDLCarrierFreqV1550,omitempty"`
	ExtCount_                        int64                             `asn1:"-" json:"-"`
	ExtPresent_                      []bool                            `asn1:"-" json:"-"`
	ExtData_                         [][]byte                          `asn1:"-" json:"-"`
}

// ASContextNB represents the ASN.1 type AS-Context-NB (SEQUENCE).
type ASContextNB struct {
	ReestablishmentInfoR13 *ReestablishmentInfoNB `asn1:"tag:0,context,implicit,optional" json:"ReestablishmentInfoR13,omitempty"`
	ExtCount_              int64                  `asn1:"-" json:"-"`
	ExtPresent_            []bool                 `asn1:"-" json:"-"`
	ExtData_               [][]byte               `asn1:"-" json:"-"`
}

// HandoverPreparationInformationNB represents the ASN.1 type HandoverPreparationInformation-NB (SEQUENCE).
type HandoverPreparationInformationNB struct {
	CriticalExtensions HandoverPreparationInformationNBCriticalExtensions `asn1:"tag:0,context,explicit"`
}

// HandoverPreparationInformationNBExtR14IEs represents the ASN.1 type HandoverPreparationInformation-NB-Ext-r14-IEs (SEQUENCE).
type HandoverPreparationInformationNBExtR14IEs struct {
	UeRadioAccessCapabilityInfoExtR14 []byte            `asn1:"tag:0,context,implicit,optional" json:"UeRadioAccessCapabilityInfoExtR14,omitempty"`
	NonCriticalExtension              *runtime.RawValue `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// HandoverPreparationInformationNBIEs represents the ASN.1 type HandoverPreparationInformation-NB-IEs (SEQUENCE).
type HandoverPreparationInformationNBIEs struct {
	UeRadioAccessCapabilityInfoR13 UECapabilityNBR13                         `asn1:"tag:0,context,implicit"`
	AsConfigR13                    ASConfigNB                                `asn1:"tag:1,context,implicit"`
	RrmConfigR13                   *RRMConfigNB                              `asn1:"tag:2,context,implicit,optional" json:"RrmConfigR13,omitempty"`
	AsContextR13                   *ASContextNB                              `asn1:"tag:3,context,implicit,optional" json:"AsContextR13,omitempty"`
	NonCriticalExtension           *HandoverPreparationInformationNBV1380IEs `asn1:"tag:4,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// HandoverPreparationInformationNBV1380IEs represents the ASN.1 type HandoverPreparationInformation-NB-v1380-IEs (SEQUENCE).
type HandoverPreparationInformationNBV1380IEs struct {
	LateNonCriticalExtension []byte                                     `asn1:"tag:0,context,implicit,optional" json:"LateNonCriticalExtension,omitempty"`
	NonCriticalExtension     *HandoverPreparationInformationNBExtR14IEs `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// RRMConfigNB represents the ASN.1 type RRM-Config-NB (SEQUENCE).
type RRMConfigNB struct {
	UeInactiveTime *int64   `asn1:"tag:0,context,implicit,optional" json:"UeInactiveTime,omitempty"`
	ExtCount_      int64    `asn1:"-" json:"-"`
	ExtPresent_    []bool   `asn1:"-" json:"-"`
	ExtData_       [][]byte `asn1:"-" json:"-"`
}

// ReestablishmentInfoNB represents the ASN.1 type ReestablishmentInfo-NB (SEQUENCE).
type ReestablishmentInfoNB struct {
	SourcePhysCellIdR13          PhysCellId                 `asn1:"tag:0,context,implicit"`
	TargetCellShortMACIR13       ShortMACI                  `asn1:"tag:1,context,implicit"`
	AdditionalReestabInfoListR13 *AdditionalReestabInfoList `asn1:"tag:2,context,implicit,optional" json:"AdditionalReestabInfoListR13,omitempty"`
	ExtCount_                    int64                      `asn1:"-" json:"-"`
	ExtPresent_                  []bool                     `asn1:"-" json:"-"`
	ExtData_                     [][]byte                   `asn1:"-" json:"-"`
}

// UEPagingCoverageInformationNB represents the ASN.1 type UEPagingCoverageInformation-NB (SEQUENCE).
type UEPagingCoverageInformationNB struct {
	CriticalExtensions UEPagingCoverageInformationNBCriticalExtensions `asn1:"tag:0,context,explicit"`
}

// UEPagingCoverageInformationNBIEs represents the ASN.1 type UEPagingCoverageInformation-NB-IEs (SEQUENCE).
type UEPagingCoverageInformationNBIEs struct {
	NpdcchNumRepetitionPagingR13 *int64                                 `asn1:"tag:0,context,implicit,optional" json:"NpdcchNumRepetitionPagingR13,omitempty"`
	NonCriticalExtension         *UEPagingCoverageInformationNBV1700IEs `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// UEPagingCoverageInformationNBV1700IEs represents the ASN.1 type UEPagingCoverageInformation-NB-v1700-IEs (SEQUENCE).
type UEPagingCoverageInformationNBV1700IEs struct {
	CbpIndexR17          *int64            `asn1:"tag:0,context,implicit,optional" json:"CbpIndexR17,omitempty"`
	NonCriticalExtension *runtime.RawValue `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// UERadioAccessCapabilityInformationNB represents the ASN.1 type UERadioAccessCapabilityInformation-NB (SEQUENCE).
type UERadioAccessCapabilityInformationNB struct {
	CriticalExtensions UERadioAccessCapabilityInformationNBCriticalExtensions `asn1:"tag:0,context,explicit"`
}

// UERadioAccessCapabilityInformationNBIEs represents the ASN.1 type UERadioAccessCapabilityInformation-NB-IEs (SEQUENCE).
type UERadioAccessCapabilityInformationNBIEs struct {
	UeRadioAccessCapabilityInfoR13 []byte                                        `asn1:"tag:0,context,implicit"`
	NonCriticalExtension           *UERadioAccessCapabilityInformationNBV1380IEs `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// UERadioAccessCapabilityInformationNBR14IEs represents the ASN.1 type UERadioAccessCapabilityInformation-NB-r14-IEs (SEQUENCE).
type UERadioAccessCapabilityInformationNBR14IEs struct {
	UeRadioAccessCapabilityInfoR14 []byte            `asn1:"tag:0,context,implicit,optional" json:"UeRadioAccessCapabilityInfoR14,omitempty"`
	NonCriticalExtension           *runtime.RawValue `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// UERadioAccessCapabilityInformationNBV1380IEs represents the ASN.1 type UERadioAccessCapabilityInformation-NB-v1380-IEs (SEQUENCE).
type UERadioAccessCapabilityInformationNBV1380IEs struct {
	LateNonCriticalExtension []byte                                      `asn1:"tag:0,context,implicit,optional" json:"LateNonCriticalExtension,omitempty"`
	NonCriticalExtension     *UERadioAccessCapabilityInformationNBR14IEs `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// UERadioPagingInformationNB represents the ASN.1 type UERadioPagingInformation-NB (SEQUENCE).
type UERadioPagingInformationNB struct {
	CriticalExtensions UERadioPagingInformationNBCriticalExtensions `asn1:"tag:0,context,explicit"`
}

// UERadioPagingInformationNBIEs represents the ASN.1 type UERadioPagingInformation-NB-IEs (SEQUENCE).
type UERadioPagingInformationNBIEs struct {
	UeRadioPagingInfoR13 []byte            `asn1:"tag:0,context,implicit"`
	NonCriticalExtension *runtime.RawValue `asn1:"tag:1,context,implicit,optional" json:"NonCriticalExtension,omitempty"`
}

// HandoverPreparationInformationNBCriticalExtensions choice constants.
const (
	HandoverPreparationInformationNBCriticalExtensionsChoiceC1                       = 1
	HandoverPreparationInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture = 2
)

// HandoverPreparationInformationNBCriticalExtensions represents the ASN.1 CHOICE type HandoverPreparationInformation-NB-criticalExtensions.
type HandoverPreparationInformationNBCriticalExtensions struct {
	Choice                   int
	C1                       *HandoverPreparationInformationNBCriticalExtensionsC1 `json:"C1,omitempty"`
	CriticalExtensionsFuture *runtime.RawValue                                     `json:"CriticalExtensionsFuture,omitempty"`
}

// NewHandoverPreparationInformationNBCriticalExtensionsC1 creates a HandoverPreparationInformation-NB-criticalExtensions with the c1 alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsC1(v HandoverPreparationInformationNBCriticalExtensionsC1) HandoverPreparationInformationNBCriticalExtensions {
	return HandoverPreparationInformationNBCriticalExtensions{
		Choice: HandoverPreparationInformationNBCriticalExtensionsChoiceC1,
		C1:     &v,
	}
}

// NewHandoverPreparationInformationNBCriticalExtensionsCriticalExtensionsFuture creates a HandoverPreparationInformation-NB-criticalExtensions with the criticalExtensionsFuture alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsCriticalExtensionsFuture(v runtime.RawValue) HandoverPreparationInformationNBCriticalExtensions {
	return HandoverPreparationInformationNBCriticalExtensions{
		Choice:                   HandoverPreparationInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture,
		CriticalExtensionsFuture: &v,
	}
}

// HandoverPreparationInformationNBCriticalExtensionsC1 choice constants.
const (
	HandoverPreparationInformationNBCriticalExtensionsC1ChoiceHandoverPreparationInformationR13 = 1
	HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare3                            = 2
	HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare2                            = 3
	HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare1                            = 4
)

// HandoverPreparationInformationNBCriticalExtensionsC1 represents the ASN.1 CHOICE type HandoverPreparationInformation-NB-criticalExtensions-c1.
type HandoverPreparationInformationNBCriticalExtensionsC1 struct {
	Choice                            int
	HandoverPreparationInformationR13 *HandoverPreparationInformationNBIEs `json:"HandoverPreparationInformationR13,omitempty"`
	Spare3                            *struct{}                            `json:"Spare3,omitempty"`
	Spare2                            *struct{}                            `json:"Spare2,omitempty"`
	Spare1                            *struct{}                            `json:"Spare1,omitempty"`
}

// NewHandoverPreparationInformationNBCriticalExtensionsC1HandoverPreparationInformationR13 creates a HandoverPreparationInformation-NB-criticalExtensions-c1 with the handoverPreparationInformation-r13 alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsC1HandoverPreparationInformationR13(v HandoverPreparationInformationNBIEs) HandoverPreparationInformationNBCriticalExtensionsC1 {
	return HandoverPreparationInformationNBCriticalExtensionsC1{
		Choice:                            HandoverPreparationInformationNBCriticalExtensionsC1ChoiceHandoverPreparationInformationR13,
		HandoverPreparationInformationR13: &v,
	}
}

// NewHandoverPreparationInformationNBCriticalExtensionsC1Spare3 creates a HandoverPreparationInformation-NB-criticalExtensions-c1 with the spare3 alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsC1Spare3(v struct{}) HandoverPreparationInformationNBCriticalExtensionsC1 {
	return HandoverPreparationInformationNBCriticalExtensionsC1{
		Choice: HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare3,
		Spare3: &v,
	}
}

// NewHandoverPreparationInformationNBCriticalExtensionsC1Spare2 creates a HandoverPreparationInformation-NB-criticalExtensions-c1 with the spare2 alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsC1Spare2(v struct{}) HandoverPreparationInformationNBCriticalExtensionsC1 {
	return HandoverPreparationInformationNBCriticalExtensionsC1{
		Choice: HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare2,
		Spare2: &v,
	}
}

// NewHandoverPreparationInformationNBCriticalExtensionsC1Spare1 creates a HandoverPreparationInformation-NB-criticalExtensions-c1 with the spare1 alternative.
func NewHandoverPreparationInformationNBCriticalExtensionsC1Spare1(v struct{}) HandoverPreparationInformationNBCriticalExtensionsC1 {
	return HandoverPreparationInformationNBCriticalExtensionsC1{
		Choice: HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare1,
		Spare1: &v,
	}
}

// UEPagingCoverageInformationNBCriticalExtensions choice constants.
const (
	UEPagingCoverageInformationNBCriticalExtensionsChoiceC1                       = 1
	UEPagingCoverageInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture = 2
)

// UEPagingCoverageInformationNBCriticalExtensions represents the ASN.1 CHOICE type UEPagingCoverageInformation-NB-criticalExtensions.
type UEPagingCoverageInformationNBCriticalExtensions struct {
	Choice                   int
	C1                       *UEPagingCoverageInformationNBCriticalExtensionsC1 `json:"C1,omitempty"`
	CriticalExtensionsFuture *runtime.RawValue                                  `json:"CriticalExtensionsFuture,omitempty"`
}

// NewUEPagingCoverageInformationNBCriticalExtensionsC1 creates a UEPagingCoverageInformation-NB-criticalExtensions with the c1 alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsC1(v UEPagingCoverageInformationNBCriticalExtensionsC1) UEPagingCoverageInformationNBCriticalExtensions {
	return UEPagingCoverageInformationNBCriticalExtensions{
		Choice: UEPagingCoverageInformationNBCriticalExtensionsChoiceC1,
		C1:     &v,
	}
}

// NewUEPagingCoverageInformationNBCriticalExtensionsCriticalExtensionsFuture creates a UEPagingCoverageInformation-NB-criticalExtensions with the criticalExtensionsFuture alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsCriticalExtensionsFuture(v runtime.RawValue) UEPagingCoverageInformationNBCriticalExtensions {
	return UEPagingCoverageInformationNBCriticalExtensions{
		Choice:                   UEPagingCoverageInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture,
		CriticalExtensionsFuture: &v,
	}
}

// UEPagingCoverageInformationNBCriticalExtensionsC1 choice constants.
const (
	UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceUePagingCoverageInformationR13 = 1
	UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare3                         = 2
	UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare2                         = 3
	UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare1                         = 4
)

// UEPagingCoverageInformationNBCriticalExtensionsC1 represents the ASN.1 CHOICE type UEPagingCoverageInformation-NB-criticalExtensions-c1.
type UEPagingCoverageInformationNBCriticalExtensionsC1 struct {
	Choice                         int
	UePagingCoverageInformationR13 *UEPagingCoverageInformationNBIEs `json:"UePagingCoverageInformationR13,omitempty"`
	Spare3                         *struct{}                         `json:"Spare3,omitempty"`
	Spare2                         *struct{}                         `json:"Spare2,omitempty"`
	Spare1                         *struct{}                         `json:"Spare1,omitempty"`
}

// NewUEPagingCoverageInformationNBCriticalExtensionsC1UePagingCoverageInformationR13 creates a UEPagingCoverageInformation-NB-criticalExtensions-c1 with the uePagingCoverageInformation-r13 alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsC1UePagingCoverageInformationR13(v UEPagingCoverageInformationNBIEs) UEPagingCoverageInformationNBCriticalExtensionsC1 {
	return UEPagingCoverageInformationNBCriticalExtensionsC1{
		Choice:                         UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceUePagingCoverageInformationR13,
		UePagingCoverageInformationR13: &v,
	}
}

// NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare3 creates a UEPagingCoverageInformation-NB-criticalExtensions-c1 with the spare3 alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare3(v struct{}) UEPagingCoverageInformationNBCriticalExtensionsC1 {
	return UEPagingCoverageInformationNBCriticalExtensionsC1{
		Choice: UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare3,
		Spare3: &v,
	}
}

// NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare2 creates a UEPagingCoverageInformation-NB-criticalExtensions-c1 with the spare2 alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare2(v struct{}) UEPagingCoverageInformationNBCriticalExtensionsC1 {
	return UEPagingCoverageInformationNBCriticalExtensionsC1{
		Choice: UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare2,
		Spare2: &v,
	}
}

// NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare1 creates a UEPagingCoverageInformation-NB-criticalExtensions-c1 with the spare1 alternative.
func NewUEPagingCoverageInformationNBCriticalExtensionsC1Spare1(v struct{}) UEPagingCoverageInformationNBCriticalExtensionsC1 {
	return UEPagingCoverageInformationNBCriticalExtensionsC1{
		Choice: UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare1,
		Spare1: &v,
	}
}

// UERadioAccessCapabilityInformationNBCriticalExtensions choice constants.
const (
	UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceC1                       = 1
	UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture = 2
)

// UERadioAccessCapabilityInformationNBCriticalExtensions represents the ASN.1 CHOICE type UERadioAccessCapabilityInformation-NB-criticalExtensions.
type UERadioAccessCapabilityInformationNBCriticalExtensions struct {
	Choice                   int
	C1                       *UERadioAccessCapabilityInformationNBCriticalExtensionsC1 `json:"C1,omitempty"`
	CriticalExtensionsFuture *runtime.RawValue                                         `json:"CriticalExtensionsFuture,omitempty"`
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1 creates a UERadioAccessCapabilityInformation-NB-criticalExtensions with the c1 alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1(v UERadioAccessCapabilityInformationNBCriticalExtensionsC1) UERadioAccessCapabilityInformationNBCriticalExtensions {
	return UERadioAccessCapabilityInformationNBCriticalExtensions{
		Choice: UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceC1,
		C1:     &v,
	}
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsCriticalExtensionsFuture creates a UERadioAccessCapabilityInformation-NB-criticalExtensions with the criticalExtensionsFuture alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsCriticalExtensionsFuture(v runtime.RawValue) UERadioAccessCapabilityInformationNBCriticalExtensions {
	return UERadioAccessCapabilityInformationNBCriticalExtensions{
		Choice:                   UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture,
		CriticalExtensionsFuture: &v,
	}
}

// UERadioAccessCapabilityInformationNBCriticalExtensionsC1 choice constants.
const (
	UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceUeRadioAccessCapabilityInformationR13 = 1
	UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare3                                = 2
	UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare2                                = 3
	UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare1                                = 4
)

// UERadioAccessCapabilityInformationNBCriticalExtensionsC1 represents the ASN.1 CHOICE type UERadioAccessCapabilityInformation-NB-criticalExtensions-c1.
type UERadioAccessCapabilityInformationNBCriticalExtensionsC1 struct {
	Choice                                int
	UeRadioAccessCapabilityInformationR13 *UERadioAccessCapabilityInformationNBIEs `json:"UeRadioAccessCapabilityInformationR13,omitempty"`
	Spare3                                *struct{}                                `json:"Spare3,omitempty"`
	Spare2                                *struct{}                                `json:"Spare2,omitempty"`
	Spare1                                *struct{}                                `json:"Spare1,omitempty"`
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1UeRadioAccessCapabilityInformationR13 creates a UERadioAccessCapabilityInformation-NB-criticalExtensions-c1 with the ueRadioAccessCapabilityInformation-r13 alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1UeRadioAccessCapabilityInformationR13(v UERadioAccessCapabilityInformationNBIEs) UERadioAccessCapabilityInformationNBCriticalExtensionsC1 {
	return UERadioAccessCapabilityInformationNBCriticalExtensionsC1{
		Choice:                                UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceUeRadioAccessCapabilityInformationR13,
		UeRadioAccessCapabilityInformationR13: &v,
	}
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare3 creates a UERadioAccessCapabilityInformation-NB-criticalExtensions-c1 with the spare3 alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare3(v struct{}) UERadioAccessCapabilityInformationNBCriticalExtensionsC1 {
	return UERadioAccessCapabilityInformationNBCriticalExtensionsC1{
		Choice: UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare3,
		Spare3: &v,
	}
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare2 creates a UERadioAccessCapabilityInformation-NB-criticalExtensions-c1 with the spare2 alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare2(v struct{}) UERadioAccessCapabilityInformationNBCriticalExtensionsC1 {
	return UERadioAccessCapabilityInformationNBCriticalExtensionsC1{
		Choice: UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare2,
		Spare2: &v,
	}
}

// NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare1 creates a UERadioAccessCapabilityInformation-NB-criticalExtensions-c1 with the spare1 alternative.
func NewUERadioAccessCapabilityInformationNBCriticalExtensionsC1Spare1(v struct{}) UERadioAccessCapabilityInformationNBCriticalExtensionsC1 {
	return UERadioAccessCapabilityInformationNBCriticalExtensionsC1{
		Choice: UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare1,
		Spare1: &v,
	}
}

// UERadioPagingInformationNBCriticalExtensions choice constants.
const (
	UERadioPagingInformationNBCriticalExtensionsChoiceC1                       = 1
	UERadioPagingInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture = 2
)

// UERadioPagingInformationNBCriticalExtensions represents the ASN.1 CHOICE type UERadioPagingInformation-NB-criticalExtensions.
type UERadioPagingInformationNBCriticalExtensions struct {
	Choice                   int
	C1                       *UERadioPagingInformationNBCriticalExtensionsC1 `json:"C1,omitempty"`
	CriticalExtensionsFuture *runtime.RawValue                               `json:"CriticalExtensionsFuture,omitempty"`
}

// NewUERadioPagingInformationNBCriticalExtensionsC1 creates a UERadioPagingInformation-NB-criticalExtensions with the c1 alternative.
func NewUERadioPagingInformationNBCriticalExtensionsC1(v UERadioPagingInformationNBCriticalExtensionsC1) UERadioPagingInformationNBCriticalExtensions {
	return UERadioPagingInformationNBCriticalExtensions{
		Choice: UERadioPagingInformationNBCriticalExtensionsChoiceC1,
		C1:     &v,
	}
}

// NewUERadioPagingInformationNBCriticalExtensionsCriticalExtensionsFuture creates a UERadioPagingInformation-NB-criticalExtensions with the criticalExtensionsFuture alternative.
func NewUERadioPagingInformationNBCriticalExtensionsCriticalExtensionsFuture(v runtime.RawValue) UERadioPagingInformationNBCriticalExtensions {
	return UERadioPagingInformationNBCriticalExtensions{
		Choice:                   UERadioPagingInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture,
		CriticalExtensionsFuture: &v,
	}
}

// UERadioPagingInformationNBCriticalExtensionsC1 choice constants.
const (
	UERadioPagingInformationNBCriticalExtensionsC1ChoiceUeRadioPagingInformationR13 = 1
	UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare3                      = 2
	UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare2                      = 3
	UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare1                      = 4
)

// UERadioPagingInformationNBCriticalExtensionsC1 represents the ASN.1 CHOICE type UERadioPagingInformation-NB-criticalExtensions-c1.
type UERadioPagingInformationNBCriticalExtensionsC1 struct {
	Choice                      int
	UeRadioPagingInformationR13 *UERadioPagingInformationNBIEs `json:"UeRadioPagingInformationR13,omitempty"`
	Spare3                      *struct{}                      `json:"Spare3,omitempty"`
	Spare2                      *struct{}                      `json:"Spare2,omitempty"`
	Spare1                      *struct{}                      `json:"Spare1,omitempty"`
}

// NewUERadioPagingInformationNBCriticalExtensionsC1UeRadioPagingInformationR13 creates a UERadioPagingInformation-NB-criticalExtensions-c1 with the ueRadioPagingInformation-r13 alternative.
func NewUERadioPagingInformationNBCriticalExtensionsC1UeRadioPagingInformationR13(v UERadioPagingInformationNBIEs) UERadioPagingInformationNBCriticalExtensionsC1 {
	return UERadioPagingInformationNBCriticalExtensionsC1{
		Choice:                      UERadioPagingInformationNBCriticalExtensionsC1ChoiceUeRadioPagingInformationR13,
		UeRadioPagingInformationR13: &v,
	}
}

// NewUERadioPagingInformationNBCriticalExtensionsC1Spare3 creates a UERadioPagingInformation-NB-criticalExtensions-c1 with the spare3 alternative.
func NewUERadioPagingInformationNBCriticalExtensionsC1Spare3(v struct{}) UERadioPagingInformationNBCriticalExtensionsC1 {
	return UERadioPagingInformationNBCriticalExtensionsC1{
		Choice: UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare3,
		Spare3: &v,
	}
}

// NewUERadioPagingInformationNBCriticalExtensionsC1Spare2 creates a UERadioPagingInformation-NB-criticalExtensions-c1 with the spare2 alternative.
func NewUERadioPagingInformationNBCriticalExtensionsC1Spare2(v struct{}) UERadioPagingInformationNBCriticalExtensionsC1 {
	return UERadioPagingInformationNBCriticalExtensionsC1{
		Choice: UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare2,
		Spare2: &v,
	}
}

// NewUERadioPagingInformationNBCriticalExtensionsC1Spare1 creates a UERadioPagingInformation-NB-criticalExtensions-c1 with the spare1 alternative.
func NewUERadioPagingInformationNBCriticalExtensionsC1Spare1(v struct{}) UERadioPagingInformationNBCriticalExtensionsC1 {
	return UERadioPagingInformationNBCriticalExtensionsC1{
		Choice: UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare1,
		Spare1: &v,
	}
}

// MarshalUPER encodes ASConfigNB to UPER format.
func (v *ASConfigNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ASConfigNB) marshalUPERTo(bb *per.BitBuffer) error {
	hasExtensions := v.ExtCount_ > 0 || len(v.ExtData_) > 0 || v.SourceDLCarrierFreqV1550 != nil
	if err := per.EncodeBoolean(bb, hasExtensions); err != nil {
		return err
	}
	if err := v.SourceRadioResourceConfigR13.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding sourceRadioResourceConfig-r13: %w", err)
	}
	if err := v.SourceSecurityAlgorithmConfigR13.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding sourceSecurityAlgorithmConfig-r13: %w", err)
	}
	if err := per.EncodeBitString(bb, v.SourceUEIdentityR13.Bytes, v.SourceUEIdentityR13.BitLength, 16, 16, true); err != nil {
		return fmt.Errorf("encoding sourceUE-Identity-r13: %w", err)
	}
	if err := v.SourceDlCarrierFreqR13.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding sourceDl-CarrierFreq-r13: %w", err)
	}
	if hasExtensions {
		extHighest := int64(0)
		if v.SourceDLCarrierFreqV1550 != nil {
			extHighest = 0
		}
		if v.ExtCount_ > extHighest {
			extHighest = v.ExtCount_
		}
		if err := per.EncodeNormallySmallNonNegative(bb, extHighest); err != nil {
			return err
		}
		// Extension presence bitmap
		if int64(0) <= extHighest {
			present0 := (int64(0) < int64(len(v.ExtPresent_)) && v.ExtPresent_[0]) || v.SourceDLCarrierFreqV1550 != nil
			if err := per.EncodeBoolean(bb, present0); err != nil {
				return err
			}
		}
		for i := int64(1); i <= extHighest; i++ {
			p := i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i]
			if err := per.EncodeBoolean(bb, p); err != nil {
				return err
			}
		}
		if (int64(0) < int64(len(v.ExtPresent_)) && v.ExtPresent_[0]) || v.SourceDLCarrierFreqV1550 != nil {
			extBuf := per.NewBitBuffer()
			if err := per.EncodeBoolean(extBuf, v.SourceDLCarrierFreqV1550 != nil); err != nil {
				return err
			}
			if v.SourceDLCarrierFreqV1550 != nil {
				if err := v.SourceDLCarrierFreqV1550.marshalUPERTo(extBuf); err != nil {
					return fmt.Errorf("encoding sourceDL-CarrierFreq-v1550: %w", err)
				}
			}
			if err := per.EncodeOpenType(bb, extBuf.Bytes()); err != nil {
				return err
			}
		}
		for i := int64(1); i <= extHighest; i++ {
			if i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i] {
				if i < int64(len(v.ExtData_)) && v.ExtData_[i] != nil {
					if err := per.EncodeOpenType(bb, v.ExtData_[i]); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// UnmarshalUPER decodes ASConfigNB from UPER format.
func (v *ASConfigNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *ASConfigNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	hasExtensions, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if err := v.SourceRadioResourceConfigR13.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding sourceRadioResourceConfig-r13: %w", err)
	}
	if err := v.SourceSecurityAlgorithmConfigR13.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding sourceSecurityAlgorithmConfig-r13: %w", err)
	}
	bsBytes_sourceueidentityr13, bsBitLen_sourceueidentityr13, err := per.DecodeBitString(bb, 16, 16, true)
	if err != nil {
		return fmt.Errorf("decoding sourceUE-Identity-r13: %w", err)
	}
	v.SourceUEIdentityR13 = runtime.BitString{Bytes: bsBytes_sourceueidentityr13, BitLength: bsBitLen_sourceueidentityr13}
	if err := v.SourceDlCarrierFreqR13.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding sourceDl-CarrierFreq-r13: %w", err)
	}
	if hasExtensions {
		extCount, err := per.DecodeNormallySmallNonNegative(bb)
		if err != nil {
			return err
		}
		v.ExtCount_ = extCount
		// Read extension presence bitmap
		extPresent := make([]bool, extCount+1)
		for i := int64(0); i <= extCount; i++ {
			p, err := per.DecodeBoolean(bb)
			if err != nil {
				return err
			}
			extPresent[i] = p
		}
		v.ExtPresent_ = extPresent
		if int64(0) <= extCount && extPresent[0] {
			extData, err := per.DecodeOpenType(bb)
			if err != nil {
				return err
			}
			extBB := per.NewBitBufferFromBytes(extData)
			_ = extBB
			ext_opt_sourcedlcarrierfreqv1550, err := per.DecodeBoolean(extBB)
			if err != nil {
				return err
			}
			if ext_opt_sourcedlcarrierfreqv1550 {
				var dec_sourcedlcarrierfreqv1550 CarrierFreqNBV1550
				if err := dec_sourcedlcarrierfreqv1550.unmarshalUPERFrom(extBB); err != nil {
					return fmt.Errorf("decoding sourceDL-CarrierFreq-v1550: %w", err)
				}
				v.SourceDLCarrierFreqV1550 = &dec_sourcedlcarrierfreqv1550
			}
		}
		v.ExtData_ = make([][]byte, extCount+1)
		for i := int64(1); i <= extCount; i++ {
			if extPresent[i] {
				data, err := per.DecodeOpenType(bb)
				if err != nil {
					return err
				}
				v.ExtData_[i] = data
			}
		}
	}
	return nil
}

// MarshalUPER encodes ASContextNB to UPER format.
func (v *ASContextNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ASContextNB) marshalUPERTo(bb *per.BitBuffer) error {
	hasExtensions := v.ExtCount_ > 0 || len(v.ExtData_) > 0
	if err := per.EncodeBoolean(bb, hasExtensions); err != nil {
		return err
	}
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.ReestablishmentInfoR13 != nil); err != nil {
		return err
	}
	if v.ReestablishmentInfoR13 != nil {
		if err := v.ReestablishmentInfoR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding reestablishmentInfo-r13: %w", err)
		}
	}
	if hasExtensions {
		if err := per.EncodeNormallySmallNonNegative(bb, v.ExtCount_); err != nil {
			return err
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			p := i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i]
			if err := per.EncodeBoolean(bb, p); err != nil {
				return err
			}
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			if i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i] {
				if i < int64(len(v.ExtData_)) && v.ExtData_[i] != nil {
					if err := per.EncodeOpenType(bb, v.ExtData_[i]); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// UnmarshalUPER decodes ASContextNB from UPER format.
func (v *ASContextNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *ASContextNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	hasExtensions, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	// Read preamble bitmap for optional root fields
	opt_reestablishmentinfor13, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_reestablishmentinfor13 {
		var dec_reestablishmentinfor13 ReestablishmentInfoNB
		if err := dec_reestablishmentinfor13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding reestablishmentInfo-r13: %w", err)
		}
		v.ReestablishmentInfoR13 = &dec_reestablishmentinfor13
	}
	if hasExtensions {
		extCount, err := per.DecodeNormallySmallNonNegative(bb)
		if err != nil {
			return err
		}
		v.ExtCount_ = extCount
		extPresent := make([]bool, extCount+1)
		v.ExtData_ = make([][]byte, extCount+1)
		for i := int64(0); i <= extCount; i++ {
			p, err := per.DecodeBoolean(bb)
			if err != nil {
				return err
			}
			extPresent[i] = p
		}
		v.ExtPresent_ = extPresent
		for i := int64(0); i <= extCount; i++ {
			if extPresent[i] {
				data, err := per.DecodeOpenType(bb)
				if err != nil {
					return err
				}
				v.ExtData_[i] = data
			}
		}
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNB to UPER format.
func (v *HandoverPreparationInformationNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNB) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding criticalExtensions: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNB from UPER format.
func (v *HandoverPreparationInformationNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding criticalExtensions: %w", err)
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNBExtR14IEs to UPER format.
func (v *HandoverPreparationInformationNBExtR14IEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNBExtR14IEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.UeRadioAccessCapabilityInfoExtR14 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.UeRadioAccessCapabilityInfoExtR14 != nil {
		if err := per.EncodeOctetString(bb, v.UeRadioAccessCapabilityInfoExtR14, 0, 0, false); err != nil {
			return fmt.Errorf("encoding ue-RadioAccessCapabilityInfoExt-r14: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNBExtR14IEs from UPER format.
func (v *HandoverPreparationInformationNBExtR14IEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNBExtR14IEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_ueradioaccesscapabilityinfoextr14, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_ueradioaccesscapabilityinfoextr14 {
		val_ueradioaccesscapabilityinfoextr14, err := per.DecodeOctetString(bb, 0, 0, false)
		if err != nil {
			return fmt.Errorf("decoding ue-RadioAccessCapabilityInfoExt-r14: %w", err)
		}
		tmp_ueradioaccesscapabilityinfoextr14 := val_ueradioaccesscapabilityinfoextr14
		v.UeRadioAccessCapabilityInfoExtR14 = tmp_ueradioaccesscapabilityinfoextr14
	}
	if opt_noncriticalextension {
		tmp_noncriticalextension := runtime.RawValue{}
		v.NonCriticalExtension = &tmp_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNBIEs to UPER format.
func (v *HandoverPreparationInformationNBIEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNBIEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.RrmConfigR13 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.AsContextR13 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if err := v.UeRadioAccessCapabilityInfoR13.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding ue-RadioAccessCapabilityInfo-r13: %w", err)
	}
	if err := v.AsConfigR13.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding as-Config-r13: %w", err)
	}
	if v.RrmConfigR13 != nil {
		if err := v.RrmConfigR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding rrm-Config-r13: %w", err)
		}
	}
	if v.AsContextR13 != nil {
		if err := v.AsContextR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding as-Context-r13: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
		if err := v.NonCriticalExtension.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding nonCriticalExtension: %w", err)
		}
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNBIEs from UPER format.
func (v *HandoverPreparationInformationNBIEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNBIEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_rrmconfigr13, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_ascontextr13, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if err := v.UeRadioAccessCapabilityInfoR13.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding ue-RadioAccessCapabilityInfo-r13: %w", err)
	}
	if err := v.AsConfigR13.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding as-Config-r13: %w", err)
	}
	if opt_rrmconfigr13 {
		var dec_rrmconfigr13 RRMConfigNB
		if err := dec_rrmconfigr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding rrm-Config-r13: %w", err)
		}
		v.RrmConfigR13 = &dec_rrmconfigr13
	}
	if opt_ascontextr13 {
		var dec_ascontextr13 ASContextNB
		if err := dec_ascontextr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding as-Context-r13: %w", err)
		}
		v.AsContextR13 = &dec_ascontextr13
	}
	if opt_noncriticalextension {
		var dec_noncriticalextension HandoverPreparationInformationNBV1380IEs
		if err := dec_noncriticalextension.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding nonCriticalExtension: %w", err)
		}
		v.NonCriticalExtension = &dec_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNBV1380IEs to UPER format.
func (v *HandoverPreparationInformationNBV1380IEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNBV1380IEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.LateNonCriticalExtension != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.LateNonCriticalExtension != nil {
		if err := per.EncodeOctetString(bb, v.LateNonCriticalExtension, 0, 0, false); err != nil {
			return fmt.Errorf("encoding lateNonCriticalExtension: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
		if err := v.NonCriticalExtension.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding nonCriticalExtension: %w", err)
		}
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNBV1380IEs from UPER format.
func (v *HandoverPreparationInformationNBV1380IEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNBV1380IEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_latenoncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_latenoncriticalextension {
		val_latenoncriticalextension, err := per.DecodeOctetString(bb, 0, 0, false)
		if err != nil {
			return fmt.Errorf("decoding lateNonCriticalExtension: %w", err)
		}
		tmp_latenoncriticalextension := val_latenoncriticalextension
		v.LateNonCriticalExtension = tmp_latenoncriticalextension
	}
	if opt_noncriticalextension {
		var dec_noncriticalextension HandoverPreparationInformationNBExtR14IEs
		if err := dec_noncriticalextension.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding nonCriticalExtension: %w", err)
		}
		v.NonCriticalExtension = &dec_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes RRMConfigNB to UPER format.
func (v *RRMConfigNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *RRMConfigNB) marshalUPERTo(bb *per.BitBuffer) error {
	hasExtensions := v.ExtCount_ > 0 || len(v.ExtData_) > 0
	if err := per.EncodeBoolean(bb, hasExtensions); err != nil {
		return err
	}
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.UeInactiveTime != nil); err != nil {
		return err
	}
	if v.UeInactiveTime != nil {
		if err := per.EncodeEnumerated(bb, int64(*v.UeInactiveTime), 64, false); err != nil {
			return fmt.Errorf("encoding ue-InactiveTime: %w", err)
		}
	}
	if hasExtensions {
		if err := per.EncodeNormallySmallNonNegative(bb, v.ExtCount_); err != nil {
			return err
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			p := i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i]
			if err := per.EncodeBoolean(bb, p); err != nil {
				return err
			}
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			if i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i] {
				if i < int64(len(v.ExtData_)) && v.ExtData_[i] != nil {
					if err := per.EncodeOpenType(bb, v.ExtData_[i]); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// UnmarshalUPER decodes RRMConfigNB from UPER format.
func (v *RRMConfigNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *RRMConfigNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	hasExtensions, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	// Read preamble bitmap for optional root fields
	opt_ueinactivetime, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_ueinactivetime {
		val_ueinactivetime, err := per.DecodeEnumerated(bb, 64, false)
		if err != nil {
			return fmt.Errorf("decoding ue-InactiveTime: %w", err)
		}
		v.UeInactiveTime = &val_ueinactivetime
	}
	if hasExtensions {
		extCount, err := per.DecodeNormallySmallNonNegative(bb)
		if err != nil {
			return err
		}
		v.ExtCount_ = extCount
		extPresent := make([]bool, extCount+1)
		v.ExtData_ = make([][]byte, extCount+1)
		for i := int64(0); i <= extCount; i++ {
			p, err := per.DecodeBoolean(bb)
			if err != nil {
				return err
			}
			extPresent[i] = p
		}
		v.ExtPresent_ = extPresent
		for i := int64(0); i <= extCount; i++ {
			if extPresent[i] {
				data, err := per.DecodeOpenType(bb)
				if err != nil {
					return err
				}
				v.ExtData_[i] = data
			}
		}
	}
	return nil
}

// MarshalUPER encodes ReestablishmentInfoNB to UPER format.
func (v *ReestablishmentInfoNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ReestablishmentInfoNB) marshalUPERTo(bb *per.BitBuffer) error {
	hasExtensions := v.ExtCount_ > 0 || len(v.ExtData_) > 0
	if err := per.EncodeBoolean(bb, hasExtensions); err != nil {
		return err
	}
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.AdditionalReestabInfoListR13 != nil); err != nil {
		return err
	}
	if err := per.EncodeInteger(bb, int64(v.SourcePhysCellIdR13), int64Ptr(0), int64Ptr(503), false); err != nil {
		return fmt.Errorf("encoding sourcePhysCellId-r13: %w", err)
	}
	if err := per.EncodeBitString(bb, v.TargetCellShortMACIR13.Bytes, v.TargetCellShortMACIR13.BitLength, 16, 16, true); err != nil {
		return fmt.Errorf("encoding targetCellShortMAC-I-r13: %w", err)
	}
	if v.AdditionalReestabInfoListR13 != nil {
		if err := per.EncodeConstrainedWholeNumber(bb, int64(len(*v.AdditionalReestabInfoListR13)), 1, 32); err != nil {
			return fmt.Errorf("encoding additionalReestabInfoList-r13 length: %w", err)
		}
		for _, elem := range *v.AdditionalReestabInfoListR13 {
			if err := elem.marshalUPERTo(bb); err != nil {
				return fmt.Errorf("encoding additionalReestabInfoList-r13 element: %w", err)
			}
		}
	}
	if hasExtensions {
		if err := per.EncodeNormallySmallNonNegative(bb, v.ExtCount_); err != nil {
			return err
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			p := i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i]
			if err := per.EncodeBoolean(bb, p); err != nil {
				return err
			}
		}
		for i := int64(0); i <= v.ExtCount_; i++ {
			if i < int64(len(v.ExtPresent_)) && v.ExtPresent_[i] {
				if i < int64(len(v.ExtData_)) && v.ExtData_[i] != nil {
					if err := per.EncodeOpenType(bb, v.ExtData_[i]); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// UnmarshalUPER decodes ReestablishmentInfoNB from UPER format.
func (v *ReestablishmentInfoNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *ReestablishmentInfoNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	hasExtensions, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	// Read preamble bitmap for optional root fields
	opt_additionalreestabinfolistr13, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	val_sourcephyscellidr13, err := per.DecodeInteger(bb, int64Ptr(0), int64Ptr(503), false)
	if err != nil {
		return fmt.Errorf("decoding sourcePhysCellId-r13: %w", err)
	}
	v.SourcePhysCellIdR13 = val_sourcephyscellidr13
	bsBytes_targetcellshortmacir13, bsBitLen_targetcellshortmacir13, err := per.DecodeBitString(bb, 16, 16, true)
	if err != nil {
		return fmt.Errorf("decoding targetCellShortMAC-I-r13: %w", err)
	}
	v.TargetCellShortMACIR13 = runtime.BitString{Bytes: bsBytes_targetcellshortmacir13, BitLength: bsBitLen_targetcellshortmacir13}
	if opt_additionalreestabinfolistr13 {
		seqLen_additionalreestabinfolistr13, err := per.DecodeConstrainedWholeNumber(bb, 1, 32)
		if err != nil {
			return fmt.Errorf("decoding additionalReestabInfoList-r13 length: %w", err)
		}
		tmp_additionalreestabinfolistr13 := make(AdditionalReestabInfoList, seqLen_additionalreestabinfolistr13)
		for i := int64(0); i < seqLen_additionalreestabinfolistr13; i++ {
			if err := tmp_additionalreestabinfolistr13[i].unmarshalUPERFrom(bb); err != nil {
				return fmt.Errorf("decoding additionalReestabInfoList-r13 element: %w", err)
			}
		}
		v.AdditionalReestabInfoListR13 = &tmp_additionalreestabinfolistr13
	}
	if hasExtensions {
		extCount, err := per.DecodeNormallySmallNonNegative(bb)
		if err != nil {
			return err
		}
		v.ExtCount_ = extCount
		extPresent := make([]bool, extCount+1)
		v.ExtData_ = make([][]byte, extCount+1)
		for i := int64(0); i <= extCount; i++ {
			p, err := per.DecodeBoolean(bb)
			if err != nil {
				return err
			}
			extPresent[i] = p
		}
		v.ExtPresent_ = extPresent
		for i := int64(0); i <= extCount; i++ {
			if extPresent[i] {
				data, err := per.DecodeOpenType(bb)
				if err != nil {
					return err
				}
				v.ExtData_[i] = data
			}
		}
	}
	return nil
}

// MarshalUPER encodes UEPagingCoverageInformationNB to UPER format.
func (v *UEPagingCoverageInformationNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UEPagingCoverageInformationNB) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding criticalExtensions: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes UEPagingCoverageInformationNB from UPER format.
func (v *UEPagingCoverageInformationNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UEPagingCoverageInformationNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding criticalExtensions: %w", err)
	}
	return nil
}

// MarshalUPER encodes UEPagingCoverageInformationNBIEs to UPER format.
func (v *UEPagingCoverageInformationNBIEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UEPagingCoverageInformationNBIEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.NpdcchNumRepetitionPagingR13 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.NpdcchNumRepetitionPagingR13 != nil {
		if err := per.EncodeInteger(bb, int64(*v.NpdcchNumRepetitionPagingR13), int64Ptr(1), int64Ptr(2048), false); err != nil {
			return fmt.Errorf("encoding npdcch-NumRepetitionPaging-r13: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
		if err := v.NonCriticalExtension.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding nonCriticalExtension: %w", err)
		}
	}
	return nil
}

// UnmarshalUPER decodes UEPagingCoverageInformationNBIEs from UPER format.
func (v *UEPagingCoverageInformationNBIEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UEPagingCoverageInformationNBIEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_npdcchnumrepetitionpagingr13, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_npdcchnumrepetitionpagingr13 {
		val_npdcchnumrepetitionpagingr13, err := per.DecodeInteger(bb, int64Ptr(1), int64Ptr(2048), false)
		if err != nil {
			return fmt.Errorf("decoding npdcch-NumRepetitionPaging-r13: %w", err)
		}
		v.NpdcchNumRepetitionPagingR13 = &val_npdcchnumrepetitionpagingr13
	}
	if opt_noncriticalextension {
		var dec_noncriticalextension UEPagingCoverageInformationNBV1700IEs
		if err := dec_noncriticalextension.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding nonCriticalExtension: %w", err)
		}
		v.NonCriticalExtension = &dec_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes UEPagingCoverageInformationNBV1700IEs to UPER format.
func (v *UEPagingCoverageInformationNBV1700IEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UEPagingCoverageInformationNBV1700IEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.CbpIndexR17 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.CbpIndexR17 != nil {
		if err := per.EncodeInteger(bb, int64(*v.CbpIndexR17), int64Ptr(1), int64Ptr(2), false); err != nil {
			return fmt.Errorf("encoding cbp-Index-r17: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
	}
	return nil
}

// UnmarshalUPER decodes UEPagingCoverageInformationNBV1700IEs from UPER format.
func (v *UEPagingCoverageInformationNBV1700IEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UEPagingCoverageInformationNBV1700IEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_cbpindexr17, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_cbpindexr17 {
		val_cbpindexr17, err := per.DecodeInteger(bb, int64Ptr(1), int64Ptr(2), false)
		if err != nil {
			return fmt.Errorf("decoding cbp-Index-r17: %w", err)
		}
		v.CbpIndexR17 = &val_cbpindexr17
	}
	if opt_noncriticalextension {
		tmp_noncriticalextension := runtime.RawValue{}
		v.NonCriticalExtension = &tmp_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNB to UPER format.
func (v *UERadioAccessCapabilityInformationNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNB) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding criticalExtensions: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNB from UPER format.
func (v *UERadioAccessCapabilityInformationNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding criticalExtensions: %w", err)
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNBIEs to UPER format.
func (v *UERadioAccessCapabilityInformationNBIEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNBIEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if err := per.EncodeOctetString(bb, v.UeRadioAccessCapabilityInfoR13, 0, 0, false); err != nil {
		return fmt.Errorf("encoding ue-RadioAccessCapabilityInfo-r13: %w", err)
	}
	if v.NonCriticalExtension != nil {
		if err := v.NonCriticalExtension.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding nonCriticalExtension: %w", err)
		}
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNBIEs from UPER format.
func (v *UERadioAccessCapabilityInformationNBIEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNBIEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	val_ueradioaccesscapabilityinfor13, err := per.DecodeOctetString(bb, 0, 0, false)
	if err != nil {
		return fmt.Errorf("decoding ue-RadioAccessCapabilityInfo-r13: %w", err)
	}
	v.UeRadioAccessCapabilityInfoR13 = val_ueradioaccesscapabilityinfor13
	if opt_noncriticalextension {
		var dec_noncriticalextension UERadioAccessCapabilityInformationNBV1380IEs
		if err := dec_noncriticalextension.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding nonCriticalExtension: %w", err)
		}
		v.NonCriticalExtension = &dec_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNBR14IEs to UPER format.
func (v *UERadioAccessCapabilityInformationNBR14IEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNBR14IEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.UeRadioAccessCapabilityInfoR14 != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.UeRadioAccessCapabilityInfoR14 != nil {
		if err := per.EncodeOctetString(bb, v.UeRadioAccessCapabilityInfoR14, 0, 0, false); err != nil {
			return fmt.Errorf("encoding ue-RadioAccessCapabilityInfo-r14: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNBR14IEs from UPER format.
func (v *UERadioAccessCapabilityInformationNBR14IEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNBR14IEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_ueradioaccesscapabilityinfor14, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_ueradioaccesscapabilityinfor14 {
		val_ueradioaccesscapabilityinfor14, err := per.DecodeOctetString(bb, 0, 0, false)
		if err != nil {
			return fmt.Errorf("decoding ue-RadioAccessCapabilityInfo-r14: %w", err)
		}
		tmp_ueradioaccesscapabilityinfor14 := val_ueradioaccesscapabilityinfor14
		v.UeRadioAccessCapabilityInfoR14 = tmp_ueradioaccesscapabilityinfor14
	}
	if opt_noncriticalextension {
		tmp_noncriticalextension := runtime.RawValue{}
		v.NonCriticalExtension = &tmp_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNBV1380IEs to UPER format.
func (v *UERadioAccessCapabilityInformationNBV1380IEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNBV1380IEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.LateNonCriticalExtension != nil); err != nil {
		return err
	}
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if v.LateNonCriticalExtension != nil {
		if err := per.EncodeOctetString(bb, v.LateNonCriticalExtension, 0, 0, false); err != nil {
			return fmt.Errorf("encoding lateNonCriticalExtension: %w", err)
		}
	}
	if v.NonCriticalExtension != nil {
		if err := v.NonCriticalExtension.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding nonCriticalExtension: %w", err)
		}
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNBV1380IEs from UPER format.
func (v *UERadioAccessCapabilityInformationNBV1380IEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNBV1380IEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_latenoncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	if opt_latenoncriticalextension {
		val_latenoncriticalextension, err := per.DecodeOctetString(bb, 0, 0, false)
		if err != nil {
			return fmt.Errorf("decoding lateNonCriticalExtension: %w", err)
		}
		tmp_latenoncriticalextension := val_latenoncriticalextension
		v.LateNonCriticalExtension = tmp_latenoncriticalextension
	}
	if opt_noncriticalextension {
		var dec_noncriticalextension UERadioAccessCapabilityInformationNBR14IEs
		if err := dec_noncriticalextension.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding nonCriticalExtension: %w", err)
		}
		v.NonCriticalExtension = &dec_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes UERadioPagingInformationNB to UPER format.
func (v *UERadioPagingInformationNB) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioPagingInformationNB) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding criticalExtensions: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes UERadioPagingInformationNB from UPER format.
func (v *UERadioPagingInformationNB) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioPagingInformationNB) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.CriticalExtensions.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding criticalExtensions: %w", err)
	}
	return nil
}

// MarshalUPER encodes UERadioPagingInformationNBIEs to UPER format.
func (v *UERadioPagingInformationNBIEs) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioPagingInformationNBIEs) marshalUPERTo(bb *per.BitBuffer) error {
	// Preamble bitmap for optional root fields
	if err := per.EncodeBoolean(bb, v.NonCriticalExtension != nil); err != nil {
		return err
	}
	if err := per.EncodeOctetString(bb, v.UeRadioPagingInfoR13, 0, 0, false); err != nil {
		return fmt.Errorf("encoding ue-RadioPagingInfo-r13: %w", err)
	}
	if v.NonCriticalExtension != nil {
	}
	return nil
}

// UnmarshalUPER decodes UERadioPagingInformationNBIEs from UPER format.
func (v *UERadioPagingInformationNBIEs) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioPagingInformationNBIEs) unmarshalUPERFrom(bb *per.BitBuffer) error {
	// Read preamble bitmap for optional root fields
	opt_noncriticalextension, err := per.DecodeBoolean(bb)
	if err != nil {
		return err
	}
	val_ueradiopaginginfor13, err := per.DecodeOctetString(bb, 0, 0, false)
	if err != nil {
		return fmt.Errorf("decoding ue-RadioPagingInfo-r13: %w", err)
	}
	v.UeRadioPagingInfoR13 = val_ueradiopaginginfor13
	if opt_noncriticalextension {
		tmp_noncriticalextension := runtime.RawValue{}
		v.NonCriticalExtension = &tmp_noncriticalextension
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNBCriticalExtensions to UPER format.
func (v *HandoverPreparationInformationNBCriticalExtensions) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNBCriticalExtensions) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 1); err != nil {
		return err
	}
	switch v.Choice {
	case HandoverPreparationInformationNBCriticalExtensionsChoiceC1:
		if err := v.C1.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding c1: %w", err)
		}
	case HandoverPreparationInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
	default:
		return fmt.Errorf("unknown HandoverPreparationInformationNBCriticalExtensions choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNBCriticalExtensions from UPER format.
func (v *HandoverPreparationInformationNBCriticalExtensions) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNBCriticalExtensions) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 1)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case HandoverPreparationInformationNBCriticalExtensionsChoiceC1:
		var dec_c1 HandoverPreparationInformationNBCriticalExtensionsC1
		if err := dec_c1.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding c1: %w", err)
		}
		v.C1 = &dec_c1
	case HandoverPreparationInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
		tmp_criticalextensionsfuture := runtime.RawValue{}
		v.CriticalExtensionsFuture = &tmp_criticalextensionsfuture
	}
	return nil
}

// MarshalUPER encodes HandoverPreparationInformationNBCriticalExtensionsC1 to UPER format.
func (v *HandoverPreparationInformationNBCriticalExtensionsC1) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *HandoverPreparationInformationNBCriticalExtensionsC1) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 3); err != nil {
		return err
	}
	switch v.Choice {
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceHandoverPreparationInformationR13:
		if err := v.HandoverPreparationInformationR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding handoverPreparationInformation-r13: %w", err)
		}
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare3:
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare2:
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare1:
	default:
		return fmt.Errorf("unknown HandoverPreparationInformationNBCriticalExtensionsC1 choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes HandoverPreparationInformationNBCriticalExtensionsC1 from UPER format.
func (v *HandoverPreparationInformationNBCriticalExtensionsC1) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *HandoverPreparationInformationNBCriticalExtensionsC1) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 3)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceHandoverPreparationInformationR13:
		var dec_handoverpreparationinformationr13 HandoverPreparationInformationNBIEs
		if err := dec_handoverpreparationinformationr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding handoverPreparationInformation-r13: %w", err)
		}
		v.HandoverPreparationInformationR13 = &dec_handoverpreparationinformationr13
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare3:
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare2:
	case HandoverPreparationInformationNBCriticalExtensionsC1ChoiceSpare1:
	}
	return nil
}

// MarshalUPER encodes UEPagingCoverageInformationNBCriticalExtensions to UPER format.
func (v *UEPagingCoverageInformationNBCriticalExtensions) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UEPagingCoverageInformationNBCriticalExtensions) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 1); err != nil {
		return err
	}
	switch v.Choice {
	case UEPagingCoverageInformationNBCriticalExtensionsChoiceC1:
		if err := v.C1.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding c1: %w", err)
		}
	case UEPagingCoverageInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
	default:
		return fmt.Errorf("unknown UEPagingCoverageInformationNBCriticalExtensions choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UEPagingCoverageInformationNBCriticalExtensions from UPER format.
func (v *UEPagingCoverageInformationNBCriticalExtensions) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UEPagingCoverageInformationNBCriticalExtensions) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 1)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UEPagingCoverageInformationNBCriticalExtensionsChoiceC1:
		var dec_c1 UEPagingCoverageInformationNBCriticalExtensionsC1
		if err := dec_c1.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding c1: %w", err)
		}
		v.C1 = &dec_c1
	case UEPagingCoverageInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
		tmp_criticalextensionsfuture := runtime.RawValue{}
		v.CriticalExtensionsFuture = &tmp_criticalextensionsfuture
	}
	return nil
}

// MarshalUPER encodes UEPagingCoverageInformationNBCriticalExtensionsC1 to UPER format.
func (v *UEPagingCoverageInformationNBCriticalExtensionsC1) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UEPagingCoverageInformationNBCriticalExtensionsC1) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 3); err != nil {
		return err
	}
	switch v.Choice {
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceUePagingCoverageInformationR13:
		if err := v.UePagingCoverageInformationR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding uePagingCoverageInformation-r13: %w", err)
		}
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare1:
	default:
		return fmt.Errorf("unknown UEPagingCoverageInformationNBCriticalExtensionsC1 choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UEPagingCoverageInformationNBCriticalExtensionsC1 from UPER format.
func (v *UEPagingCoverageInformationNBCriticalExtensionsC1) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UEPagingCoverageInformationNBCriticalExtensionsC1) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 3)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceUePagingCoverageInformationR13:
		var dec_uepagingcoverageinformationr13 UEPagingCoverageInformationNBIEs
		if err := dec_uepagingcoverageinformationr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding uePagingCoverageInformation-r13: %w", err)
		}
		v.UePagingCoverageInformationR13 = &dec_uepagingcoverageinformationr13
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UEPagingCoverageInformationNBCriticalExtensionsC1ChoiceSpare1:
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNBCriticalExtensions to UPER format.
func (v *UERadioAccessCapabilityInformationNBCriticalExtensions) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNBCriticalExtensions) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 1); err != nil {
		return err
	}
	switch v.Choice {
	case UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceC1:
		if err := v.C1.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding c1: %w", err)
		}
	case UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
	default:
		return fmt.Errorf("unknown UERadioAccessCapabilityInformationNBCriticalExtensions choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNBCriticalExtensions from UPER format.
func (v *UERadioAccessCapabilityInformationNBCriticalExtensions) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNBCriticalExtensions) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 1)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceC1:
		var dec_c1 UERadioAccessCapabilityInformationNBCriticalExtensionsC1
		if err := dec_c1.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding c1: %w", err)
		}
		v.C1 = &dec_c1
	case UERadioAccessCapabilityInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
		tmp_criticalextensionsfuture := runtime.RawValue{}
		v.CriticalExtensionsFuture = &tmp_criticalextensionsfuture
	}
	return nil
}

// MarshalUPER encodes UERadioAccessCapabilityInformationNBCriticalExtensionsC1 to UPER format.
func (v *UERadioAccessCapabilityInformationNBCriticalExtensionsC1) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioAccessCapabilityInformationNBCriticalExtensionsC1) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 3); err != nil {
		return err
	}
	switch v.Choice {
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceUeRadioAccessCapabilityInformationR13:
		if err := v.UeRadioAccessCapabilityInformationR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding ueRadioAccessCapabilityInformation-r13: %w", err)
		}
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare1:
	default:
		return fmt.Errorf("unknown UERadioAccessCapabilityInformationNBCriticalExtensionsC1 choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UERadioAccessCapabilityInformationNBCriticalExtensionsC1 from UPER format.
func (v *UERadioAccessCapabilityInformationNBCriticalExtensionsC1) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioAccessCapabilityInformationNBCriticalExtensionsC1) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 3)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceUeRadioAccessCapabilityInformationR13:
		var dec_ueradioaccesscapabilityinformationr13 UERadioAccessCapabilityInformationNBIEs
		if err := dec_ueradioaccesscapabilityinformationr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding ueRadioAccessCapabilityInformation-r13: %w", err)
		}
		v.UeRadioAccessCapabilityInformationR13 = &dec_ueradioaccesscapabilityinformationr13
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UERadioAccessCapabilityInformationNBCriticalExtensionsC1ChoiceSpare1:
	}
	return nil
}

// MarshalUPER encodes UERadioPagingInformationNBCriticalExtensions to UPER format.
func (v *UERadioPagingInformationNBCriticalExtensions) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioPagingInformationNBCriticalExtensions) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 1); err != nil {
		return err
	}
	switch v.Choice {
	case UERadioPagingInformationNBCriticalExtensionsChoiceC1:
		if err := v.C1.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding c1: %w", err)
		}
	case UERadioPagingInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
	default:
		return fmt.Errorf("unknown UERadioPagingInformationNBCriticalExtensions choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UERadioPagingInformationNBCriticalExtensions from UPER format.
func (v *UERadioPagingInformationNBCriticalExtensions) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioPagingInformationNBCriticalExtensions) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 1)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UERadioPagingInformationNBCriticalExtensionsChoiceC1:
		var dec_c1 UERadioPagingInformationNBCriticalExtensionsC1
		if err := dec_c1.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding c1: %w", err)
		}
		v.C1 = &dec_c1
	case UERadioPagingInformationNBCriticalExtensionsChoiceCriticalExtensionsFuture:
		tmp_criticalextensionsfuture := runtime.RawValue{}
		v.CriticalExtensionsFuture = &tmp_criticalextensionsfuture
	}
	return nil
}

// MarshalUPER encodes UERadioPagingInformationNBCriticalExtensionsC1 to UPER format.
func (v *UERadioPagingInformationNBCriticalExtensionsC1) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *UERadioPagingInformationNBCriticalExtensionsC1) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeConstrainedWholeNumber(bb, int64(v.Choice-1), 0, 3); err != nil {
		return err
	}
	switch v.Choice {
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceUeRadioPagingInformationR13:
		if err := v.UeRadioPagingInformationR13.marshalUPERTo(bb); err != nil {
			return fmt.Errorf("encoding ueRadioPagingInformation-r13: %w", err)
		}
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare1:
	default:
		return fmt.Errorf("unknown UERadioPagingInformationNBCriticalExtensionsC1 choice %d", v.Choice)
	}
	return nil
}

// UnmarshalUPER decodes UERadioPagingInformationNBCriticalExtensionsC1 from UPER format.
func (v *UERadioPagingInformationNBCriticalExtensionsC1) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *UERadioPagingInformationNBCriticalExtensionsC1) unmarshalUPERFrom(bb *per.BitBuffer) error {
	idx, err := per.DecodeConstrainedWholeNumber(bb, 0, 3)
	if err != nil {
		return err
	}
	v.Choice = int(idx) + 1
	switch v.Choice {
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceUeRadioPagingInformationR13:
		var dec_ueradiopaginginformationr13 UERadioPagingInformationNBIEs
		if err := dec_ueradiopaginginformationr13.unmarshalUPERFrom(bb); err != nil {
			return fmt.Errorf("decoding ueRadioPagingInformation-r13: %w", err)
		}
		v.UeRadioPagingInformationR13 = &dec_ueradiopaginginformationr13
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare3:
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare2:
	case UERadioPagingInformationNBCriticalExtensionsC1ChoiceSpare1:
	}
	return nil
}
