// Code generated by asn1c-go from ASN.1 module "PC5-RRC-Definitions". DO NOT EDIT.

package lte_rrc

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/per"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = per.NewBitBuffer
)

// MasterInformationBlockSL represents the ASN.1 type MasterInformationBlock-SL (SEQUENCE).
type MasterInformationBlockSL struct {
	SlBandwidthR12          int64             `asn1:"tag:0,context,implicit"`
	TddConfigSLR12          TDDConfigSLR12    `asn1:"tag:1,context,implicit"`
	DirectFrameNumberR12    runtime.BitString `asn1:"tag:2,context,implicit"`
	DirectSubframeNumberR12 int64             `asn1:"tag:3,context,implicit"`
	InCoverageR12           bool              `asn1:"tag:4,context,implicit"`
	InCoverageR12Raw_       byte              `asn1:"-" json:"-"`
	ReservedR12             runtime.BitString `asn1:"tag:5,context,implicit"`
}

// MasterInformationBlockSLV2XR14 represents the ASN.1 type MasterInformationBlock-SL-V2X-r14 (SEQUENCE).
type MasterInformationBlockSLV2XR14 struct {
	SlBandwidthR14          int64             `asn1:"tag:0,context,implicit"`
	TddConfigSLR14          TDDConfigSLR12    `asn1:"tag:1,context,implicit"`
	DirectFrameNumberR14    runtime.BitString `asn1:"tag:2,context,implicit"`
	DirectSubframeNumberR14 int64             `asn1:"tag:3,context,implicit"`
	InCoverageR14           bool              `asn1:"tag:4,context,implicit"`
	InCoverageR14Raw_       byte              `asn1:"-" json:"-"`
	ReservedR14             runtime.BitString `asn1:"tag:5,context,implicit"`
}

// SBCCHSLBCHMessage represents the ASN.1 type SBCCH-SL-BCH-Message (SEQUENCE).
type SBCCHSLBCHMessage struct {
	Message SBCCHSLBCHMessageType `asn1:"tag:0,context,implicit"`
}

// SBCCHSLBCHMessageType represents the ASN.1 type SBCCH-SL-BCH-MessageType (SEQUENCE).
type SBCCHSLBCHMessageType struct {
	SlBandwidthR12          int64             `asn1:"tag:0,context,implicit"`
	TddConfigSLR12          TDDConfigSLR12    `asn1:"tag:1,context,implicit"`
	DirectFrameNumberR12    runtime.BitString `asn1:"tag:2,context,implicit"`
	DirectSubframeNumberR12 int64             `asn1:"tag:3,context,implicit"`
	InCoverageR12           bool              `asn1:"tag:4,context,implicit"`
	InCoverageR12Raw_       byte              `asn1:"-" json:"-"`
	ReservedR12             runtime.BitString `asn1:"tag:5,context,implicit"`
}

// SBCCHSLBCHMessageTypeV2XR14 represents the ASN.1 type SBCCH-SL-BCH-MessageType-V2X-r14 (SEQUENCE).
type SBCCHSLBCHMessageTypeV2XR14 struct {
	SlBandwidthR14          int64             `asn1:"tag:0,context,implicit"`
	TddConfigSLR14          TDDConfigSLR12    `asn1:"tag:1,context,implicit"`
	DirectFrameNumberR14    runtime.BitString `asn1:"tag:2,context,implicit"`
	DirectSubframeNumberR14 int64             `asn1:"tag:3,context,implicit"`
	InCoverageR14           bool              `asn1:"tag:4,context,implicit"`
	InCoverageR14Raw_       byte              `asn1:"-" json:"-"`
	ReservedR14             runtime.BitString `asn1:"tag:5,context,implicit"`
}

// SBCCHSLBCHMessageV2XR14 represents the ASN.1 type SBCCH-SL-BCH-Message-V2X-r14 (SEQUENCE).
type SBCCHSLBCHMessageV2XR14 struct {
	Message SBCCHSLBCHMessageTypeV2XR14 `asn1:"tag:0,context,implicit"`
}

// MarshalUPER encodes MasterInformationBlockSL to UPER format.
func (v *MasterInformationBlockSL) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *MasterInformationBlockSL) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeEnumerated(bb, int64(v.SlBandwidthR12), 6, false); err != nil {
		return fmt.Errorf("encoding sl-Bandwidth-r12: %w", err)
	}
	if err := v.TddConfigSLR12.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding tdd-ConfigSL-r12: %w", err)
	}
	if err := per.EncodeBitString(bb, v.DirectFrameNumberR12.Bytes, v.DirectFrameNumberR12.BitLength, 10, 10, true); err != nil {
		return fmt.Errorf("encoding directFrameNumber-r12: %w", err)
	}
	if err := per.EncodeInteger(bb, int64(v.DirectSubframeNumberR12), int64Ptr(0), int64Ptr(9), false); err != nil {
		return fmt.Errorf("encoding directSubframeNumber-r12: %w", err)
	}
	if err := per.EncodeBoolean(bb, v.InCoverageR12); err != nil {
		return fmt.Errorf("encoding inCoverage-r12: %w", err)
	}
	if err := per.EncodeBitString(bb, v.ReservedR12.Bytes, v.ReservedR12.BitLength, 19, 19, true); err != nil {
		return fmt.Errorf("encoding reserved-r12: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes MasterInformationBlockSL from UPER format.
func (v *MasterInformationBlockSL) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *MasterInformationBlockSL) unmarshalUPERFrom(bb *per.BitBuffer) error {
	val_slbandwidthr12, err := per.DecodeEnumerated(bb, 6, false)
	if err != nil {
		return fmt.Errorf("decoding sl-Bandwidth-r12: %w", err)
	}
	v.SlBandwidthR12 = val_slbandwidthr12
	if err := v.TddConfigSLR12.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding tdd-ConfigSL-r12: %w", err)
	}
	bsBytes_directframenumberr12, bsBitLen_directframenumberr12, err := per.DecodeBitString(bb, 10, 10, true)
	if err != nil {
		return fmt.Errorf("decoding directFrameNumber-r12: %w", err)
	}
	v.DirectFrameNumberR12 = runtime.BitString{Bytes: bsBytes_directframenumberr12, BitLength: bsBitLen_directframenumberr12}
	val_directsubframenumberr12, err := per.DecodeInteger(bb, int64Ptr(0), int64Ptr(9), false)
	if err != nil {
		return fmt.Errorf("decoding directSubframeNumber-r12: %w", err)
	}
	v.DirectSubframeNumberR12 = val_directsubframenumberr12
	val_incoverager12, err := per.DecodeBoolean(bb)
	if err != nil {
		return fmt.Errorf("decoding inCoverage-r12: %w", err)
	}
	v.InCoverageR12 = val_incoverager12
	bsBytes_reservedr12, bsBitLen_reservedr12, err := per.DecodeBitString(bb, 19, 19, true)
	if err != nil {
		return fmt.Errorf("decoding reserved-r12: %w", err)
	}
	v.ReservedR12 = runtime.BitString{Bytes: bsBytes_reservedr12, BitLength: bsBitLen_reservedr12}
	return nil
}

// MarshalUPER encodes MasterInformationBlockSLV2XR14 to UPER format.
func (v *MasterInformationBlockSLV2XR14) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *MasterInformationBlockSLV2XR14) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeEnumerated(bb, int64(v.SlBandwidthR14), 6, false); err != nil {
		return fmt.Errorf("encoding sl-Bandwidth-r14: %w", err)
	}
	if err := v.TddConfigSLR14.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding tdd-ConfigSL-r14: %w", err)
	}
	if err := per.EncodeBitString(bb, v.DirectFrameNumberR14.Bytes, v.DirectFrameNumberR14.BitLength, 10, 10, true); err != nil {
		return fmt.Errorf("encoding directFrameNumber-r14: %w", err)
	}
	if err := per.EncodeInteger(bb, int64(v.DirectSubframeNumberR14), int64Ptr(0), int64Ptr(9), false); err != nil {
		return fmt.Errorf("encoding directSubframeNumber-r14: %w", err)
	}
	if err := per.EncodeBoolean(bb, v.InCoverageR14); err != nil {
		return fmt.Errorf("encoding inCoverage-r14: %w", err)
	}
	if err := per.EncodeBitString(bb, v.ReservedR14.Bytes, v.ReservedR14.BitLength, 27, 27, true); err != nil {
		return fmt.Errorf("encoding reserved-r14: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes MasterInformationBlockSLV2XR14 from UPER format.
func (v *MasterInformationBlockSLV2XR14) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *MasterInformationBlockSLV2XR14) unmarshalUPERFrom(bb *per.BitBuffer) error {
	val_slbandwidthr14, err := per.DecodeEnumerated(bb, 6, false)
	if err != nil {
		return fmt.Errorf("decoding sl-Bandwidth-r14: %w", err)
	}
	v.SlBandwidthR14 = val_slbandwidthr14
	if err := v.TddConfigSLR14.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding tdd-ConfigSL-r14: %w", err)
	}
	bsBytes_directframenumberr14, bsBitLen_directframenumberr14, err := per.DecodeBitString(bb, 10, 10, true)
	if err != nil {
		return fmt.Errorf("decoding directFrameNumber-r14: %w", err)
	}
	v.DirectFrameNumberR14 = runtime.BitString{Bytes: bsBytes_directframenumberr14, BitLength: bsBitLen_directframenumberr14}
	val_directsubframenumberr14, err := per.DecodeInteger(bb, int64Ptr(0), int64Ptr(9), false)
	if err != nil {
		return fmt.Errorf("decoding directSubframeNumber-r14: %w", err)
	}
	v.DirectSubframeNumberR14 = val_directsubframenumberr14
	val_incoverager14, err := per.DecodeBoolean(bb)
	if err != nil {
		return fmt.Errorf("decoding inCoverage-r14: %w", err)
	}
	v.InCoverageR14 = val_incoverager14
	bsBytes_reservedr14, bsBitLen_reservedr14, err := per.DecodeBitString(bb, 27, 27, true)
	if err != nil {
		return fmt.Errorf("decoding reserved-r14: %w", err)
	}
	v.ReservedR14 = runtime.BitString{Bytes: bsBytes_reservedr14, BitLength: bsBitLen_reservedr14}
	return nil
}

// MarshalUPER encodes SBCCHSLBCHMessage to UPER format.
func (v *SBCCHSLBCHMessage) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *SBCCHSLBCHMessage) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.Message.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding message: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes SBCCHSLBCHMessage from UPER format.
func (v *SBCCHSLBCHMessage) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *SBCCHSLBCHMessage) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.Message.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding message: %w", err)
	}
	return nil
}

// MarshalUPER encodes SBCCHSLBCHMessageType to UPER format.
func (v *SBCCHSLBCHMessageType) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *SBCCHSLBCHMessageType) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeEnumerated(bb, int64(v.SlBandwidthR12), 6, false); err != nil {
		return fmt.Errorf("encoding sl-Bandwidth-r12: %w", err)
	}
	if err := v.TddConfigSLR12.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding tdd-ConfigSL-r12: %w", err)
	}
	if err := per.EncodeBitString(bb, v.DirectFrameNumberR12.Bytes, v.DirectFrameNumberR12.BitLength, 10, 10, true); err != nil {
		return fmt.Errorf("encoding directFrameNumber-r12: %w", err)
	}
	if err := per.EncodeInteger(bb, int64(v.DirectSubframeNumberR12), int64Ptr(0), int64Ptr(9), false); err != nil {
		return fmt.Errorf("encoding directSubframeNumber-r12: %w", err)
	}
	if err := per.EncodeBoolean(bb, v.InCoverageR12); err != nil {
		return fmt.Errorf("encoding inCoverage-r12: %w", err)
	}
	if err := per.EncodeBitString(bb, v.ReservedR12.Bytes, v.ReservedR12.BitLength, 19, 19, true); err != nil {
		return fmt.Errorf("encoding reserved-r12: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes SBCCHSLBCHMessageType from UPER format.
func (v *SBCCHSLBCHMessageType) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *SBCCHSLBCHMessageType) unmarshalUPERFrom(bb *per.BitBuffer) error {
	val_slbandwidthr12, err := per.DecodeEnumerated(bb, 6, false)
	if err != nil {
		return fmt.Errorf("decoding sl-Bandwidth-r12: %w", err)
	}
	v.SlBandwidthR12 = val_slbandwidthr12
	if err := v.TddConfigSLR12.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding tdd-ConfigSL-r12: %w", err)
	}
	bsBytes_directframenumberr12, bsBitLen_directframenumberr12, err := per.DecodeBitString(bb, 10, 10, true)
	if err != nil {
		return fmt.Errorf("decoding directFrameNumber-r12: %w", err)
	}
	v.DirectFrameNumberR12 = runtime.BitString{Bytes: bsBytes_directframenumberr12, BitLength: bsBitLen_directframenumberr12}
	val_directsubframenumberr12, err := per.DecodeInteger(bb, int64Ptr(0), int64Ptr(9), false)
	if err != nil {
		return fmt.Errorf("decoding directSubframeNumber-r12: %w", err)
	}
	v.DirectSubframeNumberR12 = val_directsubframenumberr12
	val_incoverager12, err := per.DecodeBoolean(bb)
	if err != nil {
		return fmt.Errorf("decoding inCoverage-r12: %w", err)
	}
	v.InCoverageR12 = val_incoverager12
	bsBytes_reservedr12, bsBitLen_reservedr12, err := per.DecodeBitString(bb, 19, 19, true)
	if err != nil {
		return fmt.Errorf("decoding reserved-r12: %w", err)
	}
	v.ReservedR12 = runtime.BitString{Bytes: bsBytes_reservedr12, BitLength: bsBitLen_reservedr12}
	return nil
}

// MarshalUPER encodes SBCCHSLBCHMessageTypeV2XR14 to UPER format.
func (v *SBCCHSLBCHMessageTypeV2XR14) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *SBCCHSLBCHMessageTypeV2XR14) marshalUPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeEnumerated(bb, int64(v.SlBandwidthR14), 6, false); err != nil {
		return fmt.Errorf("encoding sl-Bandwidth-r14: %w", err)
	}
	if err := v.TddConfigSLR14.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding tdd-ConfigSL-r14: %w", err)
	}
	if err := per.EncodeBitString(bb, v.DirectFrameNumberR14.Bytes, v.DirectFrameNumberR14.BitLength, 10, 10, true); err != nil {
		return fmt.Errorf("encoding directFrameNumber-r14: %w", err)
	}
	if err := per.EncodeInteger(bb, int64(v.DirectSubframeNumberR14), int64Ptr(0), int64Ptr(9), false); err != nil {
		return fmt.Errorf("encoding directSubframeNumber-r14: %w", err)
	}
	if err := per.EncodeBoolean(bb, v.InCoverageR14); err != nil {
		return fmt.Errorf("encoding inCoverage-r14: %w", err)
	}
	if err := per.EncodeBitString(bb, v.ReservedR14.Bytes, v.ReservedR14.BitLength, 27, 27, true); err != nil {
		return fmt.Errorf("encoding reserved-r14: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes SBCCHSLBCHMessageTypeV2XR14 from UPER format.
func (v *SBCCHSLBCHMessageTypeV2XR14) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *SBCCHSLBCHMessageTypeV2XR14) unmarshalUPERFrom(bb *per.BitBuffer) error {
	val_slbandwidthr14, err := per.DecodeEnumerated(bb, 6, false)
	if err != nil {
		return fmt.Errorf("decoding sl-Bandwidth-r14: %w", err)
	}
	v.SlBandwidthR14 = val_slbandwidthr14
	if err := v.TddConfigSLR14.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding tdd-ConfigSL-r14: %w", err)
	}
	bsBytes_directframenumberr14, bsBitLen_directframenumberr14, err := per.DecodeBitString(bb, 10, 10, true)
	if err != nil {
		return fmt.Errorf("decoding directFrameNumber-r14: %w", err)
	}
	v.DirectFrameNumberR14 = runtime.BitString{Bytes: bsBytes_directframenumberr14, BitLength: bsBitLen_directframenumberr14}
	val_directsubframenumberr14, err := per.DecodeInteger(bb, int64Ptr(0), int64Ptr(9), false)
	if err != nil {
		return fmt.Errorf("decoding directSubframeNumber-r14: %w", err)
	}
	v.DirectSubframeNumberR14 = val_directsubframenumberr14
	val_incoverager14, err := per.DecodeBoolean(bb)
	if err != nil {
		return fmt.Errorf("decoding inCoverage-r14: %w", err)
	}
	v.InCoverageR14 = val_incoverager14
	bsBytes_reservedr14, bsBitLen_reservedr14, err := per.DecodeBitString(bb, 27, 27, true)
	if err != nil {
		return fmt.Errorf("decoding reserved-r14: %w", err)
	}
	v.ReservedR14 = runtime.BitString{Bytes: bsBytes_reservedr14, BitLength: bsBitLen_reservedr14}
	return nil
}

// MarshalUPER encodes SBCCHSLBCHMessageV2XR14 to UPER format.
func (v *SBCCHSLBCHMessageV2XR14) MarshalUPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalUPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *SBCCHSLBCHMessageV2XR14) marshalUPERTo(bb *per.BitBuffer) error {
	if err := v.Message.marshalUPERTo(bb); err != nil {
		return fmt.Errorf("encoding message: %w", err)
	}
	return nil
}

// UnmarshalUPER decodes SBCCHSLBCHMessageV2XR14 from UPER format.
func (v *SBCCHSLBCHMessageV2XR14) UnmarshalUPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalUPERFrom(bb)
}

func (v *SBCCHSLBCHMessageV2XR14) unmarshalUPERFrom(bb *per.BitBuffer) error {
	if err := v.Message.unmarshalUPERFrom(bb); err != nil {
		return fmt.Errorf("decoding message: %w", err)
	}
	return nil
}
