// Code generated by asn1c-go from ASN.1 module "X2AP-Containers". DO NOT EDIT.

package x2ap

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/per"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = per.NewBitBuffer
)

// PrivateIEContainer represents the ASN.1 type PrivateIE-Container (SEQUENCE_OF).
type PrivateIEContainer = []PrivateIEField

// PrivateIEField represents the ASN.1 type PrivateIE-Field (SEQUENCE).
type PrivateIEField struct {
	Id          ProtocolIEID     `asn1:""`
	Criticality Criticality      `asn1:""`
	Value       runtime.RawValue `asn1:""`
}

// ProtocolExtensionContainer represents the ASN.1 type ProtocolExtensionContainer (SEQUENCE_OF).
type ProtocolExtensionContainer = []ProtocolExtensionField

// ProtocolExtensionField represents the ASN.1 type ProtocolExtensionField (SEQUENCE).
type ProtocolExtensionField struct {
	Id             ProtocolIEID     `asn1:""`
	Criticality    Criticality      `asn1:""`
	ExtensionValue runtime.RawValue `asn1:""`
}

// ProtocolIEContainer represents the ASN.1 type ProtocolIE-Container (SEQUENCE_OF).
type ProtocolIEContainer = []ProtocolIEField

// ProtocolIEContainerList represents the ASN.1 type ProtocolIE-ContainerList (SEQUENCE_OF).
type ProtocolIEContainerList = []ProtocolIEContainer

// ProtocolIEContainerPair represents the ASN.1 type ProtocolIE-ContainerPair (SEQUENCE_OF).
type ProtocolIEContainerPair = []ProtocolIEFieldPair

// ProtocolIEContainerPairList represents the ASN.1 type ProtocolIE-ContainerPairList (SEQUENCE_OF).
type ProtocolIEContainerPairList = []ProtocolIEContainerPair

// ProtocolIEField represents the ASN.1 type ProtocolIE-Field (SEQUENCE).
type ProtocolIEField struct {
	Id          ProtocolIEID     `asn1:""`
	Criticality Criticality      `asn1:""`
	Value       runtime.RawValue `asn1:""`
}

// ProtocolIEFieldPair represents the ASN.1 type ProtocolIE-FieldPair (SEQUENCE).
type ProtocolIEFieldPair struct {
	Id                ProtocolIEID     `asn1:""`
	FirstCriticality  Criticality      `asn1:""`
	FirstValue        runtime.RawValue `asn1:""`
	SecondCriticality Criticality      `asn1:""`
	SecondValue       runtime.RawValue `asn1:""`
}

// ProtocolIESingleContainer represents the ASN.1 type ProtocolIE-Single-Container (SEQUENCE).
type ProtocolIESingleContainer = ProtocolIEField

// MarshalAPER encodes PrivateIEField to APER format.
func (v *PrivateIEField) MarshalAPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalAPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *PrivateIEField) marshalAPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeIntegerAligned(bb, int64(v.Id), int64Ptr(0), int64Ptr(65535), false); err != nil {
		return fmt.Errorf("encoding id: %w", err)
	}
	if err := per.EncodeEnumeratedAligned(bb, int64(v.Criticality), 3, false); err != nil {
		return fmt.Errorf("encoding criticality: %w", err)
	}
	if err := per.EncodeOpenTypeAligned(bb, v.Value.Bytes); err != nil {
		return fmt.Errorf("encoding value: %w", err)
	}
	return nil
}

// UnmarshalAPER decodes PrivateIEField from APER format.
func (v *PrivateIEField) UnmarshalAPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalAPERFrom(bb)
}

func (v *PrivateIEField) unmarshalAPERFrom(bb *per.BitBuffer) error {
	val_id, err := per.DecodeIntegerAligned(bb, int64Ptr(0), int64Ptr(65535), false)
	if err != nil {
		return fmt.Errorf("decoding id: %w", err)
	}
	v.Id = val_id
	val_criticality, err := per.DecodeEnumeratedAligned(bb, 3, false)
	if err != nil {
		return fmt.Errorf("decoding criticality: %w", err)
	}
	v.Criticality = Criticality(val_criticality)
	openData_value, err := per.DecodeOpenTypeAligned(bb)
	if err != nil {
		return fmt.Errorf("decoding value: %w", err)
	}
	v.Value = runtime.RawValue{Bytes: openData_value}
	return nil
}

// MarshalAPER encodes ProtocolExtensionField to APER format.
func (v *ProtocolExtensionField) MarshalAPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalAPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ProtocolExtensionField) marshalAPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeIntegerAligned(bb, int64(v.Id), int64Ptr(0), int64Ptr(65535), false); err != nil {
		return fmt.Errorf("encoding id: %w", err)
	}
	if err := per.EncodeEnumeratedAligned(bb, int64(v.Criticality), 3, false); err != nil {
		return fmt.Errorf("encoding criticality: %w", err)
	}
	if err := per.EncodeOpenTypeAligned(bb, v.ExtensionValue.Bytes); err != nil {
		return fmt.Errorf("encoding extensionValue: %w", err)
	}
	return nil
}

// UnmarshalAPER decodes ProtocolExtensionField from APER format.
func (v *ProtocolExtensionField) UnmarshalAPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalAPERFrom(bb)
}

func (v *ProtocolExtensionField) unmarshalAPERFrom(bb *per.BitBuffer) error {
	val_id, err := per.DecodeIntegerAligned(bb, int64Ptr(0), int64Ptr(65535), false)
	if err != nil {
		return fmt.Errorf("decoding id: %w", err)
	}
	v.Id = val_id
	val_criticality, err := per.DecodeEnumeratedAligned(bb, 3, false)
	if err != nil {
		return fmt.Errorf("decoding criticality: %w", err)
	}
	v.Criticality = Criticality(val_criticality)
	openData_extensionvalue, err := per.DecodeOpenTypeAligned(bb)
	if err != nil {
		return fmt.Errorf("decoding extensionValue: %w", err)
	}
	v.ExtensionValue = runtime.RawValue{Bytes: openData_extensionvalue}
	return nil
}

// MarshalAPER encodes ProtocolIEField to APER format.
func (v *ProtocolIEField) MarshalAPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalAPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ProtocolIEField) marshalAPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeIntegerAligned(bb, int64(v.Id), int64Ptr(0), int64Ptr(65535), false); err != nil {
		return fmt.Errorf("encoding id: %w", err)
	}
	if err := per.EncodeEnumeratedAligned(bb, int64(v.Criticality), 3, false); err != nil {
		return fmt.Errorf("encoding criticality: %w", err)
	}
	if err := per.EncodeOpenTypeAligned(bb, v.Value.Bytes); err != nil {
		return fmt.Errorf("encoding value: %w", err)
	}
	return nil
}

// UnmarshalAPER decodes ProtocolIEField from APER format.
func (v *ProtocolIEField) UnmarshalAPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalAPERFrom(bb)
}

func (v *ProtocolIEField) unmarshalAPERFrom(bb *per.BitBuffer) error {
	val_id, err := per.DecodeIntegerAligned(bb, int64Ptr(0), int64Ptr(65535), false)
	if err != nil {
		return fmt.Errorf("decoding id: %w", err)
	}
	v.Id = val_id
	val_criticality, err := per.DecodeEnumeratedAligned(bb, 3, false)
	if err != nil {
		return fmt.Errorf("decoding criticality: %w", err)
	}
	v.Criticality = Criticality(val_criticality)
	openData_value, err := per.DecodeOpenTypeAligned(bb)
	if err != nil {
		return fmt.Errorf("decoding value: %w", err)
	}
	v.Value = runtime.RawValue{Bytes: openData_value}
	return nil
}

// MarshalAPER encodes ProtocolIEFieldPair to APER format.
func (v *ProtocolIEFieldPair) MarshalAPER() ([]byte, error) {
	bb := per.NewBitBuffer()
	if err := v.marshalAPERTo(bb); err != nil {
		return nil, err
	}
	return bb.Bytes(), nil
}

func (v *ProtocolIEFieldPair) marshalAPERTo(bb *per.BitBuffer) error {
	if err := per.EncodeIntegerAligned(bb, int64(v.Id), int64Ptr(0), int64Ptr(65535), false); err != nil {
		return fmt.Errorf("encoding id: %w", err)
	}
	if err := per.EncodeEnumeratedAligned(bb, int64(v.FirstCriticality), 3, false); err != nil {
		return fmt.Errorf("encoding firstCriticality: %w", err)
	}
	if err := per.EncodeOpenTypeAligned(bb, v.FirstValue.Bytes); err != nil {
		return fmt.Errorf("encoding firstValue: %w", err)
	}
	if err := per.EncodeEnumeratedAligned(bb, int64(v.SecondCriticality), 3, false); err != nil {
		return fmt.Errorf("encoding secondCriticality: %w", err)
	}
	if err := per.EncodeOpenTypeAligned(bb, v.SecondValue.Bytes); err != nil {
		return fmt.Errorf("encoding secondValue: %w", err)
	}
	return nil
}

// UnmarshalAPER decodes ProtocolIEFieldPair from APER format.
func (v *ProtocolIEFieldPair) UnmarshalAPER(data []byte) error {
	bb := per.NewBitBufferFromBytes(data)
	return v.unmarshalAPERFrom(bb)
}

func (v *ProtocolIEFieldPair) unmarshalAPERFrom(bb *per.BitBuffer) error {
	val_id, err := per.DecodeIntegerAligned(bb, int64Ptr(0), int64Ptr(65535), false)
	if err != nil {
		return fmt.Errorf("decoding id: %w", err)
	}
	v.Id = val_id
	val_firstcriticality, err := per.DecodeEnumeratedAligned(bb, 3, false)
	if err != nil {
		return fmt.Errorf("decoding firstCriticality: %w", err)
	}
	v.FirstCriticality = Criticality(val_firstcriticality)
	openData_firstvalue, err := per.DecodeOpenTypeAligned(bb)
	if err != nil {
		return fmt.Errorf("decoding firstValue: %w", err)
	}
	v.FirstValue = runtime.RawValue{Bytes: openData_firstvalue}
	val_secondcriticality, err := per.DecodeEnumeratedAligned(bb, 3, false)
	if err != nil {
		return fmt.Errorf("decoding secondCriticality: %w", err)
	}
	v.SecondCriticality = Criticality(val_secondcriticality)
	openData_secondvalue, err := per.DecodeOpenTypeAligned(bb)
	if err != nil {
		return fmt.Errorf("decoding secondValue: %w", err)
	}
	v.SecondValue = runtime.RawValue{Bytes: openData_secondvalue}
	return nil
}
