// Code generated by asn1c-go from ASN.1 module "X2AP-Constants". DO NOT EDIT.

package x2ap

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/per"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = per.NewBitBuffer
)

// IdABSInformation is the integer value for id-ABSInformation.
const IdABSInformation int64 = 61

// IdABSStatus is the integer value for id-ABS-Status.
const IdABSStatus int64 = 63

// IdActivatedCellList is the integer value for id-ActivatedCellList.
const IdActivatedCellList int64 = 58

// IdActivatedNRCellList is the integer value for id-ActivatedNRCellList.
const IdActivatedNRCellList int64 = 268

// IdActivationID is the integer value for id-ActivationID.
const IdActivationID int64 = 256

// IdAdditionLocationInformation is the integer value for id-AdditionLocationInformation.
const IdAdditionLocationInformation int64 = 409

// IdAdditionalListofForwardingGTPTunnelEndpoint is the integer value for id-AdditionalListofForwardingGTPTunnelEndpoint.
const IdAdditionalListofForwardingGTPTunnelEndpoint int64 = 441

// IdAdditionalRRMPriorityIndex is the integer value for id-AdditionalRRMPriorityIndex.
const IdAdditionalRRMPriorityIndex int64 = 340

// IdAdditionalSpecialSubframeExtensionInfo is the integer value for id-AdditionalSpecialSubframeExtension-Info.
const IdAdditionalSpecialSubframeExtensionInfo int64 = 179

// IdAdditionalSpecialSubframeInfo is the integer value for id-AdditionalSpecialSubframe-Info.
const IdAdditionalSpecialSubframeInfo int64 = 97

// IdAdditionalMeasurementTimingConfigurationList is the integer value for id-Additional-Measurement-Timing-Configuration-List.
const IdAdditionalMeasurementTimingConfigurationList int64 = 433

// IdAdmittedSplitSRBs is the integer value for id-AdmittedSplitSRBs.
const IdAdmittedSplitSRBs int64 = 212

// IdAdmittedSplitSRBsrelease is the integer value for id-AdmittedSplitSRBsrelease.
const IdAdmittedSplitSRBsrelease int64 = 281

// IdAerialUEsubscriptionInformation is the integer value for id-AerialUEsubscriptionInformation.
const IdAerialUEsubscriptionInformation int64 = 277

// IdAvailableFastMCGRecoveryViaSRB3 is the integer value for id-AvailableFastMCGRecoveryViaSRB3.
const IdAvailableFastMCGRecoveryViaSRB3 int64 = 344

// IdBPLMNIDInfoEUTRA is the integer value for id-BPLMN-ID-Info-EUTRA.
const IdBPLMNIDInfoEUTRA int64 = 336

// IdBPLMNIDInfoNR is the integer value for id-BPLMN-ID-Info-NR.
const IdBPLMNIDInfoNR int64 = 337

// IdBandwidthReducedSI is the integer value for id-BandwidthReducedSI.
const IdBandwidthReducedSI int64 = 180

// IdBearerType is the integer value for id-BearerType.
const IdBearerType int64 = 171

// IdBluetoothMeasurementConfiguration is the integer value for id-BluetoothMeasurementConfiguration.
const IdBluetoothMeasurementConfiguration int64 = 303

// IdCHODCEarlyDataForwarding is the integer value for id-CHO-DC-EarlyDataForwarding.
const IdCHODCEarlyDataForwarding int64 = 407

// IdCHODCIndicator is the integer value for id-CHO-DC-Indicator.
const IdCHODCIndicator int64 = 368

// IdCHOinformationACK is the integer value for id-CHOinformation-ACK.
const IdCHOinformationACK int64 = 362

// IdCHOinformationAddReq is the integer value for id-CHOinformation-AddReq.
const IdCHOinformationAddReq int64 = 420

// IdCHOinformationModReq is the integer value for id-CHOinformation-ModReq.
const IdCHOinformationModReq int64 = 421

// IdCHOinformationREQ is the integer value for id-CHOinformation-REQ.
const IdCHOinformationREQ int64 = 361

// IdCNTypeRestrictions is the integer value for id-CNTypeRestrictions.
const IdCNTypeRestrictions int64 = 301

// IdCPACinformationREQD is the integer value for id-CPACinformation-REQD.
const IdCPACinformationREQD int64 = 428

// IdCPAinformationMOD is the integer value for id-CPAinformation-MOD.
const IdCPAinformationMOD int64 = 426

// IdCPAinformationMODACK is the integer value for id-CPAinformation-MOD-ACK.
const IdCPAinformationMODACK int64 = 427

// IdCPAinformationREQ is the integer value for id-CPAinformation-REQ.
const IdCPAinformationREQ int64 = 424

// IdCPAinformationREQACK is the integer value for id-CPAinformation-REQ-ACK.
const IdCPAinformationREQACK int64 = 425

// IdCPCCancel is the integer value for id-CPC-cancel.
const IdCPCCancel int64 = 59

// IdCPCinformationCONF is the integer value for id-CPCinformation-CONF.
const IdCPCinformationCONF int64 = 430

// IdCPCinformationNOTIFY is the integer value for id-CPCinformation-NOTIFY.
const IdCPCinformationNOTIFY int64 = 431

// IdCPCinformationREQD is the integer value for id-CPCinformation-REQD.
const IdCPCinformationREQD int64 = 429

// IdCPCupdateMOD is the integer value for id-CPCupdate-MOD.
const IdCPCupdateMOD int64 = 432

// IdCSGMembershipStatus is the integer value for id-CSGMembershipStatus.
const IdCSGMembershipStatus int64 = 71

// IdCSGId is the integer value for id-CSG-Id.
const IdCSGId int64 = 70

// IdCSIReportList is the integer value for id-CSIReportList.
const IdCSIReportList int64 = 146

// IdCSIRSTransmissionIndication is the integer value for id-CSI-RSTransmissionIndication.
const IdCSIRSTransmissionIndication int64 = 380

// IdCandidateCellsToBeCancelledList is the integer value for id-CandidateCellsToBeCancelledList.
const IdCandidateCellsToBeCancelledList int64 = 365

// IdCarrierList is the integer value for id-CarrierList.
const IdCarrierList int64 = 386

// IdCause is the integer value for id-Cause.
const IdCause int64 = 5

// IdCellAssistanceInformation is the integer value for id-CellAssistanceInformation.
const IdCellAssistanceInformation int64 = 251

// IdCellInformation is the integer value for id-CellInformation.
const IdCellInformation int64 = 6

// IdCellInformationItem is the integer value for id-CellInformation-Item.
const IdCellInformationItem int64 = 7

// IdCellMeasurementResult is the integer value for id-CellMeasurementResult.
const IdCellMeasurementResult int64 = 32

// IdCellMeasurementResultEUTRAENDC is the integer value for id-CellMeasurementResult-E-UTRA-ENDC.
const IdCellMeasurementResultEUTRAENDC int64 = 401

// IdCellMeasurementResultEUTRAENDCItem is the integer value for id-CellMeasurementResult-E-UTRA-ENDC-Item.
const IdCellMeasurementResultEUTRAENDCItem int64 = 402

// IdCellMeasurementResultItem is the integer value for id-CellMeasurementResult-Item.
const IdCellMeasurementResultItem int64 = 33

// IdCellMeasurementResultNRENDC is the integer value for id-CellMeasurementResult-NR-ENDC.
const IdCellMeasurementResultNRENDC int64 = 393

// IdCellMeasurementResultNRENDCItem is the integer value for id-CellMeasurementResult-NR-ENDC-Item.
const IdCellMeasurementResultNRENDCItem int64 = 394

// IdCellReportingIndicator is the integer value for id-CellReportingIndicator.
const IdCellReportingIndicator int64 = 170

// IdCellToReport is the integer value for id-CellToReport.
const IdCellToReport int64 = 29

// IdCellToReportEUTRAENDC is the integer value for id-CellToReport-E-UTRA-ENDC.
const IdCellToReportEUTRAENDC int64 = 403

// IdCellToReportEUTRAENDCItem is the integer value for id-CellToReport-E-UTRA-ENDC-Item.
const IdCellToReportEUTRAENDCItem int64 = 404

// IdCellToReportItem is the integer value for id-CellToReport-Item.
const IdCellToReportItem int64 = 31

// IdCellToReportNRENDC is the integer value for id-CellToReport-NR-ENDC.
const IdCellToReportNRENDC int64 = 391

// IdCellToReportNRENDCItem is the integer value for id-CellToReport-NR-ENDC-Item.
const IdCellToReportNRENDCItem int64 = 392

// IdCellandCapacityAssistInfo is the integer value for id-CellandCapacityAssistInfo.
const IdCellandCapacityAssistInfo int64 = 351

// IdCoMPInformation is the integer value for id-CoMPInformation.
const IdCoMPInformation int64 = 108

// IdCompleteFailureCauseInformationItem is the integer value for id-CompleteFailureCauseInformation-Item.
const IdCompleteFailureCauseInformationItem int64 = 69

// IdCompleteFailureCauseInformationList is the integer value for id-CompleteFailureCauseInformation-List.
const IdCompleteFailureCauseInformationList int64 = 68

// IdCompositeAvailableCapacityGroup is the integer value for id-CompositeAvailableCapacityGroup.
const IdCompositeAvailableCapacityGroup int64 = 42

// IdCorrelationID is the integer value for id-Correlation-ID.
const IdCorrelationID int64 = 166

// IdCoverageModificationList is the integer value for id-CoverageModificationList.
const IdCoverageModificationList int64 = 143

// IdCriticalityDiagnostics is the integer value for id-CriticalityDiagnostics.
const IdCriticalityDiagnostics int64 = 17

// IdDAPSRequestInfo is the integer value for id-DAPSRequestInfo.
const IdDAPSRequestInfo int64 = 363

// IdDAPSResponseInfo is the integer value for id-DAPSResponseInfo.
const IdDAPSResponseInfo int64 = 366

// IdDLCOUNTValueExtended is the integer value for id-DLCOUNTValueExtended.
const IdDLCOUNTValueExtended int64 = 93

// IdDLCOUNTValuePDCPSNlength18 is the integer value for id-DLCOUNTValuePDCP-SNlength18.
const IdDLCOUNTValuePDCPSNlength18 int64 = 152

// IdDLCarrierList is the integer value for id-DLCarrierList.
const IdDLCarrierList int64 = 381

// IdDLEARFCNExtension is the integer value for id-DL-EARFCNExtension.
const IdDLEARFCNExtension int64 = 96

// IdDLSchedulingPDCCHCCEUsage is the integer value for id-DL-scheduling-PDCCH-CCE-usage.
const IdDLSchedulingPDCCHCCEUsage int64 = 193

// IdDataTrafficResourceIndication is the integer value for id-DataTrafficResourceIndication.
const IdDataTrafficResourceIndication int64 = 287

// IdDeactivationIndication is the integer value for id-DeactivationIndication.
const IdDeactivationIndication int64 = 59

// IdDesiredActNotificationLevel is the integer value for id-DesiredActNotificationLevel.
const IdDesiredActNotificationLevel int64 = 329

// IdDirectForwardingPathAvailability is the integer value for id-DirectForwardingPathAvailability.
const IdDirectForwardingPathAvailability int64 = 410

// IdDownlinkPacketLossRate is the integer value for id-DownlinkPacketLossRate.
const IdDownlinkPacketLossRate int64 = 273

// IdDynamicDLTransmissionInformation is the integer value for id-DynamicDLTransmissionInformation.
const IdDynamicDLTransmissionInformation int64 = 106

// IdECGI is the integer value for id-ECGI.
const IdECGI int64 = 316

// IdENB1CellID is the integer value for id-ENB1-Cell-ID.
const IdENB1CellID int64 = 43

// IdENB1MeasurementID is the integer value for id-ENB1-Measurement-ID.
const IdENB1MeasurementID int64 = 39

// IdENB1MobilityParameters is the integer value for id-ENB1-Mobility-Parameters.
const IdENB1MobilityParameters int64 = 46

// IdENB2CellID is the integer value for id-ENB2-Cell-ID.
const IdENB2CellID int64 = 44

// IdENB2MeasurementID is the integer value for id-ENB2-Measurement-ID.
const IdENB2MeasurementID int64 = 40

// IdENB2MobilityParametersModificationRange is the integer value for id-ENB2-Mobility-Parameters-Modification-Range.
const IdENB2MobilityParametersModificationRange int64 = 47

// IdENB2ProposedMobilityParameters is the integer value for id-ENB2-Proposed-Mobility-Parameters.
const IdENB2ProposedMobilityParameters int64 = 45

// IdEPCHandoverRestrictionListContainer is the integer value for id-EPCHandoverRestrictionListContainer.
const IdEPCHandoverRestrictionListContainer int64 = 360

// IdERABActivityNotifyItemList is the integer value for id-ERABActivityNotifyItemList.
const IdERABActivityNotifyItemList int64 = 297

// IdERABsTransferredToMeNB is the integer value for id-ERABs-transferred-to-MeNB.
const IdERABsTransferredToMeNB int64 = 339

// IdEUTRANTraceID is the integer value for id-EUTRANTraceID.
const IdEUTRANTraceID int64 = 333

// IdERABUsageReportItem is the integer value for id-E-RABUsageReport-Item.
const IdERABUsageReportItem int64 = 263

// IdERABItem is the integer value for id-E-RAB-Item.
const IdERABItem int64 = 2

// IdERABsAdmittedToBeModifiedSgNBModConfList is the integer value for id-E-RABs-AdmittedToBeModified-SgNBModConfList.
const IdERABsAdmittedToBeModifiedSgNBModConfList int64 = 294

// IdERABsAdmittedToBeModifiedSgNBModConfItem is the integer value for id-E-RABs-AdmittedToBeModified-SgNBModConf-Item.
const IdERABsAdmittedToBeModifiedSgNBModConfItem int64 = 295

// IdERABsAdmittedItem is the integer value for id-E-RABs-Admitted-Item.
const IdERABsAdmittedItem int64 = 0

// IdERABsAdmittedList is the integer value for id-E-RABs-Admitted-List.
const IdERABsAdmittedList int64 = 1

// IdERABsAdmittedToBeAddedItem is the integer value for id-E-RABs-Admitted-ToBeAdded-Item.
const IdERABsAdmittedToBeAddedItem int64 = 121

// IdERABsAdmittedToBeAddedList is the integer value for id-E-RABs-Admitted-ToBeAdded-List.
const IdERABsAdmittedToBeAddedList int64 = 120

// IdERABsAdmittedToBeAddedModAckItem is the integer value for id-E-RABs-Admitted-ToBeAdded-ModAckItem.
const IdERABsAdmittedToBeAddedModAckItem int64 = 131

// IdERABsAdmittedToBeAddedModAckList is the integer value for id-E-RABs-Admitted-ToBeAdded-ModAckList.
const IdERABsAdmittedToBeAddedModAckList int64 = 128

// IdERABsAdmittedToBeAddedSgNBAddReqAckList is the integer value for id-E-RABs-Admitted-ToBeAdded-SgNBAddReqAckList.
const IdERABsAdmittedToBeAddedSgNBAddReqAckList int64 = 210

// IdERABsAdmittedToBeAddedSgNBAddReqAckItem is the integer value for id-E-RABs-Admitted-ToBeAdded-SgNBAddReqAck-Item.
const IdERABsAdmittedToBeAddedSgNBAddReqAckItem int64 = 213

// IdERABsAdmittedToBeAddedSgNBModAckList is the integer value for id-E-RABs-Admitted-ToBeAdded-SgNBModAckList.
const IdERABsAdmittedToBeAddedSgNBModAckList int64 = 219

// IdERABsAdmittedToBeAddedSgNBModAckItem is the integer value for id-E-RABs-Admitted-ToBeAdded-SgNBModAck-Item.
const IdERABsAdmittedToBeAddedSgNBModAckItem int64 = 222

// IdERABsAdmittedToBeModifiedModAckItem is the integer value for id-E-RABs-Admitted-ToBeModified-ModAckItem.
const IdERABsAdmittedToBeModifiedModAckItem int64 = 132

// IdERABsAdmittedToBeModifiedModAckList is the integer value for id-E-RABs-Admitted-ToBeModified-ModAckList.
const IdERABsAdmittedToBeModifiedModAckList int64 = 129

// IdERABsAdmittedToBeModifiedSgNBModAckList is the integer value for id-E-RABs-Admitted-ToBeModified-SgNBModAckList.
const IdERABsAdmittedToBeModifiedSgNBModAckList int64 = 220

// IdERABsAdmittedToBeModifiedSgNBModAckItem is the integer value for id-E-RABs-Admitted-ToBeModified-SgNBModAck-Item.
const IdERABsAdmittedToBeModifiedSgNBModAckItem int64 = 223

// IdERABsAdmittedToBeReleasedModAckItem is the integer value for id-E-RABs-Admitted-ToBeReleased-ModAckItem.
const IdERABsAdmittedToBeReleasedModAckItem int64 = 133

// IdERABsAdmittedToBeReleasedModAckList is the integer value for id-E-RABs-Admitted-ToBeReleased-ModAckList.
const IdERABsAdmittedToBeReleasedModAckList int64 = 130

// IdERABsAdmittedToBeReleasedSgNBModAckList is the integer value for id-E-RABs-Admitted-ToBeReleased-SgNBModAckList.
const IdERABsAdmittedToBeReleasedSgNBModAckList int64 = 221

// IdERABsAdmittedToBeReleasedSgNBModAckItem is the integer value for id-E-RABs-Admitted-ToBeReleased-SgNBModAck-Item.
const IdERABsAdmittedToBeReleasedSgNBModAckItem int64 = 224

// IdERABsAdmittedToBeReleasedSgNBRelReqAckList is the integer value for id-E-RABs-Admitted-ToBeReleased-SgNBRelReqAckList.
const IdERABsAdmittedToBeReleasedSgNBRelReqAckList int64 = 318

// IdERABsAdmittedToBeReleasedSgNBRelReqAckItem is the integer value for id-E-RABs-Admitted-ToBeReleased-SgNBRelReqAck-Item.
const IdERABsAdmittedToBeReleasedSgNBRelReqAckItem int64 = 319

// IdERABsDataForwardingAddressItem is the integer value for id-E-RABs-DataForwardingAddress-Item.
const IdERABsDataForwardingAddressItem int64 = 308

// IdERABsDataForwardingAddressList is the integer value for id-E-RABs-DataForwardingAddress-List.
const IdERABsDataForwardingAddressList int64 = 307

// IdERABsNotAdmittedList is the integer value for id-E-RABs-NotAdmitted-List.
const IdERABsNotAdmittedList int64 = 3

// IdERABsSubjectToCounterCheckItem is the integer value for id-E-RABs-SubjectToCounterCheckItem.
const IdERABsSubjectToCounterCheckItem int64 = 142

// IdERABsSubjectToCounterCheckList is the integer value for id-E-RABs-SubjectToCounterCheck-List.
const IdERABsSubjectToCounterCheckList int64 = 141

// IdERABsSubjectToSgNBCounterCheckItem is the integer value for id-E-RABs-SubjectToSgNBCounterCheck-Item.
const IdERABsSubjectToSgNBCounterCheckItem int64 = 236

// IdERABsSubjectToSgNBCounterCheckList is the integer value for id-E-RABs-SubjectToSgNBCounterCheck-List.
const IdERABsSubjectToSgNBCounterCheckList int64 = 235

// IdERABsSubjectToStatusTransferItem is the integer value for id-E-RABs-SubjectToStatusTransfer-Item.
const IdERABsSubjectToStatusTransferItem int64 = 19

// IdERABsSubjectToStatusTransferList is the integer value for id-E-RABs-SubjectToStatusTransfer-List.
const IdERABsSubjectToStatusTransferList int64 = 18

// IdERABsToBeAddedItem is the integer value for id-E-RABs-ToBeAdded-Item.
const IdERABsToBeAddedItem int64 = 118

// IdERABsToBeAddedList is the integer value for id-E-RABs-ToBeAdded-List.
const IdERABsToBeAddedList int64 = 117

// IdERABsToBeAddedModReqItem is the integer value for id-E-RABs-ToBeAdded-ModReqItem.
const IdERABsToBeAddedModReqItem int64 = 125

// IdERABsToBeAddedSgNBAddReqList is the integer value for id-E-RABs-ToBeAdded-SgNBAddReqList.
const IdERABsToBeAddedSgNBAddReqList int64 = 205

// IdERABsToBeAddedSgNBAddReqItem is the integer value for id-E-RABs-ToBeAdded-SgNBAddReq-Item.
const IdERABsToBeAddedSgNBAddReqItem int64 = 209

// IdERABsToBeAddedSgNBModReqItem is the integer value for id-E-RABs-ToBeAdded-SgNBModReq-Item.
const IdERABsToBeAddedSgNBModReqItem int64 = 216

// IdERABsToBeModifiedModReqItem is the integer value for id-E-RABs-ToBeModified-ModReqItem.
const IdERABsToBeModifiedModReqItem int64 = 126

// IdERABsToBeModifiedSgNBModReqItem is the integer value for id-E-RABs-ToBeModified-SgNBModReq-Item.
const IdERABsToBeModifiedSgNBModReqItem int64 = 217

// IdERABsToBeModifiedSgNBModReqdList is the integer value for id-E-RABs-ToBeModified-SgNBModReqdList.
const IdERABsToBeModifiedSgNBModReqdList int64 = 226

// IdERABsToBeModifiedSgNBModReqdItem is the integer value for id-E-RABs-ToBeModified-SgNBModReqd-Item.
const IdERABsToBeModifiedSgNBModReqdItem int64 = 228

// IdERABsToBeReleasedListRelConf is the integer value for id-E-RABs-ToBeReleased-List-RelConf.
const IdERABsToBeReleasedListRelConf int64 = 139

// IdERABsToBeReleasedListRelReq is the integer value for id-E-RABs-ToBeReleased-List-RelReq.
const IdERABsToBeReleasedListRelReq int64 = 137

// IdERABsToBeReleasedModReqItem is the integer value for id-E-RABs-ToBeReleased-ModReqItem.
const IdERABsToBeReleasedModReqItem int64 = 127

// IdERABsToBeReleasedModReqd is the integer value for id-E-RABs-ToBeReleased-ModReqd.
const IdERABsToBeReleasedModReqd int64 = 134

// IdERABsToBeReleasedModReqdItem is the integer value for id-E-RABs-ToBeReleased-ModReqdItem.
const IdERABsToBeReleasedModReqdItem int64 = 135

// IdERABsToBeReleasedRelConfItem is the integer value for id-E-RABs-ToBeReleased-RelConfItem.
const IdERABsToBeReleasedRelConfItem int64 = 140

// IdERABsToBeReleasedRelReqItem is the integer value for id-E-RABs-ToBeReleased-RelReqItem.
const IdERABsToBeReleasedRelReqItem int64 = 138

// IdERABsToBeReleasedSgNBChaConfList is the integer value for id-E-RABs-ToBeReleased-SgNBChaConfList.
const IdERABsToBeReleasedSgNBChaConfList int64 = 229

// IdERABsToBeReleasedSgNBChaConfItem is the integer value for id-E-RABs-ToBeReleased-SgNBChaConf-Item.
const IdERABsToBeReleasedSgNBChaConfItem int64 = 230

// IdERABsToBeReleasedSgNBModReqItem is the integer value for id-E-RABs-ToBeReleased-SgNBModReq-Item.
const IdERABsToBeReleasedSgNBModReqItem int64 = 218

// IdERABsToBeReleasedSgNBModReqdList is the integer value for id-E-RABs-ToBeReleased-SgNBModReqdList.
const IdERABsToBeReleasedSgNBModReqdList int64 = 225

// IdERABsToBeReleasedSgNBModReqdItem is the integer value for id-E-RABs-ToBeReleased-SgNBModReqd-Item.
const IdERABsToBeReleasedSgNBModReqdItem int64 = 227

// IdERABsToBeReleasedSgNBRelConfList is the integer value for id-E-RABs-ToBeReleased-SgNBRelConfList.
const IdERABsToBeReleasedSgNBRelConfList int64 = 233

// IdERABsToBeReleasedSgNBRelConfItem is the integer value for id-E-RABs-ToBeReleased-SgNBRelConf-Item.
const IdERABsToBeReleasedSgNBRelConfItem int64 = 234

// IdERABsToBeReleasedSgNBRelReqList is the integer value for id-E-RABs-ToBeReleased-SgNBRelReqList.
const IdERABsToBeReleasedSgNBRelReqList int64 = 231

// IdERABsToBeReleasedSgNBRelReqItem is the integer value for id-E-RABs-ToBeReleased-SgNBRelReq-Item.
const IdERABsToBeReleasedSgNBRelReqItem int64 = 232

// IdERABsToBeReleasedSgNBRelReqdList is the integer value for id-E-RABs-ToBeReleased-SgNBRelReqdList.
const IdERABsToBeReleasedSgNBRelReqdList int64 = 320

// IdERABsToBeReleasedSgNBRelReqdItem is the integer value for id-E-RABs-ToBeReleased-SgNBRelReqd-Item.
const IdERABsToBeReleasedSgNBRelReqdItem int64 = 321

// IdERABsToBeSetupRetrieveItem is the integer value for id-E-RABs-ToBeSetupRetrieve-Item.
const IdERABsToBeSetupRetrieveItem int64 = 174

// IdERABsToBeSetupItem is the integer value for id-E-RABs-ToBeSetup-Item.
const IdERABsToBeSetupItem int64 = 4

// IdEUTRANNode1MeasurementID is the integer value for id-E-UTRAN-Node1-Measurement-ID.
const IdEUTRANNode1MeasurementID int64 = 383

// IdEUTRANNode2MeasurementID is the integer value for id-E-UTRAN-Node2-Measurement-ID.
const IdEUTRANNode2MeasurementID int64 = 384

// IdEthernetType is the integer value for id-Ethernet-Type.
const IdEthernetType int64 = 369

// IdExpectedUEBehaviour is the integer value for id-ExpectedUEBehaviour.
const IdExpectedUEBehaviour int64 = 104

// IdExtendedULInterferenceOverloadInfo is the integer value for id-ExtendedULInterferenceOverloadInfo.
const IdExtendedULInterferenceOverloadInfo int64 = 100

// IdF1CTrafficContainer is the integer value for id-F1CTrafficContainer.
const IdF1CTrafficContainer int64 = 397

// IdFailureCellCRNTI is the integer value for id-FailureCellCRNTI.
const IdFailureCellCRNTI int64 = 50

// IdFailureCellECGI is the integer value for id-FailureCellECGI.
const IdFailureCellECGI int64 = 53

// IdFailureCellPCI is the integer value for id-FailureCellPCI.
const IdFailureCellPCI int64 = 48

// IdFastMCGRecoveryMNToSN is the integer value for id-FastMCGRecovery-MN-to-SN.
const IdFastMCGRecoveryMNToSN int64 = 347

// IdFastMCGRecoverySNToMN is the integer value for id-FastMCGRecovery-SN-to-MN.
const IdFastMCGRecoverySNToMN int64 = 342

// IdFreqBandIndicatorPriority is the integer value for id-FreqBandIndicatorPriority.
const IdFreqBandIndicatorPriority int64 = 160

// IdFrequencyShift7p5khz is the integer value for id-FrequencyShift7p5khz.
const IdFrequencyShift7p5khz int64 = 388

// IdGNBOverloadInformation is the integer value for id-GNBOverloadInformation.
const IdGNBOverloadInformation int64 = 310

// IdGUGroupIDList is the integer value for id-GUGroupIDList.
const IdGUGroupIDList int64 = 24

// IdGUGroupIDToAddList is the integer value for id-GUGroupIDToAddList.
const IdGUGroupIDToAddList int64 = 34

// IdGUGroupIDToDeleteList is the integer value for id-GUGroupIDToDeleteList.
const IdGUGroupIDToDeleteList int64 = 35

// IdGUMMEIID is the integer value for id-GUMMEI-ID.
const IdGUMMEIID int64 = 23

// IdGWTransportLayerAddress is the integer value for id-GW-TransportLayerAddress.
const IdGWTransportLayerAddress int64 = 165

// IdGlobalENBID is the integer value for id-GlobalENB-ID.
const IdGlobalENBID int64 = 21

// IdGlobalenGNBID is the integer value for id-Globalen-gNB-ID.
const IdGlobalenGNBID int64 = 252

// IdHOCause is the integer value for id-HO-cause.
const IdHOCause int64 = 80

// IdHandoverReportType is the integer value for id-HandoverReportType.
const IdHandoverReportType int64 = 54

// IdHandoverRestrictionList is the integer value for id-HandoverRestrictionList.
const IdHandoverRestrictionList int64 = 240

// IdIABNodeIndication is the integer value for id-IABNodeIndication.
const IdIABNodeIndication int64 = 395

// IdIMSvoiceEPSfallbackfrom5G is the integer value for id-IMSvoiceEPSfallbackfrom5G.
const IdIMSvoiceEPSfallbackfrom5G int64 = 408

// IdInitiatingNodeTypeEndcConfigUpdate is the integer value for id-InitiatingNodeType-EndcConfigUpdate.
const IdInitiatingNodeTypeEndcConfigUpdate int64 = 245

// IdInitiatingNodeTypeEndcX2Removal is the integer value for id-InitiatingNodeType-EndcX2Removal.
const IdInitiatingNodeTypeEndcX2Removal int64 = 298

// IdInitiatingNodeTypeEndcX2Setup is the integer value for id-InitiatingNodeType-EndcX2Setup.
const IdInitiatingNodeTypeEndcX2Setup int64 = 244

// IdInitiatingNodeTypeEutranrCellResourceCoordination is the integer value for id-InitiatingNodeType-EutranrCellResourceCoordination.
const IdInitiatingNodeTypeEutranrCellResourceCoordination int64 = 285

// IdIntendedTDDDLULConfigurationNR is the integer value for id-IntendedTDD-DL-ULConfiguration-NR.
const IdIntendedTDDDLULConfigurationNR int64 = 399

// IdIntendedULDLConfiguration is the integer value for id-IntendedULDLConfiguration.
const IdIntendedULDLConfiguration int64 = 99

// IdInterfaceInstanceIndication is the integer value for id-InterfaceInstanceIndication.
const IdInterfaceInstanceIndication int64 = 335

// IdInvokeIndication is the integer value for id-InvokeIndication.
const IdInvokeIndication int64 = 62

// IdLHNID is the integer value for id-LHN-ID.
const IdLHNID int64 = 159

// IdLastNGRANPLMNIdentity is the integer value for id-LastNG-RANPLMNIdentity.
const IdLastNGRANPLMNIdentity int64 = 332

// IdListofEUTRACellsinEUTRACoordinationReq is the integer value for id-ListofEUTRACellsinEUTRACoordinationReq.
const IdListofEUTRACellsinEUTRACoordinationReq int64 = 289

// IdListofEUTRACellsinEUTRACoordinationResp is the integer value for id-ListofEUTRACellsinEUTRACoordinationResp.
const IdListofEUTRACellsinEUTRACoordinationResp int64 = 290

// IdListofEUTRACellsinNRCoordinationReq is the integer value for id-ListofEUTRACellsinNRCoordinationReq.
const IdListofEUTRACellsinNRCoordinationReq int64 = 291

// IdListofNRCellsinNRCoordinationReq is the integer value for id-ListofNRCellsinNRCoordinationReq.
const IdListofNRCellsinNRCoordinationReq int64 = 292

// IdListofNRCellsinNRCoordinationResp is the integer value for id-ListofNRCellsinNRCoordinationResp.
const IdListofNRCellsinNRCoordinationResp int64 = 293

// IdLocationInformationSgNB is the integer value for id-LocationInformationSgNB.
const IdLocationInformationSgNB int64 = 331

// IdLocationInformationSgNBReporting is the integer value for id-LocationInformationSgNBReporting.
const IdLocationInformationSgNBReporting int64 = 330

// IdLowerLayerPresenceStatusChange is the integer value for id-LowerLayerPresenceStatusChange.
const IdLowerLayerPresenceStatusChange int64 = 341

// IdM3Configuration is the integer value for id-M3Configuration.
const IdM3Configuration int64 = 85

// IdM4Configuration is the integer value for id-M4Configuration.
const IdM4Configuration int64 = 86

// IdM5Configuration is the integer value for id-M5Configuration.
const IdM5Configuration int64 = 87

// IdM6Configuration is the integer value for id-M6Configuration.
const IdM6Configuration int64 = 161

// IdM7Configuration is the integer value for id-M7Configuration.
const IdM7Configuration int64 = 162

// IdMBMSServiceAreaList is the integer value for id-MBMS-Service-Area-List.
const IdMBMSServiceAreaList int64 = 79

// IdMBSFNSubframeInfo is the integer value for id-MBSFN-Subframe-Info.
const IdMBSFNSubframeInfo int64 = 56

// IdMDTConfiguration is the integer value for id-MDTConfiguration.
const IdMDTConfiguration int64 = 72

// IdMDTConfigurationNR is the integer value for id-MDTConfigurationNR.
const IdMDTConfigurationNR int64 = 375

// IdMDTLocationInfo is the integer value for id-MDT-Location-Info.
const IdMDTLocationInfo int64 = 88

// IdMIMOPRBusageInformation is the integer value for id-MIMOPRBusageInformation.
const IdMIMOPRBusageInformation int64 = 439

// IdMakeBeforeBreakIndicator is the integer value for id-MakeBeforeBreakIndicator.
const IdMakeBeforeBreakIndicator int64 = 181

// IdManagementBasedMDTPLMNList is the integer value for id-ManagementBasedMDTPLMNList.
const IdManagementBasedMDTPLMNList int64 = 89

// IdManagementBasedMDTallowed is the integer value for id-ManagementBasedMDTallowed.
const IdManagementBasedMDTallowed int64 = 74

// IdMaskedIMEISV is the integer value for id-Masked-IMEISV.
const IdMaskedIMEISV int64 = 98

// IdMaximumCellListSize is the integer value for id-MaximumCellListSize.
const IdMaximumCellListSize int64 = 349

// IdMeNBCellID is the integer value for id-MeNBCell-ID.
const IdMeNBCellID int64 = 279

// IdMeNBCoordinationAssistanceInformation is the integer value for id-MeNBCoordinationAssistanceInformation.
const IdMeNBCoordinationAssistanceInformation int64 = 323

// IdMeNBResourceCoordinationInformation is the integer value for id-MeNBResourceCoordinationInformation.
const IdMeNBResourceCoordinationInformation int64 = 257

// IdMeNBUEX2APID is the integer value for id-MeNB-UE-X2AP-ID.
const IdMeNBUEX2APID int64 = 111

// IdMeNBUEX2APIDExtension is the integer value for id-MeNB-UE-X2AP-ID-Extension.
const IdMeNBUEX2APIDExtension int64 = 157

// IdMeNBtoSeNBContainer is the integer value for id-MeNBtoSeNBContainer.
const IdMeNBtoSeNBContainer int64 = 119

// IdMeNBtoSgNBContainer is the integer value for id-MeNBtoSgNBContainer.
const IdMeNBtoSgNBContainer int64 = 206

// IdMeasurementFailureCauseItem is the integer value for id-MeasurementFailureCause-Item.
const IdMeasurementFailureCauseItem int64 = 67

// IdMeasurementInitiationResultItem is the integer value for id-MeasurementInitiationResult-Item.
const IdMeasurementInitiationResultItem int64 = 66

// IdMeasurementInitiationResultList is the integer value for id-MeasurementInitiationResult-List.
const IdMeasurementInitiationResultList int64 = 65

// IdMeasurementResultforNRCellsPossiblyAggregated is the integer value for id-MeasurementResultforNRCellsPossiblyAggregated.
const IdMeasurementResultforNRCellsPossiblyAggregated int64 = 417

// IdMeasurementID is the integer value for id-Measurement-ID.
const IdMeasurementID int64 = 37

// IdMessageOversizeNotification is the integer value for id-MessageOversizeNotification.
const IdMessageOversizeNotification int64 = 350

// IdMobilityInformation is the integer value for id-MobilityInformation.
const IdMobilityInformation int64 = 82

// IdMultibandInfoList is the integer value for id-MultibandInfoList.
const IdMultibandInfoList int64 = 84

// IdNBIoTRLFReportContainer is the integer value for id-NBIoT-RLF-Report-Container.
const IdNBIoTRLFReportContainer int64 = 374

// IdNBIoTULDLAlignmentOffset is the integer value for id-NBIoT-UL-DL-AlignmentOffset.
const IdNBIoTULDLAlignmentOffset int64 = 338

// IdNPRACHConfiguration is the integer value for id-NPRACHConfiguration.
const IdNPRACHConfiguration int64 = 373

// IdNRCGI is the integer value for id-NRCGI.
const IdNRCGI int64 = 322

// IdNRCellPRACHConfig is the integer value for id-NRCellPRACHConfig.
const IdNRCellPRACHConfig int64 = 390

// IdNRNeighbourInfoToAdd is the integer value for id-NRNeighbourInfoToAdd.
const IdNRNeighbourInfoToAdd int64 = 327

// IdNRNeighbourInfoToModify is the integer value for id-NRNeighbourInfoToModify.
const IdNRNeighbourInfoToModify int64 = 328

// IdNRRACHReportInformation is the integer value for id-NRRACHReportInformation.
const IdNRRACHReportInformation int64 = 414

// IdNRSNSSSPowerOffset is the integer value for id-NRS-NSSS-PowerOffset.
const IdNRSNSSSPowerOffset int64 = 282

// IdNRUESecurityCapabilities is the integer value for id-NRUESecurityCapabilities.
const IdNRUESecurityCapabilities int64 = 248

// IdNRUESidelinkAggregateMaximumBitRate is the integer value for id-NRUESidelinkAggregateMaximumBitRate.
const IdNRUESidelinkAggregateMaximumBitRate int64 = 371

// IdNRUeReport is the integer value for id-NRUeReport.
const IdNRUeReport int64 = 243

// IdNRV2XServicesAuthorized is the integer value for id-NRV2XServicesAuthorized.
const IdNRV2XServicesAuthorized int64 = 370

// IdNRrestrictionin5GS is the integer value for id-NRrestrictionin5GS.
const IdNRrestrictionin5GS int64 = 305

// IdNRrestrictioninEPSasSecondaryRAT is the integer value for id-NRrestrictioninEPSasSecondaryRAT.
const IdNRrestrictioninEPSasSecondaryRAT int64 = 202

// IdNSSSNumOccasionDifferentPrecoder is the integer value for id-NSSS-NumOccasionDifferentPrecoder.
const IdNSSSNumOccasionDifferentPrecoder int64 = 283

// IdNeighbourTAC is the integer value for id-NeighbourTAC.
const IdNeighbourTAC int64 = 76

// IdNewEUTRANCellIdentifier is the integer value for id-NewEUTRANCellIdentifier.
const IdNewEUTRANCellIdentifier int64 = 175

// IdNewENBUEX2APID is the integer value for id-New-eNB-UE-X2AP-ID.
const IdNewENBUEX2APID int64 = 9

// IdNewENBUEX2APIDExtension is the integer value for id-New-eNB-UE-X2AP-ID-Extension.
const IdNewENBUEX2APIDExtension int64 = 155

// IdNumberOfAntennaports is the integer value for id-Number-of-Antennaports.
const IdNumberOfAntennaports int64 = 41

// IdOffsetOfNbiotChannelNumberToDLEARFCN is the integer value for id-OffsetOfNbiotChannelNumberToDL-EARFCN.
const IdOffsetOfNbiotChannelNumberToDLEARFCN int64 = 177

// IdOffsetOfNbiotChannelNumberToULEARFCN is the integer value for id-OffsetOfNbiotChannelNumberToUL-EARFCN.
const IdOffsetOfNbiotChannelNumberToULEARFCN int64 = 178

// IdOldSgNBUEX2APID is the integer value for id-Old-SgNB-UE-X2AP-ID.
const IdOldSgNBUEX2APID int64 = 264

// IdOldENBUEX2APID is the integer value for id-Old-eNB-UE-X2AP-ID.
const IdOldENBUEX2APID int64 = 10

// IdOldENBUEX2APIDExtension is the integer value for id-Old-eNB-UE-X2AP-ID-Extension.
const IdOldENBUEX2APIDExtension int64 = 156

// IdPC5QoSParameters is the integer value for id-PC5QoSParameters.
const IdPC5QoSParameters int64 = 372

// IdPDCPChangeIndication is the integer value for id-PDCPChangeIndication.
const IdPDCPChangeIndication int64 = 249

// IdPRACHConfiguration is the integer value for id-PRACH-Configuration.
const IdPRACHConfiguration int64 = 55

// IdPSCellChangeHistory is the integer value for id-PSCellChangeHistory.
const IdPSCellChangeHistory int64 = 419

// IdPSCellHistoryInformationRetrieve is the integer value for id-PSCellHistoryInformationRetrieve.
const IdPSCellHistoryInformationRetrieve int64 = 416

// IdPSCellUEHistoryInformation is the integer value for id-PSCell-UE-HistoryInformation.
const IdPSCellUEHistoryInformation int64 = 418

// IdPartialListIndicator is the integer value for id-PartialListIndicator.
const IdPartialListIndicator int64 = 348

// IdPartialSuccessIndicator is the integer value for id-PartialSuccessIndicator.
const IdPartialSuccessIndicator int64 = 64

// IdPrivacyIndicator is the integer value for id-PrivacyIndicator.
const IdPrivacyIndicator int64 = 376

// IdProSeAuthorized is the integer value for id-ProSeAuthorized.
const IdProSeAuthorized int64 = 103

// IdProSeUEtoNetworkRelaying is the integer value for id-ProSeUEtoNetworkRelaying.
const IdProSeUEtoNetworkRelaying int64 = 149

// IdProcedureStage is the integer value for id-ProcedureStage.
const IdProcedureStage int64 = 367

// IdProtectedEUTRAResourceIndication is the integer value for id-ProtectedEUTRAResourceIndication.
const IdProtectedEUTRAResourceIndication int64 = 284

// IdQoSMappingInformation is the integer value for id-QoS-Mapping-Information.
const IdQoSMappingInformation int64 = 396

// IdRATRestrictions is the integer value for id-RAT-Restrictions.
const IdRATRestrictions int64 = 437

// IdRLCModeTransferred is the integer value for id-RLCMode-transferred.
const IdRLCModeTransferred int64 = 317

// IdRLCStatus is the integer value for id-RLC-Status.
const IdRLCStatus int64 = 300

// IdRNLHeader is the integer value for id-RNL-Header.
const IdRNLHeader int64 = 101

// IdRRCConfigIndication is the integer value for id-RRCConfigIndication.
const IdRRCConfigIndication int64 = 272

// IdRRCConnReestabIndicator is the integer value for id-RRCConnReestabIndicator.
const IdRRCConnReestabIndicator int64 = 78

// IdRRCConnSetupIndicator is the integer value for id-RRCConnSetupIndicator.
const IdRRCConnSetupIndicator int64 = 75

// IdRRCContainer is the integer value for id-RRCContainer.
const IdRRCContainer int64 = 237

// IdRSRPMRList is the integer value for id-RSRPMRList.
const IdRSRPMRList int64 = 110

// IdReEstablishmentCellECGI is the integer value for id-Re-establishmentCellECGI.
const IdReEstablishmentCellECGI int64 = 49

// IdReceiveStatusOfULPDCPSDUsExtended is the integer value for id-ReceiveStatusOfULPDCPSDUsExtended.
const IdReceiveStatusOfULPDCPSDUsExtended int64 = 91

// IdReceiveStatusOfULPDCPSDUsPDCPSNlength18 is the integer value for id-ReceiveStatusOfULPDCPSDUsPDCP-SNlength18.
const IdReceiveStatusOfULPDCPSDUsPDCPSNlength18 int64 = 150

// IdRegistrationRequest is the integer value for id-Registration-Request.
const IdRegistrationRequest int64 = 28

// IdReleaseFastMCGRecoveryViaSRB3 is the integer value for id-ReleaseFastMCGRecoveryViaSRB3.
const IdReleaseFastMCGRecoveryViaSRB3 int64 = 346

// IdReportCharacteristics is the integer value for id-ReportCharacteristics.
const IdReportCharacteristics int64 = 38

// IdReportingPeriodicity is the integer value for id-ReportingPeriodicity.
const IdReportingPeriodicity int64 = 30

// IdReportingPeriodicityCSIR is the integer value for id-ReportingPeriodicityCSIR.
const IdReportingPeriodicityCSIR int64 = 145

// IdReportingPeriodicityRSRPMR is the integer value for id-ReportingPeriodicityRSRPMR.
const IdReportingPeriodicityRSRPMR int64 = 109

// IdRequestedFastMCGRecoveryViaSRB3 is the integer value for id-RequestedFastMCGRecoveryViaSRB3.
const IdRequestedFastMCGRecoveryViaSRB3 int64 = 343

// IdRequestedFastMCGRecoveryViaSRB3Release is the integer value for id-RequestedFastMCGRecoveryViaSRB3Release.
const IdRequestedFastMCGRecoveryViaSRB3Release int64 = 345

// IdRequestedSplitSRBs is the integer value for id-RequestedSplitSRBs.
const IdRequestedSplitSRBs int64 = 208

// IdRequestedSplitSRBsrelease is the integer value for id-RequestedSplitSRBsrelease.
const IdRequestedSplitSRBsrelease int64 = 280

// IdRequestedTargetCellID is the integer value for id-RequestedTargetCellID.
const IdRequestedTargetCellID int64 = 364

// IdRespondingNodeTypeEndcConfigUpdate is the integer value for id-RespondingNodeType-EndcConfigUpdate.
const IdRespondingNodeTypeEndcConfigUpdate int64 = 247

// IdRespondingNodeTypeEndcX2Removal is the integer value for id-RespondingNodeType-EndcX2Removal.
const IdRespondingNodeTypeEndcX2Removal int64 = 299

// IdRespondingNodeTypeEndcX2Setup is the integer value for id-RespondingNodeType-EndcX2Setup.
const IdRespondingNodeTypeEndcX2Setup int64 = 246

// IdRespondingNodeTypeEutranrCellResourceCoordination is the integer value for id-RespondingNodeType-EutranrCellResourceCoordination.
const IdRespondingNodeTypeEutranrCellResourceCoordination int64 = 286

// IdResponseInformationSeNBReconfComp is the integer value for id-ResponseInformationSeNBReconfComp.
const IdResponseInformationSeNBReconfComp int64 = 123

// IdResponseInformationSgNBReconfComp is the integer value for id-ResponseInformationSgNBReconfComp.
const IdResponseInformationSgNBReconfComp int64 = 214

// IdSCGActivationRequest is the integer value for id-SCGActivationRequest.
const IdSCGActivationRequest int64 = 423

// IdSCGActivationStatus is the integer value for id-SCGActivationStatus.
const IdSCGActivationStatus int64 = 422

// IdSCGChangeIndication is the integer value for id-SCGChangeIndication.
const IdSCGChangeIndication int64 = 136

// IdSCGConfigurationQuery is the integer value for id-SCGConfigurationQuery.
const IdSCGConfigurationQuery int64 = 241

// IdSCGUEHistoryInformation is the integer value for id-SCG-UE-HistoryInformation.
const IdSCGUEHistoryInformation int64 = 415

// IdSCGreconfigNotification is the integer value for id-SCGreconfigNotification.
const IdSCGreconfigNotification int64 = 438

// IdSFNOffset is the integer value for id-SFN-Offset.
const IdSFNOffset int64 = 406

// IdSGNBAdditionTriggerInd is the integer value for id-SGNB-Addition-Trigger-Ind.
const IdSGNBAdditionTriggerInd int64 = 278

// IdSIPTOBearerDeactivationIndication is the integer value for id-SIPTO-BearerDeactivationIndication.
const IdSIPTOBearerDeactivationIndication int64 = 164

// IdSIPTOCorrelationID is the integer value for id-SIPTO-Correlation-ID.
const IdSIPTOCorrelationID int64 = 167

// IdSIPTOLGWTransportLayerAddress is the integer value for id-SIPTO-L-GW-TransportLayerAddress.
const IdSIPTOLGWTransportLayerAddress int64 = 168

// IdSNtriggered is the integer value for id-SNtriggered.
const IdSNtriggered int64 = 379

// IdSRBType is the integer value for id-SRBType.
const IdSRBType int64 = 238

// IdSRVCCOperationPossible is the integer value for id-SRVCCOperationPossible.
const IdSRVCCOperationPossible int64 = 36

// IdSSBPositionsInBurst is the integer value for id-SSB-PositionsInBurst.
const IdSSBPositionsInBurst int64 = 389

// IdSeNBSecurityKey is the integer value for id-SeNBSecurityKey.
const IdSeNBSecurityKey int64 = 114

// IdSeNBUEAggregateMaximumBitRate is the integer value for id-SeNBUEAggregateMaximumBitRate.
const IdSeNBUEAggregateMaximumBitRate int64 = 115

// IdSeNBUEX2APID is the integer value for id-SeNB-UE-X2AP-ID.
const IdSeNBUEX2APID int64 = 112

// IdSeNBUEX2APIDExtension is the integer value for id-SeNB-UE-X2AP-ID-Extension.
const IdSeNBUEX2APIDExtension int64 = 158

// IdSeNBtoMeNBContainer is the integer value for id-SeNBtoMeNBContainer.
const IdSeNBtoMeNBContainer int64 = 122

// IdSecondaryRATUsageReport is the integer value for id-SecondaryRATUsageReport.
const IdSecondaryRATUsageReport int64 = 255

// IdSecondaryRATUsageReportList is the integer value for id-SecondaryRATUsageReportList.
const IdSecondaryRATUsageReportList int64 = 265

// IdSecondaryRATUsageReportItem is the integer value for id-SecondaryRATUsageReport-Item.
const IdSecondaryRATUsageReportItem int64 = 266

// IdSecurityIndication is the integer value for id-SecurityIndication.
const IdSecurityIndication int64 = 435

// IdSecurityResult is the integer value for id-SecurityResult.
const IdSecurityResult int64 = 436

// IdSelectedPLMN is the integer value for id-SelectedPLMN.
const IdSelectedPLMN int64 = 269

// IdSensorMeasurementConfiguration is the integer value for id-SensorMeasurementConfiguration.
const IdSensorMeasurementConfiguration int64 = 440

// IdServedCellSpecificInfoReqNR is the integer value for id-ServedCellSpecificInfoReq-NR.
const IdServedCellSpecificInfoReqNR int64 = 434

// IdServedCells is the integer value for id-ServedCells.
const IdServedCells int64 = 20

// IdServedCellsToActivate is the integer value for id-ServedCellsToActivate.
const IdServedCellsToActivate int64 = 57

// IdServedCellsToAdd is the integer value for id-ServedCellsToAdd.
const IdServedCellsToAdd int64 = 25

// IdServedCellsToDelete is the integer value for id-ServedCellsToDelete.
const IdServedCellsToDelete int64 = 27

// IdServedCellsToModify is the integer value for id-ServedCellsToModify.
const IdServedCellsToModify int64 = 26

// IdServedEUTRAcellsENDCX2ManagementList is the integer value for id-ServedEUTRAcellsENDCX2ManagementList.
const IdServedEUTRAcellsENDCX2ManagementList int64 = 250

// IdServedEUTRAcellsToDeleteListENDCConfUpd is the integer value for id-ServedEUTRAcellsToDeleteListENDCConfUpd.
const IdServedEUTRAcellsToDeleteListENDCConfUpd int64 = 260

// IdServedEUTRAcellsToModifyListENDCConfUpd is the integer value for id-ServedEUTRAcellsToModifyListENDCConfUpd.
const IdServedEUTRAcellsToModifyListENDCConfUpd int64 = 259

// IdServedNRCellsToActivate is the integer value for id-ServedNRCellsToActivate.
const IdServedNRCellsToActivate int64 = 267

// IdServedNRcellsENDCX2ManagementList is the integer value for id-ServedNRcellsENDCX2ManagementList.
const IdServedNRcellsENDCX2ManagementList int64 = 253

// IdServedNRcellsToDeleteListENDCConfUpd is the integer value for id-ServedNRcellsToDeleteListENDCConfUpd.
const IdServedNRcellsToDeleteListENDCConfUpd int64 = 262

// IdServedNRcellsToModifyListENDCConfUpd is the integer value for id-ServedNRcellsToModifyListENDCConfUpd.
const IdServedNRcellsToModifyListENDCConfUpd int64 = 261

// IdServingPLMN is the integer value for id-ServingPLMN.
const IdServingPLMN int64 = 116

// IdSgNBActivityNotification is the integer value for id-SgNBActivityNotification.
const IdSgNBActivityNotification int64 = 42

// IdSgNBCoordinationAssistanceInformation is the integer value for id-SgNBCoordinationAssistanceInformation.
const IdSgNBCoordinationAssistanceInformation int64 = 324

// IdSgNBResourceCoordinationInformation is the integer value for id-SgNBResourceCoordinationInformation.
const IdSgNBResourceCoordinationInformation int64 = 258

// IdSgNBSecurityKey is the integer value for id-SgNBSecurityKey.
const IdSgNBSecurityKey int64 = 203

// IdSgNBUEAggregateMaximumBitRate is the integer value for id-SgNBUEAggregateMaximumBitRate.
const IdSgNBUEAggregateMaximumBitRate int64 = 204

// IdSgNBUEX2APID is the integer value for id-SgNB-UE-X2AP-ID.
const IdSgNBUEX2APID int64 = 207

// IdSgNBtoMeNBContainer is the integer value for id-SgNBtoMeNBContainer.
const IdSgNBtoMeNBContainer int64 = 211

// IdShortMACI is the integer value for id-ShortMAC-I.
const IdShortMACI int64 = 51

// IdSignallingBasedMDTPLMNList is the integer value for id-SignallingBasedMDTPLMNList.
const IdSignallingBasedMDTPLMNList int64 = 90

// IdSourceCellCRNTI is the integer value for id-SourceCellCRNTI.
const IdSourceCellCRNTI int64 = 83

// IdSourceCellECGI is the integer value for id-SourceCellECGI.
const IdSourceCellECGI int64 = 52

// IdSourceDLForwardingIPAddress is the integer value for id-SourceDLForwardingIPAddress.
const IdSourceDLForwardingIPAddress int64 = 412

// IdSourceNodeDLForwardingIPAddress is the integer value for id-SourceNodeDLForwardingIPAddress.
const IdSourceNodeDLForwardingIPAddress int64 = 413

// IdSpectrumSharingGroupID is the integer value for id-SpectrumSharingGroupID.
const IdSpectrumSharingGroupID int64 = 288

// IdSplitSRB is the integer value for id-SplitSRB.
const IdSplitSRB int64 = 242

// IdSubscriberProfileIDforRFP is the integer value for id-SubscriberProfileIDforRFP.
const IdSubscriberProfileIDforRFP int64 = 275

// IdSubscriptionBasedUEDifferentiationInfo is the integer value for id-Subscription-Based-UE-DifferentiationInfo.
const IdSubscriptionBasedUEDifferentiationInfo int64 = 309

// IdTDDULDLConfigurationCommonNR is the integer value for id-TDDULDLConfigurationCommonNR.
const IdTDDULDLConfigurationCommonNR int64 = 385

// IdTNLAFailedToSetupList is the integer value for id-TNLA-Failed-To-Setup-List.
const IdTNLAFailedToSetupList int64 = 357

// IdTNLASetupList is the integer value for id-TNLA-Setup-List.
const IdTNLASetupList int64 = 356

// IdTNLAToAddList is the integer value for id-TNLA-To-Add-List.
const IdTNLAToAddList int64 = 353

// IdTNLAToRemoveList is the integer value for id-TNLA-To-Remove-List.
const IdTNLAToRemoveList int64 = 355

// IdTNLAToUpdateList is the integer value for id-TNLA-To-Update-List.
const IdTNLAToUpdateList int64 = 354

// IdTNLConfigurationInfo is the integer value for id-TNLConfigurationInfo.
const IdTNLConfigurationInfo int64 = 352

// IdTargetCellInNGRAN is the integer value for id-TargetCellInNGRAN.
const IdTargetCellInNGRAN int64 = 382

// IdTargetCellInUTRAN is the integer value for id-TargetCellInUTRAN.
const IdTargetCellInUTRAN int64 = 81

// IdTargetCellID is the integer value for id-TargetCell-ID.
const IdTargetCellID int64 = 11

// IdTargetSgNBID is the integer value for id-Target-SgNB-ID.
const IdTargetSgNBID int64 = 239

// IdTargeteNBtoSourceENBTransparentContainer is the integer value for id-TargeteNBtoSource-eNBTransparentContainer.
const IdTargeteNBtoSourceENBTransparentContainer int64 = 12

// IdTimeToWait is the integer value for id-TimeToWait.
const IdTimeToWait int64 = 22

// IdTimeUEStayedInCellEnhancedGranularity is the integer value for id-Time-UE-StayedInCell-EnhancedGranularity.
const IdTimeUEStayedInCellEnhancedGranularity int64 = 77

// IdTraceActivation is the integer value for id-TraceActivation.
const IdTraceActivation int64 = 13

// IdTraceCollectionEntityIPAddress is the integer value for id-TraceCollectionEntityIPAddress.
const IdTraceCollectionEntityIPAddress int64 = 377

// IdTraceCollectionEntityURI is the integer value for id-TraceCollectionEntityURI.
const IdTraceCollectionEntityURI int64 = 405

// IdTunnelInformationForBBF is the integer value for id-Tunnel-Information-for-BBF.
const IdTunnelInformationForBBF int64 = 163

// IdUEAppLayerMeasConfig is the integer value for id-UEAppLayerMeasConfig.
const IdUEAppLayerMeasConfig int64 = 195

// IdUEContextLevelUserPlaneActivity is the integer value for id-UEContextLevelUserPlaneActivity.
const IdUEContextLevelUserPlaneActivity int64 = 296

// IdUEContextReferenceatSourceNGRAN is the integer value for id-UEContextReferenceatSourceNGRAN.
const IdUEContextReferenceatSourceNGRAN int64 = 359

// IdUEID is the integer value for id-UEID.
const IdUEID int64 = 147

// IdUERadioCapability is the integer value for id-UERadioCapability.
const IdUERadioCapability int64 = 400

// IdUERadioCapabilityID is the integer value for id-UERadioCapabilityID.
const IdUERadioCapabilityID int64 = 378

// IdUERadioCapabilityIDMapping is the integer value for id-UERadioCapabilityIDMapping.
const IdUERadioCapabilityIDMapping int64 = 56

// IdUESidelinkAggregateMaximumBitRate is the integer value for id-UESidelinkAggregateMaximumBitRate.
const IdUESidelinkAggregateMaximumBitRate int64 = 184

// IdUEContextInformation is the integer value for id-UE-ContextInformation.
const IdUEContextInformation int64 = 14

// IdUEContextInformationRetrieve is the integer value for id-UE-ContextInformationRetrieve.
const IdUEContextInformationRetrieve int64 = 173

// IdUEContextInformationSeNBModReq is the integer value for id-UE-ContextInformationSeNBModReq.
const IdUEContextInformationSeNBModReq int64 = 124

// IdUEContextInformationSgNBModReq is the integer value for id-UE-ContextInformation-SgNBModReq.
const IdUEContextInformationSgNBModReq int64 = 215

// IdUEContextKeptIndicator is the integer value for id-UE-ContextKeptIndicator.
const IdUEContextKeptIndicator int64 = 154

// IdUEContextReferenceAtSeNB is the integer value for id-UE-ContextReferenceAtSeNB.
const IdUEContextReferenceAtSeNB int64 = 153

// IdUEContextReferenceAtSgNB is the integer value for id-UE-ContextReferenceAtSgNB.
const IdUEContextReferenceAtSgNB int64 = 254

// IdUEContextReferenceAtWT is the integer value for id-UE-ContextReferenceAtWT.
const IdUEContextReferenceAtWT int64 = 182

// IdUEHistoryInformation is the integer value for id-UE-HistoryInformation.
const IdUEHistoryInformation int64 = 15

// IdUEHistoryInformationFromTheUE is the integer value for id-UE-HistoryInformationFromTheUE.
const IdUEHistoryInformationFromTheUE int64 = 105

// IdUERLFReportContainer is the integer value for id-UE-RLF-Report-Container.
const IdUERLFReportContainer int64 = 60

// IdUERLFReportContainerForExtendedBands is the integer value for id-UE-RLF-Report-Container-for-extended-bands.
const IdUERLFReportContainerForExtendedBands int64 = 107

// IdUESecurityCapabilities is the integer value for id-UE-SecurityCapabilities.
const IdUESecurityCapabilities int64 = 113

// IdUEX2APID is the integer value for id-UE-X2AP-ID.
const IdUEX2APID int64 = 16

// IdUEsAdmittedToBeReset is the integer value for id-UEs-Admitted-ToBeReset.
const IdUEsAdmittedToBeReset int64 = 271

// IdUEsToBeReset is the integer value for id-UEs-ToBeReset.
const IdUEsToBeReset int64 = 270

// IdULCOUNTValueExtended is the integer value for id-ULCOUNTValueExtended.
const IdULCOUNTValueExtended int64 = 92

// IdULCOUNTValuePDCPSNlength18 is the integer value for id-ULCOUNTValuePDCP-SNlength18.
const IdULCOUNTValuePDCPSNlength18 int64 = 151

// IdULCarrierList is the integer value for id-ULCarrierList.
const IdULCarrierList int64 = 387

// IdULEARFCNExtension is the integer value for id-UL-EARFCNExtension.
const IdULEARFCNExtension int64 = 95

// IdULSchedulingPDCCHCCEUsage is the integer value for id-UL-scheduling-PDCCH-CCE-usage.
const IdULSchedulingPDCCHCCEUsage int64 = 194

// IdUnlicensedSpectrumRestriction is the integer value for id-UnlicensedSpectrumRestriction.
const IdUnlicensedSpectrumRestriction int64 = 358

// IdUplinkPacketLossRate is the integer value for id-UplinkPacketLossRate.
const IdUplinkPacketLossRate int64 = 274

// IdV2XServicesAuthorized is the integer value for id-V2XServicesAuthorized.
const IdV2XServicesAuthorized int64 = 176

// IdWLANMeasurementConfiguration is the integer value for id-WLANMeasurementConfiguration.
const IdWLANMeasurementConfiguration int64 = 304

// IdWTUEContextKeptIndicator is the integer value for id-WT-UE-ContextKeptIndicator.
const IdWTUEContextKeptIndicator int64 = 183

// IdX2RemovalThreshold is the integer value for id-X2RemovalThreshold.
const IdX2RemovalThreshold int64 = 169

// IdAccessAndMobilityIndication is the integer value for id-accessAndMobilityIndication.
const IdAccessAndMobilityIndication int64 = 57

// IdAdditionalPLMNsItem is the integer value for id-additionalPLMNs-Item.
const IdAdditionalPLMNsItem int64 = 334

// IdCellActivation is the integer value for id-cellActivation.
const IdCellActivation int64 = 15

// IdCellTrafficTrace is the integer value for id-cellTrafficTrace.
const IdCellTrafficTrace int64 = 52

// IdConditionalHandoverCancel is the integer value for id-conditionalHandoverCancel.
const IdConditionalHandoverCancel int64 = 50

// IdDLPDCPSnLength is the integer value for id-dLPDCPSnLength.
const IdDLPDCPSnLength int64 = 311

// IdDLForwarding is the integer value for id-dL-Forwarding.
const IdDLForwarding int64 = 306

// IdDataForwardingAddressIndication is the integer value for id-dataForwardingAddressIndication.
const IdDataForwardingAddressIndication int64 = 44

// IdDeactivateTrace is the integer value for id-deactivateTrace.
const IdDeactivateTrace int64 = 46

// IdDuplicationActivation is the integer value for id-duplicationActivation.
const IdDuplicationActivation int64 = 315

// IdEARFCNExtension is the integer value for id-eARFCNExtension.
const IdEARFCNExtension int64 = 94

// IdENBConfigurationUpdate is the integer value for id-eNBConfigurationUpdate.
const IdENBConfigurationUpdate int64 = 8

// IdEUTRANRCellResourceCoordination is the integer value for id-eUTRANRCellResourceCoordination.
const IdEUTRANRCellResourceCoordination int64 = 41

// IdEarlyStatusTransfer is the integer value for id-earlyStatusTransfer.
const IdEarlyStatusTransfer int64 = 51

// IdEndcCellActivation is the integer value for id-endcCellActivation.
const IdEndcCellActivation int64 = 39

// IdEndcConfigurationTransfer is the integer value for id-endcConfigurationTransfer.
const IdEndcConfigurationTransfer int64 = 48

// IdEndcConfigurationUpdate is the integer value for id-endcConfigurationUpdate.
const IdEndcConfigurationUpdate int64 = 37

// IdEndcPartialReset is the integer value for id-endcPartialReset.
const IdEndcPartialReset int64 = 40

// IdEndcSONConfigurationTransfer is the integer value for id-endcSONConfigurationTransfer.
const IdEndcSONConfigurationTransfer int64 = 326

// IdEndcX2Removal is the integer value for id-endcX2Removal.
const IdEndcX2Removal int64 = 43

// IdEndcX2Setup is the integer value for id-endcX2Setup.
const IdEndcX2Setup int64 = 36

// IdEndcresourceStatusReporting is the integer value for id-endcresourceStatusReporting.
const IdEndcresourceStatusReporting int64 = 53

// IdEndcresourceStatusReportingInitiation is the integer value for id-endcresourceStatusReportingInitiation.
const IdEndcresourceStatusReportingInitiation int64 = 54

// IdEnhancedRNTP is the integer value for id-enhancedRNTP.
const IdEnhancedRNTP int64 = 148

// IdErrorIndication is the integer value for id-errorIndication.
const IdErrorIndication int64 = 3

// IdExtendedERABGuaranteedBitrateDL is the integer value for id-extended-e-RAB-GuaranteedBitrateDL.
const IdExtendedERABGuaranteedBitrateDL int64 = 198

// IdExtendedERABGuaranteedBitrateUL is the integer value for id-extended-e-RAB-GuaranteedBitrateUL.
const IdExtendedERABGuaranteedBitrateUL int64 = 199

// IdExtendedERABMaximumBitrateDL is the integer value for id-extended-e-RAB-MaximumBitrateDL.
const IdExtendedERABMaximumBitrateDL int64 = 196

// IdExtendedERABMaximumBitrateUL is the integer value for id-extended-e-RAB-MaximumBitrateUL.
const IdExtendedERABMaximumBitrateUL int64 = 197

// IdExtendedUEaggregateMaximumBitRateDownlink is the integer value for id-extended-uEaggregateMaximumBitRateDownlink.
const IdExtendedUEaggregateMaximumBitRateDownlink int64 = 200

// IdExtendedUEaggregateMaximumBitRateUplink is the integer value for id-extended-uEaggregateMaximumBitRateUplink.
const IdExtendedUEaggregateMaximumBitRateUplink int64 = 201

// IdF1CTrafficTransfer is the integer value for id-f1CTrafficTransfer.
const IdF1CTrafficTransfer int64 = 55

// IdGNBStatusIndication is the integer value for id-gNBStatusIndication.
const IdGNBStatusIndication int64 = 45

// IdHandoverCancel is the integer value for id-handoverCancel.
const IdHandoverCancel int64 = 1

// IdHandoverPreparation is the integer value for id-handoverPreparation.
const IdHandoverPreparation int64 = 0

// IdHandoverReport is the integer value for id-handoverReport.
const IdHandoverReport int64 = 14

// IdHandoverSuccess is the integer value for id-handoverSuccess.
const IdHandoverSuccess int64 = 49

// IdLCID is the integer value for id-lCID.
const IdLCID int64 = 314

// IdLoadIndication is the integer value for id-loadIndication.
const IdLoadIndication int64 = 2

// IdMeNBinitiatedSeNBModificationPreparation is the integer value for id-meNBinitiatedSeNBModificationPreparation.
const IdMeNBinitiatedSeNBModificationPreparation int64 = 21

// IdMeNBinitiatedSeNBRelease is the integer value for id-meNBinitiatedSeNBRelease.
const IdMeNBinitiatedSeNBRelease int64 = 23

// IdMeNBinitiatedSgNBModificationPreparation is the integer value for id-meNBinitiatedSgNBModificationPreparation.
const IdMeNBinitiatedSgNBModificationPreparation int64 = 29

// IdMeNBinitiatedSgNBRelease is the integer value for id-meNBinitiatedSgNBRelease.
const IdMeNBinitiatedSgNBRelease int64 = 31

// IdMobilitySettingsChange is the integer value for id-mobilitySettingsChange.
const IdMobilitySettingsChange int64 = 12

// IdNewDrbIDReq is the integer value for id-new-drb-ID-req.
const IdNewDrbIDReq int64 = 325

// IdPrivateMessage is the integer value for id-privateMessage.
const IdPrivateMessage int64 = 11

// IdProcedureCode58NotToBeUsed is the integer value for id-procedure-code-58-not-to-be-used.
const IdProcedureCode58NotToBeUsed int64 = 58

// IdRLFIndication is the integer value for id-rLFIndication.
const IdRLFIndication int64 = 13

// IdRRCTransfer is the integer value for id-rRCTransfer.
const IdRRCTransfer int64 = 35

// IdReset is the integer value for id-reset.
const IdReset int64 = 7

// IdResourceStatusReporting is the integer value for id-resourceStatusReporting.
const IdResourceStatusReporting int64 = 10

// IdResourceStatusReportingInitiation is the integer value for id-resourceStatusReportingInitiation.
const IdResourceStatusReportingInitiation int64 = 9

// IdResumeID is the integer value for id-resumeID.
const IdResumeID int64 = 172

// IdRetrieveUEContext is the integer value for id-retrieveUEContext.
const IdRetrieveUEContext int64 = 26

// IdSeNBAdditionPreparation is the integer value for id-seNBAdditionPreparation.
const IdSeNBAdditionPreparation int64 = 19

// IdSeNBCounterCheck is the integer value for id-seNBCounterCheck.
const IdSeNBCounterCheck int64 = 25

// IdSeNBReconfigurationCompletion is the integer value for id-seNBReconfigurationCompletion.
const IdSeNBReconfigurationCompletion int64 = 20

// IdSeNBinitiatedSeNBModification is the integer value for id-seNBinitiatedSeNBModification.
const IdSeNBinitiatedSeNBModification int64 = 22

// IdSeNBinitiatedSeNBRelease is the integer value for id-seNBinitiatedSeNBRelease.
const IdSeNBinitiatedSeNBRelease int64 = 24

// IdSecondaryRATDataUsageReport is the integer value for id-secondaryRATDataUsageReport.
const IdSecondaryRATDataUsageReport int64 = 38

// IdSecondarymeNBULGTPTEIDatPDCP is the integer value for id-secondarymeNBULGTPTEIDatPDCP.
const IdSecondarymeNBULGTPTEIDatPDCP int64 = 313

// IdSecondarysgNBDLGTPTEIDatPDCP is the integer value for id-secondarysgNBDLGTPTEIDatPDCP.
const IdSecondarysgNBDLGTPTEIDatPDCP int64 = 312

// IdServiceType is the integer value for id-serviceType.
const IdServiceType int64 = 276

// IdSgNBAdditionPreparation is the integer value for id-sgNBAdditionPreparation.
const IdSgNBAdditionPreparation int64 = 27

// IdSgNBChange is the integer value for id-sgNBChange.
const IdSgNBChange int64 = 34

// IdSgNBCounterCheck is the integer value for id-sgNBCounterCheck.
const IdSgNBCounterCheck int64 = 33

// IdSgNBReconfigurationCompletion is the integer value for id-sgNBReconfigurationCompletion.
const IdSgNBReconfigurationCompletion int64 = 28

// IdSgNBinitiatedSgNBModification is the integer value for id-sgNBinitiatedSgNBModification.
const IdSgNBinitiatedSgNBModification int64 = 30

// IdSgNBinitiatedSgNBRelease is the integer value for id-sgNBinitiatedSgNBRelease.
const IdSgNBinitiatedSgNBRelease int64 = 32

// IdSnStatusTransfer is the integer value for id-snStatusTransfer.
const IdSnStatusTransfer int64 = 4

// IdSourceNGRANNodeId is the integer value for id-sourceNG-RAN-node-id.
const IdSourceNGRANNodeId int64 = 411

// IdTraceStart is the integer value for id-traceStart.
const IdTraceStart int64 = 47

// IdUEContextRelease is the integer value for id-uEContextRelease.
const IdUEContextRelease int64 = 5

// IdULGTPtunnelEndpoint is the integer value for id-uL-GTPtunnelEndpoint.
const IdULGTPtunnelEndpoint int64 = 185

// IdULpDCPSnLength is the integer value for id-uLpDCPSnLength.
const IdULpDCPSnLength int64 = 302

// IdX2APMessage is the integer value for id-x2APMessage.
const IdX2APMessage int64 = 102

// IdX2APMessageTransfer is the integer value for id-x2APMessageTransfer.
const IdX2APMessageTransfer int64 = 17

// IdX2Release is the integer value for id-x2Release.
const IdX2Release int64 = 16

// IdX2Removal is the integer value for id-x2Removal.
const IdX2Removal int64 = 18

// IdX2Setup is the integer value for id-x2Setup.
const IdX2Setup int64 = 6

// MaxCSIProcess is the integer value for maxCSIProcess.
const MaxCSIProcess int64 = 4

// MaxCSIReport is the integer value for maxCSIReport.
const MaxCSIReport int64 = 2

// MaxCellReport is the integer value for maxCellReport.
const MaxCellReport int64 = 9

// MaxCellineNB is the integer value for maxCellineNB.
const MaxCellineNB int64 = 256

// MaxCellinengNB is the integer value for maxCellinengNB.
const MaxCellinengNB int64 = 16384

// MaxEARFCN is the integer value for maxEARFCN.
const MaxEARFCN int64 = 65535

// MaxEARFCNPlusOne is the integer value for maxEARFCNPlusOne.
const MaxEARFCNPlusOne int64 = 65536

// MaxFailedMeasObjects is the integer value for maxFailedMeasObjects.
const MaxFailedMeasObjects int64 = 32

// MaxInterfaces is the integer value for maxInterfaces.
const MaxInterfaces int64 = 16

// MaxNrOfErrors is the integer value for maxNrOfErrors.
const MaxNrOfErrors int64 = 256

// MaxPools is the integer value for maxPools.
const MaxPools int64 = 16

// MaxSubband is the integer value for maxSubband.
const MaxSubband int64 = 14

// MaxUEReport is the integer value for maxUEReport.
const MaxUEReport int64 = 128

// MaxUEsinengNBDU is the integer value for maxUEsinengNBDU.
const MaxUEsinengNBDU int64 = 8192

// MaxnoNRcellsSpectrumSharingWithEUTRA is the integer value for maxnoNRcellsSpectrumSharingWithE-UTRA.
const MaxnoNRcellsSpectrumSharingWithEUTRA int64 = 64

// MaxnoofAdditionalPLMNs is the integer value for maxnoofAdditionalPLMNs.
const MaxnoofAdditionalPLMNs int64 = 6

// MaxnoofBPLMNs is the integer value for maxnoofBPLMNs.
const MaxnoofBPLMNs int64 = 6

// MaxnoofBands is the integer value for maxnoofBands.
const MaxnoofBands int64 = 16

// MaxnoofBearers is the integer value for maxnoofBearers.
const MaxnoofBearers int64 = 256

// MaxnoofBluetoothName is the integer value for maxnoofBluetoothName.
const MaxnoofBluetoothName int64 = 4

// MaxnoofCSIRSconfigurations is the integer value for maxnoofCSIRSconfigurations.
const MaxnoofCSIRSconfigurations int64 = 96

// MaxnoofCSIRSneighbourCells is the integer value for maxnoofCSIRSneighbourCells.
const MaxnoofCSIRSneighbourCells int64 = 16

// MaxnoofCSIRSneighbourCellsInMTC is the integer value for maxnoofCSIRSneighbourCellsInMTC.
const MaxnoofCSIRSneighbourCellsInMTC int64 = 16

// MaxnoofCellIDforMDT is the integer value for maxnoofCellIDforMDT.
const MaxnoofCellIDforMDT int64 = 32

// MaxnoofCellIDforQMC is the integer value for maxnoofCellIDforQMC.
const MaxnoofCellIDforQMC int64 = 32

// MaxnoofCells is the integer value for maxnoofCells.
const MaxnoofCells int64 = 16

// MaxnoofCellsinCHO is the integer value for maxnoofCellsinCHO.
const MaxnoofCellsinCHO int64 = 8

// MaxnoofCoMPCells is the integer value for maxnoofCoMPCells.
const MaxnoofCoMPCells int64 = 32

// MaxnoofCoMPHypothesisSet is the integer value for maxnoofCoMPHypothesisSet.
const MaxnoofCoMPHypothesisSet int64 = 256

// MaxnoofEPLMNs is the integer value for maxnoofEPLMNs.
const MaxnoofEPLMNs int64 = 15

// MaxnoofEPLMNsPlusOne is the integer value for maxnoofEPLMNsPlusOne.
const MaxnoofEPLMNsPlusOne int64 = 16

// MaxnoofForbLACs is the integer value for maxnoofForbLACs.
const MaxnoofForbLACs int64 = 4096

// MaxnoofForbTACs is the integer value for maxnoofForbTACs.
const MaxnoofForbTACs int64 = 4096

// MaxnoofGTPTLAs is the integer value for maxnoofGTPTLAs.
const MaxnoofGTPTLAs int64 = 16

// MaxnoofMBMSServiceAreaIdentities is the integer value for maxnoofMBMSServiceAreaIdentities.
const MaxnoofMBMSServiceAreaIdentities int64 = 256

// MaxnoofMBSFN is the integer value for maxnoofMBSFN.
const MaxnoofMBSFN int64 = 8

// MaxnoofMDTPLMNs is the integer value for maxnoofMDTPLMNs.
const MaxnoofMDTPLMNs int64 = 16

// MaxnoofMTCItems is the integer value for maxnoofMTCItems.
const MaxnoofMTCItems int64 = 16

// MaxnoofNRPhysicalResourceBlocks is the integer value for maxnoofNRPhysicalResourceBlocks.
const MaxnoofNRPhysicalResourceBlocks int64 = 275

// MaxnoofNRSCSs is the integer value for maxnoofNRSCSs.
const MaxnoofNRSCSs int64 = 5

// MaxnoofNeighbours is the integer value for maxnoofNeighbours.
const MaxnoofNeighbours int64 = 512

// MaxnoofNonAnchorCarrierFreqConfig is the integer value for maxnoofNonAnchorCarrierFreqConfig.
const MaxnoofNonAnchorCarrierFreqConfig int64 = 15

// MaxnoofNrCellBands is the integer value for maxnoofNrCellBands.
const MaxnoofNrCellBands int64 = 32

// MaxnoofPA is the integer value for maxnoofPA.
const MaxnoofPA int64 = 3

// MaxnoofPC5QoSFlows is the integer value for maxnoofPC5QoSFlows.
const MaxnoofPC5QoSFlows int64 = 2048

// MaxnoofPDCPSN is the integer value for maxnoofPDCP-SN.
const MaxnoofPDCPSN int64 = 16

// MaxnoofPLMNforQMC is the integer value for maxnoofPLMNforQMC.
const MaxnoofPLMNforQMC int64 = 16

// MaxnoofPRBs is the integer value for maxnoofPRBs.
const MaxnoofPRBs int64 = 110

// MaxnoofPSCellCandidates is the integer value for maxnoofPSCellCandidates.
const MaxnoofPSCellCandidates int64 = 8

// MaxnoofPSCellsPerPrimaryCellinUEHistoryInfo is the integer value for maxnoofPSCellsPerPrimaryCellinUEHistoryInfo.
const MaxnoofPSCellsPerPrimaryCellinUEHistoryInfo int64 = 8

// MaxnoofPSCellsPerSN is the integer value for maxnoofPSCellsPerSN.
const MaxnoofPSCellsPerSN int64 = 8

// MaxnoofProtectedResourcePatterns is the integer value for maxnoofProtectedResourcePatterns.
const MaxnoofProtectedResourcePatterns int64 = 16

// MaxnoofRACHReports is the integer value for maxnoofRACHReports.
const MaxnoofRACHReports int64 = 64

// MaxnoofReportedNRCellsPossiblyAggregated is the integer value for maxnoofReportedNRCellsPossiblyAggregated.
const MaxnoofReportedNRCellsPossiblyAggregated int64 = 16

// MaxnoofSSBAreas is the integer value for maxnoofSSBAreas.
const MaxnoofSSBAreas int64 = 64

// MaxnoofSensorName is the integer value for maxnoofSensorName.
const MaxnoofSensorName int64 = 3

// MaxnoofTAforMDT is the integer value for maxnoofTAforMDT.
const MaxnoofTAforMDT int64 = 8

// MaxnoofTAforQMC is the integer value for maxnoofTAforQMC.
const MaxnoofTAforQMC int64 = 8

// MaxnoofTLAs is the integer value for maxnoofTLAs.
const MaxnoofTLAs int64 = 16

// MaxnoofTNLAssociations is the integer value for maxnoofTNLAssociations.
const MaxnoofTNLAssociations int64 = 32

// MaxnoofTargetSgNBs is the integer value for maxnoofTargetSgNBs.
const MaxnoofTargetSgNBs int64 = 8

// MaxnoofTargetSgNBsMinusOne is the integer value for maxnoofTargetSgNBsMinusOne.
const MaxnoofTargetSgNBsMinusOne int64 = 7

// MaxnoofWLANName is the integer value for maxnoofWLANName.
const MaxnoofWLANName int64 = 4

// MaxnoofextBPLMNs is the integer value for maxnoofextBPLMNs.
const MaxnoofextBPLMNs int64 = 12

// Maxnooftimeperiods is the integer value for maxnooftimeperiods.
const Maxnooftimeperiods int64 = 2

// MaxofNRNeighbours is the integer value for maxofNRNeighbours.
const MaxofNRNeighbours int64 = 1024

// NewmaxEARFCN is the integer value for newmaxEARFCN.
const NewmaxEARFCN int64 = 262143
