// Code generated by asn1c-go. DO NOT EDIT.

package gsm_map

import "fmt"

// ErrorCode is a typed alias for MAP error codes.
type ErrorCode int64

const (
	// AbsentSubscriber is the error code for absentSubscriber.
	AbsentSubscriber ErrorCode = 27
	// AbsentSubscriberSM is the error code for absentSubscriberSM.
	AbsentSubscriberSM ErrorCode = 6
	// AtiNotAllowed is the error code for ati-NotAllowed.
	AtiNotAllowed ErrorCode = 49
	// AtmNotAllowed is the error code for atm-NotAllowed.
	AtmNotAllowed ErrorCode = 61
	// AtsiNotAllowed is the error code for atsi-NotAllowed.
	AtsiNotAllowed ErrorCode = 60
	// BearerServiceNotProvisioned is the error code for bearerServiceNotProvisioned.
	BearerServiceNotProvisioned ErrorCode = 10
	// BusySubscriber is the error code for busySubscriber.
	BusySubscriber ErrorCode = 45
	// CallBarred is the error code for callBarred.
	CallBarred ErrorCode = 13
	// CugReject is the error code for cug-Reject.
	CugReject ErrorCode = 15
	// DataMissing is the error code for dataMissing.
	DataMissing ErrorCode = 35
	// FacilityNotSupported is the error code for facilityNotSupported.
	FacilityNotSupported ErrorCode = 21
	// ForwardingFailed is the error code for forwardingFailed.
	ForwardingFailed ErrorCode = 47
	// ForwardingViolation is the error code for forwardingViolation.
	ForwardingViolation ErrorCode = 14
	// IllegalEquipment is the error code for illegalEquipment.
	IllegalEquipment ErrorCode = 12
	// IllegalSSOperation is the error code for illegalSS-Operation.
	IllegalSSOperation ErrorCode = 16
	// IllegalSubscriber is the error code for illegalSubscriber.
	IllegalSubscriber ErrorCode = 9
	// IncompatibleTerminal is the error code for incompatibleTerminal.
	IncompatibleTerminal ErrorCode = 28
	// InformationNotAvailable is the error code for informationNotAvailable.
	InformationNotAvailable ErrorCode = 62
	// LongTermDenial is the error code for longTermDenial.
	LongTermDenial ErrorCode = 30
	// MessageWaitingListFull is the error code for messageWaitingListFull.
	MessageWaitingListFull ErrorCode = 33
	// MmEventNotSupported is the error code for mm-EventNotSupported.
	MmEventNotSupported ErrorCode = 59
	// NegativePWCheck is the error code for negativePW-Check.
	NegativePWCheck ErrorCode = 38
	// NoGroupCallNumberAvailable is the error code for noGroupCallNumberAvailable.
	NoGroupCallNumberAvailable ErrorCode = 50
	// NoHandoverNumberAvailable is the error code for noHandoverNumberAvailable.
	NoHandoverNumberAvailable ErrorCode = 25
	// NoRoamingNumberAvailable is the error code for noRoamingNumberAvailable.
	NoRoamingNumberAvailable ErrorCode = 39
	// NoSubscriberReply is the error code for noSubscriberReply.
	NoSubscriberReply ErrorCode = 46
	// NumberChanged is the error code for numberChanged.
	NumberChanged ErrorCode = 44
	// NumberOfPWAttemptsViolation is the error code for numberOfPW-AttemptsViolation.
	NumberOfPWAttemptsViolation ErrorCode = 43
	// OngoingGroupCall is the error code for ongoingGroupCall.
	OngoingGroupCall ErrorCode = 22
	// OrNotAllowed is the error code for or-NotAllowed.
	OrNotAllowed ErrorCode = 48
	// PositionMethodFailure is the error code for positionMethodFailure.
	PositionMethodFailure ErrorCode = 54
	// PwRegistrationFailure is the error code for pw-RegistrationFailure.
	PwRegistrationFailure ErrorCode = 37
	// ResourceLimitation is the error code for resourceLimitation.
	ResourceLimitation ErrorCode = 51
	// RoamingNotAllowed is the error code for roamingNotAllowed.
	RoamingNotAllowed ErrorCode = 8
	// ShortTermDenial is the error code for shortTermDenial.
	ShortTermDenial ErrorCode = 29
	// SmDeliveryFailure is the error code for sm-DeliveryFailure.
	SmDeliveryFailure ErrorCode = 32
	// SsErrorStatus is the error code for ss-ErrorStatus.
	SsErrorStatus ErrorCode = 17
	// SsIncompatibility is the error code for ss-Incompatibility.
	SsIncompatibility ErrorCode = 20
	// SsNotAvailable is the error code for ss-NotAvailable.
	SsNotAvailable ErrorCode = 18
	// SsSubscriptionViolation is the error code for ss-SubscriptionViolation.
	SsSubscriptionViolation ErrorCode = 19
	// SubscriberBusyForMTSMS is the error code for subscriberBusyForMT-SMS.
	SubscriberBusyForMTSMS ErrorCode = 31
	// SubsequentHandoverFailure is the error code for subsequentHandoverFailure.
	SubsequentHandoverFailure ErrorCode = 26
	// SystemFailure is the error code for systemFailure.
	SystemFailure ErrorCode = 34
	// TargetCellOutsideGroupCallArea is the error code for targetCellOutsideGroupCallArea.
	TargetCellOutsideGroupCallArea ErrorCode = 42
	// TeleserviceNotProvisioned is the error code for teleserviceNotProvisioned.
	TeleserviceNotProvisioned ErrorCode = 11
	// TracingBufferFull is the error code for tracingBufferFull.
	TracingBufferFull ErrorCode = 40
	// UnauthorizedLCSClient is the error code for unauthorizedLCSClient.
	UnauthorizedLCSClient ErrorCode = 53
	// UnauthorizedRequestingNetwork is the error code for unauthorizedRequestingNetwork.
	UnauthorizedRequestingNetwork ErrorCode = 52
	// UnexpectedDataValue is the error code for unexpectedDataValue.
	UnexpectedDataValue ErrorCode = 36
	// UnidentifiedSubscriber is the error code for unidentifiedSubscriber.
	UnidentifiedSubscriber ErrorCode = 5
	// UnknownAlphabet is the error code for unknownAlphabet.
	UnknownAlphabet ErrorCode = 71
	// UnknownEquipment is the error code for unknownEquipment.
	UnknownEquipment ErrorCode = 7
	// UnknownMSC is the error code for unknownMSC.
	UnknownMSC ErrorCode = 3
	// UnknownOrUnreachableLCSClient is the error code for unknownOrUnreachableLCSClient.
	UnknownOrUnreachableLCSClient ErrorCode = 58
	// UnknownSubscriber is the error code for unknownSubscriber.
	UnknownSubscriber ErrorCode = 1
	// UssdBusy is the error code for ussd-Busy.
	UssdBusy ErrorCode = 72
	// Refuse is the error code for refuse.
	Refuse ErrorCode = -1
)

// String returns the ASN.1 name of the error code.
func (c ErrorCode) String() string {
	switch c {
	case 27:
		return "absentSubscriber"
	case 6:
		return "absentSubscriberSM"
	case 49:
		return "ati-NotAllowed"
	case 61:
		return "atm-NotAllowed"
	case 60:
		return "atsi-NotAllowed"
	case 10:
		return "bearerServiceNotProvisioned"
	case 45:
		return "busySubscriber"
	case 13:
		return "callBarred"
	case 15:
		return "cug-Reject"
	case 35:
		return "dataMissing"
	case 21:
		return "facilityNotSupported"
	case 47:
		return "forwardingFailed"
	case 14:
		return "forwardingViolation"
	case 12:
		return "illegalEquipment"
	case 16:
		return "illegalSS-Operation"
	case 9:
		return "illegalSubscriber"
	case 28:
		return "incompatibleTerminal"
	case 62:
		return "informationNotAvailable"
	case 30:
		return "longTermDenial"
	case 33:
		return "messageWaitingListFull"
	case 59:
		return "mm-EventNotSupported"
	case 38:
		return "negativePW-Check"
	case 50:
		return "noGroupCallNumberAvailable"
	case 25:
		return "noHandoverNumberAvailable"
	case 39:
		return "noRoamingNumberAvailable"
	case 46:
		return "noSubscriberReply"
	case 44:
		return "numberChanged"
	case 43:
		return "numberOfPW-AttemptsViolation"
	case 22:
		return "ongoingGroupCall"
	case 48:
		return "or-NotAllowed"
	case 54:
		return "positionMethodFailure"
	case 37:
		return "pw-RegistrationFailure"
	case 51:
		return "resourceLimitation"
	case 8:
		return "roamingNotAllowed"
	case 29:
		return "shortTermDenial"
	case 32:
		return "sm-DeliveryFailure"
	case 17:
		return "ss-ErrorStatus"
	case 20:
		return "ss-Incompatibility"
	case 18:
		return "ss-NotAvailable"
	case 19:
		return "ss-SubscriptionViolation"
	case 31:
		return "subscriberBusyForMT-SMS"
	case 26:
		return "subsequentHandoverFailure"
	case 34:
		return "systemFailure"
	case 42:
		return "targetCellOutsideGroupCallArea"
	case 11:
		return "teleserviceNotProvisioned"
	case 40:
		return "tracingBufferFull"
	case 53:
		return "unauthorizedLCSClient"
	case 52:
		return "unauthorizedRequestingNetwork"
	case 36:
		return "unexpectedDataValue"
	case 5:
		return "unidentifiedSubscriber"
	case 71:
		return "unknownAlphabet"
	case 7:
		return "unknownEquipment"
	case 3:
		return "unknownMSC"
	case 58:
		return "unknownOrUnreachableLCSClient"
	case 1:
		return "unknownSubscriber"
	case 72:
		return "ussd-Busy"
	case -1:
		return "refuse"
	default:
		return fmt.Sprintf("ErrorCode(%d)", int64(c))
	}
}

// OperationCode is a typed alias for MAP operation codes.
type OperationCode int64

const (
	// IstAlert is the operation code for ist-Alert.
	IstAlert OperationCode = 87
	// IstCommand is the operation code for ist-Command.
	IstCommand OperationCode = 88
	// ProvideRoamingNumber is the operation code for provideRoamingNumber.
	ProvideRoamingNumber OperationCode = 4
	// ReleaseResources is the operation code for releaseResources.
	ReleaseResources OperationCode = 20
	// RemoteUserFree is the operation code for remoteUserFree.
	RemoteUserFree OperationCode = 75
	// ResumeCallHandling is the operation code for resumeCallHandling.
	ResumeCallHandling OperationCode = 6
	// SendRoutingInfo is the operation code for sendRoutingInfo.
	SendRoutingInfo OperationCode = 22
	// SetReportingState is the operation code for setReportingState.
	SetReportingState OperationCode = 73
	// StatusReport is the operation code for statusReport.
	StatusReport OperationCode = 74
	// ForwardGroupCallSignalling is the operation code for forwardGroupCallSignalling.
	ForwardGroupCallSignalling OperationCode = 42
	// PrepareGroupCall is the operation code for prepareGroupCall.
	PrepareGroupCall OperationCode = 39
	// ProcessGroupCallSignalling is the operation code for processGroupCallSignalling.
	ProcessGroupCallSignalling OperationCode = 41
	// SendGroupCallEndSignal is the operation code for sendGroupCallEndSignal.
	SendGroupCallEndSignal OperationCode = 40
	// SendGroupCallInfo is the operation code for sendGroupCallInfo.
	SendGroupCallInfo OperationCode = 84
	// ProvideSubscriberLocation is the operation code for provideSubscriberLocation.
	ProvideSubscriberLocation OperationCode = 83
	// SendRoutingInfoForLCS is the operation code for sendRoutingInfoForLCS.
	SendRoutingInfoForLCS OperationCode = 85
	// SubscriberLocationReport is the operation code for subscriberLocationReport.
	SubscriberLocationReport OperationCode = 86
	// AnyTimeInterrogation is the operation code for anyTimeInterrogation.
	AnyTimeInterrogation OperationCode = 71
	// AnyTimeModification is the operation code for anyTimeModification.
	AnyTimeModification OperationCode = 65
	// AnyTimeSubscriptionInterrogation is the operation code for anyTimeSubscriptionInterrogation.
	AnyTimeSubscriptionInterrogation OperationCode = 62
	// AuthenticationFailureReport is the operation code for authenticationFailureReport.
	AuthenticationFailureReport OperationCode = 15
	// CancelLocation is the operation code for cancelLocation.
	CancelLocation OperationCode = 3
	// CancelVcsgLocation is the operation code for cancelVcsgLocation.
	CancelVcsgLocation OperationCode = 36
	// CheckIMEI is the operation code for checkIMEI.
	CheckIMEI OperationCode = 43
	// DeleteSubscriberData is the operation code for deleteSubscriberData.
	DeleteSubscriberData OperationCode = 8
	// FailureReport is the operation code for failureReport.
	FailureReport OperationCode = 25
	// ForwardAccessSignalling is the operation code for forwardAccessSignalling.
	ForwardAccessSignalling OperationCode = 34
	// ForwardCheckSSIndication is the operation code for forwardCheckSS-Indication.
	ForwardCheckSSIndication OperationCode = 38
	// InsertSubscriberData is the operation code for insertSubscriberData.
	InsertSubscriberData OperationCode = 7
	// NoteMMEvent is the operation code for noteMM-Event.
	NoteMMEvent OperationCode = 89
	// NoteMsPresentForGprs is the operation code for noteMsPresentForGprs.
	NoteMsPresentForGprs OperationCode = 26
	// NoteSubscriberDataModified is the operation code for noteSubscriberDataModified.
	NoteSubscriberDataModified OperationCode = 5
	// PrepareHandover is the operation code for prepareHandover.
	PrepareHandover OperationCode = 68
	// PrepareSubsequentHandover is the operation code for prepareSubsequentHandover.
	PrepareSubsequentHandover OperationCode = 69
	// ProcessAccessSignalling is the operation code for processAccessSignalling.
	ProcessAccessSignalling OperationCode = 33
	// ProvideSubscriberInfo is the operation code for provideSubscriberInfo.
	ProvideSubscriberInfo OperationCode = 70
	// PurgeMS is the operation code for purgeMS.
	PurgeMS OperationCode = 67
	// Reset is the operation code for reset.
	Reset OperationCode = 37
	// RestoreData is the operation code for restoreData.
	RestoreData OperationCode = 57
	// SendAuthenticationInfo is the operation code for sendAuthenticationInfo.
	SendAuthenticationInfo OperationCode = 56
	// SendEndSignal is the operation code for sendEndSignal.
	SendEndSignal OperationCode = 29
	// SendIdentification is the operation code for sendIdentification.
	SendIdentification OperationCode = 55
	// SendRoutingInfoForGprs is the operation code for sendRoutingInfoForGprs.
	SendRoutingInfoForGprs OperationCode = 24
	// UpdateGprsLocation is the operation code for updateGprsLocation.
	UpdateGprsLocation OperationCode = 23
	// UpdateLocation is the operation code for updateLocation.
	UpdateLocation OperationCode = 2
	// UpdateVcsgLocation is the operation code for updateVcsgLocation.
	UpdateVcsgLocation OperationCode = 53
	// ActivateTraceMode is the operation code for activateTraceMode.
	ActivateTraceMode OperationCode = 50
	// DeactivateTraceMode is the operation code for deactivateTraceMode.
	DeactivateTraceMode OperationCode = 51
	// SendIMSI is the operation code for sendIMSI.
	SendIMSI OperationCode = 58
	// AlertServiceCentre is the operation code for alertServiceCentre.
	AlertServiceCentre OperationCode = 64
	// InformServiceCentre is the operation code for informServiceCentre.
	InformServiceCentre OperationCode = 63
	// MoForwardSM is the operation code for mo-ForwardSM.
	MoForwardSM OperationCode = 46
	// MtForwardSM is the operation code for mt-ForwardSM.
	MtForwardSM OperationCode = 44
	// MtForwardSMVGCS is the operation code for mt-ForwardSM-VGCS.
	MtForwardSMVGCS OperationCode = 21
	// ReadyForSM is the operation code for readyForSM.
	ReadyForSM OperationCode = 66
	// ReportSMDeliveryStatus is the operation code for reportSM-DeliveryStatus.
	ReportSMDeliveryStatus OperationCode = 47
	// SendRoutingInfoForSM is the operation code for sendRoutingInfoForSM.
	SendRoutingInfoForSM OperationCode = 45
	// ActivateSS is the operation code for activateSS.
	ActivateSS OperationCode = 12
	// DeactivateSS is the operation code for deactivateSS.
	DeactivateSS OperationCode = 13
	// EraseCCEntry is the operation code for eraseCC-Entry.
	EraseCCEntry OperationCode = 77
	// EraseSS is the operation code for eraseSS.
	EraseSS OperationCode = 11
	// GetPassword is the operation code for getPassword.
	GetPassword OperationCode = 18
	// InterrogateSS is the operation code for interrogateSS.
	InterrogateSS OperationCode = 14
	// ProcessUnstructuredSSRequest is the operation code for processUnstructuredSS-Request.
	ProcessUnstructuredSSRequest OperationCode = 59
	// RegisterCCEntry is the operation code for registerCC-Entry.
	RegisterCCEntry OperationCode = 76
	// RegisterPassword is the operation code for registerPassword.
	RegisterPassword OperationCode = 17
	// RegisterSS is the operation code for registerSS.
	RegisterSS OperationCode = 10
	// SsInvocationNotification is the operation code for ss-InvocationNotification.
	SsInvocationNotification OperationCode = 72
	// UnstructuredSSNotify is the operation code for unstructuredSS-Notify.
	UnstructuredSSNotify OperationCode = 61
	// UnstructuredSSRequest is the operation code for unstructuredSS-Request.
	UnstructuredSSRequest OperationCode = 60
)

// String returns the ASN.1 name of the operation code.
func (c OperationCode) String() string {
	switch c {
	case 87:
		return "ist-Alert"
	case 88:
		return "ist-Command"
	case 4:
		return "provideRoamingNumber"
	case 20:
		return "releaseResources"
	case 75:
		return "remoteUserFree"
	case 6:
		return "resumeCallHandling"
	case 22:
		return "sendRoutingInfo"
	case 73:
		return "setReportingState"
	case 74:
		return "statusReport"
	case 42:
		return "forwardGroupCallSignalling"
	case 39:
		return "prepareGroupCall"
	case 41:
		return "processGroupCallSignalling"
	case 40:
		return "sendGroupCallEndSignal"
	case 84:
		return "sendGroupCallInfo"
	case 83:
		return "provideSubscriberLocation"
	case 85:
		return "sendRoutingInfoForLCS"
	case 86:
		return "subscriberLocationReport"
	case 71:
		return "anyTimeInterrogation"
	case 65:
		return "anyTimeModification"
	case 62:
		return "anyTimeSubscriptionInterrogation"
	case 15:
		return "authenticationFailureReport"
	case 3:
		return "cancelLocation"
	case 36:
		return "cancelVcsgLocation"
	case 43:
		return "checkIMEI"
	case 8:
		return "deleteSubscriberData"
	case 25:
		return "failureReport"
	case 34:
		return "forwardAccessSignalling"
	case 38:
		return "forwardCheckSS-Indication"
	case 7:
		return "insertSubscriberData"
	case 89:
		return "noteMM-Event"
	case 26:
		return "noteMsPresentForGprs"
	case 5:
		return "noteSubscriberDataModified"
	case 68:
		return "prepareHandover"
	case 69:
		return "prepareSubsequentHandover"
	case 33:
		return "processAccessSignalling"
	case 70:
		return "provideSubscriberInfo"
	case 67:
		return "purgeMS"
	case 37:
		return "reset"
	case 57:
		return "restoreData"
	case 56:
		return "sendAuthenticationInfo"
	case 29:
		return "sendEndSignal"
	case 55:
		return "sendIdentification"
	case 24:
		return "sendRoutingInfoForGprs"
	case 23:
		return "updateGprsLocation"
	case 2:
		return "updateLocation"
	case 53:
		return "updateVcsgLocation"
	case 50:
		return "activateTraceMode"
	case 51:
		return "deactivateTraceMode"
	case 58:
		return "sendIMSI"
	case 64:
		return "alertServiceCentre"
	case 63:
		return "informServiceCentre"
	case 46:
		return "mo-ForwardSM"
	case 44:
		return "mt-ForwardSM"
	case 21:
		return "mt-ForwardSM-VGCS"
	case 66:
		return "readyForSM"
	case 47:
		return "reportSM-DeliveryStatus"
	case 45:
		return "sendRoutingInfoForSM"
	case 12:
		return "activateSS"
	case 13:
		return "deactivateSS"
	case 77:
		return "eraseCC-Entry"
	case 11:
		return "eraseSS"
	case 18:
		return "getPassword"
	case 14:
		return "interrogateSS"
	case 59:
		return "processUnstructuredSS-Request"
	case 76:
		return "registerCC-Entry"
	case 17:
		return "registerPassword"
	case 10:
		return "registerSS"
	case 72:
		return "ss-InvocationNotification"
	case 61:
		return "unstructuredSS-Notify"
	case 60:
		return "unstructuredSS-Request"
	default:
		return fmt.Sprintf("OperationCode(%d)", int64(c))
	}
}
