// Code generated by asn1c-go from ASN.1 module "MAP-ApplicationContexts". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

var (

	// AnyTimeInfoEnquiryContextV3 is the OID value for anyTimeInfoEnquiryContext-v3.
	AnyTimeInfoEnquiryContextV3 = []uint64{0, 4, 0, 0, 1, 0, 29, 3}

	// AnyTimeInfoHandlingContextV3 is the OID value for anyTimeInfoHandlingContext-v3.
	AnyTimeInfoHandlingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 43, 3}

	// AuthenticationFailureReportContextV3 is the OID value for authenticationFailureReportContext-v3.
	AuthenticationFailureReportContextV3 = []uint64{0, 4, 0, 0, 1, 0, 39, 3}

	// CallCompletionContextV3 is the OID value for callCompletionContext-v3.
	CallCompletionContextV3 = []uint64{0, 4, 0, 0, 1, 0, 8, 3}

	// CallControlTransferContextV4 is the OID value for callControlTransferContext-v4.
	CallControlTransferContextV4 = []uint64{0, 4, 0, 0, 1, 0, 6, 4}

	// EquipmentMngtContextV3 is the OID value for equipmentMngtContext-v3.
	EquipmentMngtContextV3 = []uint64{0, 4, 0, 0, 1, 0, 13, 3}

	// FailureReportContextV3 is the OID value for failureReportContext-v3.
	FailureReportContextV3 = []uint64{0, 4, 0, 0, 1, 0, 34, 3}

	// GprsLocationInfoRetrievalContextV4 is the OID value for gprsLocationInfoRetrievalContext-v4.
	GprsLocationInfoRetrievalContextV4 = []uint64{0, 4, 0, 0, 1, 0, 33, 4}

	// GprsLocationUpdateContextV3 is the OID value for gprsLocationUpdateContext-v3.
	GprsLocationUpdateContextV3 = []uint64{0, 4, 0, 0, 1, 0, 32, 3}

	// GprsNotifyContextV3 is the OID value for gprsNotifyContext-v3.
	GprsNotifyContextV3 = []uint64{0, 4, 0, 0, 1, 0, 35, 3}

	// GroupCallControlContextV3 is the OID value for groupCallControlContext-v3.
	GroupCallControlContextV3 = []uint64{0, 4, 0, 0, 1, 0, 31, 3}

	// GroupCallInfoRetrievalContextV3 is the OID value for groupCallInfoRetrievalContext-v3.
	GroupCallInfoRetrievalContextV3 = []uint64{0, 4, 0, 0, 1, 0, 45, 3}

	// HandoverControlContextV3 is the OID value for handoverControlContext-v3.
	HandoverControlContextV3 = []uint64{0, 4, 0, 0, 1, 0, 11, 3}

	// ImsiRetrievalContextV2 is the OID value for imsiRetrievalContext-v2.
	ImsiRetrievalContextV2 = []uint64{0, 4, 0, 0, 1, 0, 26, 2}

	// InfoRetrievalContextV3 is the OID value for infoRetrievalContext-v3.
	InfoRetrievalContextV3 = []uint64{0, 4, 0, 0, 1, 0, 14, 3}

	// InterVlrInfoRetrievalContextV3 is the OID value for interVlrInfoRetrievalContext-v3.
	InterVlrInfoRetrievalContextV3 = []uint64{0, 4, 0, 0, 1, 0, 15, 3}

	// IstAlertingContextV3 is the OID value for istAlertingContext-v3.
	IstAlertingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 4, 3}

	// LocationCancellationContextV3 is the OID value for locationCancellationContext-v3.
	LocationCancellationContextV3 = []uint64{0, 4, 0, 0, 1, 0, 2, 3}

	// LocationInfoRetrievalContextV3 is the OID value for locationInfoRetrievalContext-v3.
	LocationInfoRetrievalContextV3 = []uint64{0, 4, 0, 0, 1, 0, 5, 3}

	// LocationSvcEnquiryContextV3 is the OID value for locationSvcEnquiryContext-v3.
	LocationSvcEnquiryContextV3 = []uint64{0, 4, 0, 0, 1, 0, 38, 3}

	// LocationSvcGatewayContextV3 is the OID value for locationSvcGatewayContext-v3.
	LocationSvcGatewayContextV3 = []uint64{0, 4, 0, 0, 1, 0, 37, 3}

	// MapAc is the OID value for map-ac.
	MapAc = []uint64{0, 4, 0, 0, 1, 0}

	// MmEventReportingContextV3 is the OID value for mm-EventReportingContext-v3.
	MmEventReportingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 42, 3}

	// MsPurgingContextV3 is the OID value for msPurgingContext-v3.
	MsPurgingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 27, 3}

	// MwdMngtContextV3 is the OID value for mwdMngtContext-v3.
	MwdMngtContextV3 = []uint64{0, 4, 0, 0, 1, 0, 24, 3}

	// NetworkFunctionalSsContextV2 is the OID value for networkFunctionalSsContext-v2.
	NetworkFunctionalSsContextV2 = []uint64{0, 4, 0, 0, 1, 0, 18, 2}

	// NetworkLocUpContextV3 is the OID value for networkLocUpContext-v3.
	NetworkLocUpContextV3 = []uint64{0, 4, 0, 0, 1, 0, 1, 3}

	// NetworkUnstructuredSsContextV2 is the OID value for networkUnstructuredSsContext-v2.
	NetworkUnstructuredSsContextV2 = []uint64{0, 4, 0, 0, 1, 0, 19, 2}

	// ReportingContextV3 is the OID value for reportingContext-v3.
	ReportingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 7, 3}

	// ResetContextV3 is the OID value for resetContext-v3.
	ResetContextV3 = []uint64{0, 4, 0, 0, 1, 0, 10, 3}

	// ResourceManagementContextV3 is the OID value for resourceManagementContext-v3.
	ResourceManagementContextV3 = []uint64{0, 4, 0, 0, 1, 0, 44, 3}

	// RoamingNumberEnquiryContextV3 is the OID value for roamingNumberEnquiryContext-v3.
	RoamingNumberEnquiryContextV3 = []uint64{0, 4, 0, 0, 1, 0, 3, 3}

	// ServiceTerminationContextV3 is the OID value for serviceTerminationContext-v3.
	ServiceTerminationContextV3 = []uint64{0, 4, 0, 0, 1, 0, 9, 3}

	// ShortMsgAlertContextV2 is the OID value for shortMsgAlertContext-v2.
	ShortMsgAlertContextV2 = []uint64{0, 4, 0, 0, 1, 0, 23, 2}

	// ShortMsgGatewayContextV3 is the OID value for shortMsgGatewayContext-v3.
	ShortMsgGatewayContextV3 = []uint64{0, 4, 0, 0, 1, 0, 20, 3}

	// ShortMsgMORelayContextV3 is the OID value for shortMsgMO-RelayContext-v3.
	ShortMsgMORelayContextV3 = []uint64{0, 4, 0, 0, 1, 0, 21, 3}

	// ShortMsgMTRelayContextV3 is the OID value for shortMsgMT-RelayContext-v3.
	ShortMsgMTRelayContextV3 = []uint64{0, 4, 0, 0, 1, 0, 25, 3}

	// ShortMsgMTRelayVGCSContextV3 is the OID value for shortMsgMT-Relay-VGCS-Context-v3.
	ShortMsgMTRelayVGCSContextV3 = []uint64{0, 4, 0, 0, 1, 0, 41, 3}

	// SsInvocationNotificationContextV3 is the OID value for ss-InvocationNotificationContext-v3.
	SsInvocationNotificationContextV3 = []uint64{0, 4, 0, 0, 1, 0, 36, 3}

	// SubscriberDataMngtContextV3 is the OID value for subscriberDataMngtContext-v3.
	SubscriberDataMngtContextV3 = []uint64{0, 4, 0, 0, 1, 0, 16, 3}

	// SubscriberDataModificationNotificationContextV3 is the OID value for subscriberDataModificationNotificationContext-v3.
	SubscriberDataModificationNotificationContextV3 = []uint64{0, 4, 0, 0, 1, 0, 22, 3}

	// SubscriberInfoEnquiryContextV3 is the OID value for subscriberInfoEnquiryContext-v3.
	SubscriberInfoEnquiryContextV3 = []uint64{0, 4, 0, 0, 1, 0, 28, 3}

	// TracingContextV3 is the OID value for tracingContext-v3.
	TracingContextV3 = []uint64{0, 4, 0, 0, 1, 0, 17, 3}

	// VcsgLocationCancellationContextV3 is the OID value for vcsgLocationCancellationContext-v3.
	VcsgLocationCancellationContextV3 = []uint64{0, 4, 0, 0, 1, 0, 47, 3}

	// VcsgLocationUpdateContextV3 is the OID value for vcsgLocationUpdateContext-v3.
	VcsgLocationUpdateContextV3 = []uint64{0, 4, 0, 0, 1, 0, 46, 3}
)
