// Code generated by asn1c-go from ASN.1 module "MAP-DialogueInformation". DO NOT EDIT.

package gsm_map

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// MapDialogueAS is the OID value for map-DialogueAS.
var MapDialogueAS = []uint64{0, 4, 0, 0, 1, 1, 1, 1}

// MAPAcceptInfo represents the ASN.1 type MAP-AcceptInfo (SEQUENCE).
type MAPAcceptInfo struct {
	ExtensionContainer *ExtensionContainer `asn1:",optional" json:"ExtensionContainer,omitempty"`
	ExtCount_          int64               `asn1:"-" json:"-"`
	ExtPresent_        []bool              `asn1:"-" json:"-"`
	ExtData_           [][]byte            `asn1:"-" json:"-"`
}

// MAPCloseInfo represents the ASN.1 type MAP-CloseInfo (SEQUENCE).
type MAPCloseInfo struct {
	ExtensionContainer *ExtensionContainer `asn1:",optional" json:"ExtensionContainer,omitempty"`
	ExtCount_          int64               `asn1:"-" json:"-"`
	ExtPresent_        []bool              `asn1:"-" json:"-"`
	ExtData_           [][]byte            `asn1:"-" json:"-"`
}

// MAPDialoguePDU choice constants.
const (
	MAPDialoguePDUChoiceMapOpen          = 1
	MAPDialoguePDUChoiceMapAccept        = 2
	MAPDialoguePDUChoiceMapClose         = 3
	MAPDialoguePDUChoiceMapRefuse        = 4
	MAPDialoguePDUChoiceMapUserAbort     = 5
	MAPDialoguePDUChoiceMapProviderAbort = 6
)

// MAPDialoguePDU represents the ASN.1 CHOICE type MAP-DialoguePDU.
type MAPDialoguePDU struct {
	Choice           int
	MapOpen          *MAPOpenInfo          `json:"MapOpen,omitempty"`
	MapAccept        *MAPAcceptInfo        `json:"MapAccept,omitempty"`
	MapClose         *MAPCloseInfo         `json:"MapClose,omitempty"`
	MapRefuse        *MAPRefuseInfo        `json:"MapRefuse,omitempty"`
	MapUserAbort     *MAPUserAbortInfo     `json:"MapUserAbort,omitempty"`
	MapProviderAbort *MAPProviderAbortInfo `json:"MapProviderAbort,omitempty"`
}

// NewMAPDialoguePDUMapOpen creates a MAP-DialoguePDU with the map-open alternative.
func NewMAPDialoguePDUMapOpen(v MAPOpenInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:  MAPDialoguePDUChoiceMapOpen,
		MapOpen: &v,
	}
}

// NewMAPDialoguePDUMapAccept creates a MAP-DialoguePDU with the map-accept alternative.
func NewMAPDialoguePDUMapAccept(v MAPAcceptInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:    MAPDialoguePDUChoiceMapAccept,
		MapAccept: &v,
	}
}

// NewMAPDialoguePDUMapClose creates a MAP-DialoguePDU with the map-close alternative.
func NewMAPDialoguePDUMapClose(v MAPCloseInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:   MAPDialoguePDUChoiceMapClose,
		MapClose: &v,
	}
}

// NewMAPDialoguePDUMapRefuse creates a MAP-DialoguePDU with the map-refuse alternative.
func NewMAPDialoguePDUMapRefuse(v MAPRefuseInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:    MAPDialoguePDUChoiceMapRefuse,
		MapRefuse: &v,
	}
}

// NewMAPDialoguePDUMapUserAbort creates a MAP-DialoguePDU with the map-userAbort alternative.
func NewMAPDialoguePDUMapUserAbort(v MAPUserAbortInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:       MAPDialoguePDUChoiceMapUserAbort,
		MapUserAbort: &v,
	}
}

// NewMAPDialoguePDUMapProviderAbort creates a MAP-DialoguePDU with the map-providerAbort alternative.
func NewMAPDialoguePDUMapProviderAbort(v MAPProviderAbortInfo) MAPDialoguePDU {
	return MAPDialoguePDU{
		Choice:           MAPDialoguePDUChoiceMapProviderAbort,
		MapProviderAbort: &v,
	}
}

// MAPOpenInfo represents the ASN.1 type MAP-OpenInfo (SEQUENCE).
type MAPOpenInfo struct {
	DestinationReference *AddressString      `asn1:"tag:0,context,implicit,optional" json:"DestinationReference,omitempty"`
	OriginationReference *AddressString      `asn1:"tag:1,context,implicit,optional" json:"OriginationReference,omitempty"`
	ExtensionContainer   *ExtensionContainer `asn1:",optional" json:"ExtensionContainer,omitempty"`
	ExtCount_            int64               `asn1:"-" json:"-"`
	ExtPresent_          []bool              `asn1:"-" json:"-"`
	ExtData_             [][]byte            `asn1:"-" json:"-"`
}

// MAPProviderAbortInfo represents the ASN.1 type MAP-ProviderAbortInfo (SEQUENCE).
type MAPProviderAbortInfo struct {
	MapProviderAbortReason MAPProviderAbortReason `asn1:""`
	ExtensionContainer     *ExtensionContainer    `asn1:",optional" json:"ExtensionContainer,omitempty"`
	ExtCount_              int64                  `asn1:"-" json:"-"`
	ExtPresent_            []bool                 `asn1:"-" json:"-"`
	ExtData_               [][]byte               `asn1:"-" json:"-"`
}

// MAPProviderAbortReason represents the ASN.1 ENUMERATED type MAP-ProviderAbortReason.
type MAPProviderAbortReason int64

const (
	MAPProviderAbortReasonAbnormalDialogue MAPProviderAbortReason = 0
	MAPProviderAbortReasonInvalidPDU       MAPProviderAbortReason = 1
)

func (v MAPProviderAbortReason) String() string {
	switch v {
	case MAPProviderAbortReasonAbnormalDialogue:
		return "abnormalDialogue"
	case MAPProviderAbortReasonInvalidPDU:
		return "invalidPDU"
	default:
		return "unknown"
	}
}

// MAPRefuseInfo represents the ASN.1 type MAP-RefuseInfo (SEQUENCE).
type MAPRefuseInfo struct {
	Reason                        Reason                   `asn1:""`
	ExtensionContainer            *ExtensionContainer      `asn1:",optional" json:"ExtensionContainer,omitempty"`
	AlternativeApplicationContext runtime.ObjectIdentifier `asn1:",optional" json:"AlternativeApplicationContext,omitempty"`
	ExtCount_                     int64                    `asn1:"-" json:"-"`
	ExtPresent_                   []bool                   `asn1:"-" json:"-"`
	ExtData_                      [][]byte                 `asn1:"-" json:"-"`
}

// MAPUserAbortChoice choice constants.
const (
	MAPUserAbortChoiceChoiceUserSpecificReason               = 1
	MAPUserAbortChoiceChoiceUserResourceLimitation           = 2
	MAPUserAbortChoiceChoiceResourceUnavailable              = 3
	MAPUserAbortChoiceChoiceApplicationProcedureCancellation = 4
)

// MAPUserAbortChoice represents the ASN.1 CHOICE type MAP-UserAbortChoice.
type MAPUserAbortChoice struct {
	Choice                           int
	UserSpecificReason               *struct{}                    `json:"UserSpecificReason,omitempty"`
	UserResourceLimitation           *struct{}                    `json:"UserResourceLimitation,omitempty"`
	ResourceUnavailable              *ResourceUnavailableReason   `json:"ResourceUnavailable,omitempty"`
	ApplicationProcedureCancellation *ProcedureCancellationReason `json:"ApplicationProcedureCancellation,omitempty"`
}

// NewMAPUserAbortChoiceUserSpecificReason creates a MAP-UserAbortChoice with the userSpecificReason alternative.
func NewMAPUserAbortChoiceUserSpecificReason(v struct{}) MAPUserAbortChoice {
	return MAPUserAbortChoice{
		Choice:             MAPUserAbortChoiceChoiceUserSpecificReason,
		UserSpecificReason: &v,
	}
}

// NewMAPUserAbortChoiceUserResourceLimitation creates a MAP-UserAbortChoice with the userResourceLimitation alternative.
func NewMAPUserAbortChoiceUserResourceLimitation(v struct{}) MAPUserAbortChoice {
	return MAPUserAbortChoice{
		Choice:                 MAPUserAbortChoiceChoiceUserResourceLimitation,
		UserResourceLimitation: &v,
	}
}

// NewMAPUserAbortChoiceResourceUnavailable creates a MAP-UserAbortChoice with the resourceUnavailable alternative.
func NewMAPUserAbortChoiceResourceUnavailable(v ResourceUnavailableReason) MAPUserAbortChoice {
	return MAPUserAbortChoice{
		Choice:              MAPUserAbortChoiceChoiceResourceUnavailable,
		ResourceUnavailable: &v,
	}
}

// NewMAPUserAbortChoiceApplicationProcedureCancellation creates a MAP-UserAbortChoice with the applicationProcedureCancellation alternative.
func NewMAPUserAbortChoiceApplicationProcedureCancellation(v ProcedureCancellationReason) MAPUserAbortChoice {
	return MAPUserAbortChoice{
		Choice:                           MAPUserAbortChoiceChoiceApplicationProcedureCancellation,
		ApplicationProcedureCancellation: &v,
	}
}

// MAPUserAbortInfo represents the ASN.1 type MAP-UserAbortInfo (SEQUENCE).
type MAPUserAbortInfo struct {
	MapUserAbortChoice MAPUserAbortChoice  `asn1:""`
	ExtensionContainer *ExtensionContainer `asn1:",optional" json:"ExtensionContainer,omitempty"`
	ExtCount_          int64               `asn1:"-" json:"-"`
	ExtPresent_        []bool              `asn1:"-" json:"-"`
	ExtData_           [][]byte            `asn1:"-" json:"-"`
}

// ProcedureCancellationReason represents the ASN.1 ENUMERATED type ProcedureCancellationReason.
type ProcedureCancellationReason int64

const (
	ProcedureCancellationReasonHandoverCancellation       ProcedureCancellationReason = 0
	ProcedureCancellationReasonRadioChannelRelease        ProcedureCancellationReason = 1
	ProcedureCancellationReasonNetworkPathRelease         ProcedureCancellationReason = 2
	ProcedureCancellationReasonCallRelease                ProcedureCancellationReason = 3
	ProcedureCancellationReasonAssociatedProcedureFailure ProcedureCancellationReason = 4
	ProcedureCancellationReasonTandemDialogueRelease      ProcedureCancellationReason = 5
	ProcedureCancellationReasonRemoteOperationsFailure    ProcedureCancellationReason = 6
)

func (v ProcedureCancellationReason) String() string {
	switch v {
	case ProcedureCancellationReasonHandoverCancellation:
		return "handoverCancellation"
	case ProcedureCancellationReasonRadioChannelRelease:
		return "radioChannelRelease"
	case ProcedureCancellationReasonNetworkPathRelease:
		return "networkPathRelease"
	case ProcedureCancellationReasonCallRelease:
		return "callRelease"
	case ProcedureCancellationReasonAssociatedProcedureFailure:
		return "associatedProcedureFailure"
	case ProcedureCancellationReasonTandemDialogueRelease:
		return "tandemDialogueRelease"
	case ProcedureCancellationReasonRemoteOperationsFailure:
		return "remoteOperationsFailure"
	default:
		return "unknown"
	}
}

// Reason represents the ASN.1 ENUMERATED type Reason.
type Reason int64

const (
	ReasonNoReasonGiven               Reason = 0
	ReasonInvalidDestinationReference Reason = 1
	ReasonInvalidOriginatingReference Reason = 2
)

func (v Reason) String() string {
	switch v {
	case ReasonNoReasonGiven:
		return "noReasonGiven"
	case ReasonInvalidDestinationReference:
		return "invalidDestinationReference"
	case ReasonInvalidOriginatingReference:
		return "invalidOriginatingReference"
	default:
		return "unknown"
	}
}

// ResourceUnavailableReason represents the ASN.1 ENUMERATED type ResourceUnavailableReason.
type ResourceUnavailableReason int64

const (
	ResourceUnavailableReasonShortTermResourceLimitation ResourceUnavailableReason = 0
	ResourceUnavailableReasonLongTermResourceLimitation  ResourceUnavailableReason = 1
)

func (v ResourceUnavailableReason) String() string {
	switch v {
	case ResourceUnavailableReasonShortTermResourceLimitation:
		return "shortTermResourceLimitation"
	case ResourceUnavailableReasonLongTermResourceLimitation:
		return "longTermResourceLimitation"
	default:
		return "unknown"
	}
}

// MarshalBER encodes MAPAcceptInfo to BER format.
func (v *MAPAcceptInfo) MarshalBER() ([]byte, error) {
	var children []byte
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPAcceptInfo to DER format.
func (v *MAPAcceptInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPAcceptInfo from BER/DER format.
func (v *MAPAcceptInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPAcceptInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	return nil
}

// MarshalBER encodes MAPCloseInfo to BER format.
func (v *MAPCloseInfo) MarshalBER() ([]byte, error) {
	var children []byte
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPCloseInfo to DER format.
func (v *MAPCloseInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPCloseInfo from BER/DER format.
func (v *MAPCloseInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPCloseInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	return nil
}

// MarshalBER encodes MAPDialoguePDU to BER format.
func (v *MAPDialoguePDU) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case MAPDialoguePDUChoiceMapOpen:
		if v.MapOpen == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-open is nil")
		}
		enc_0, err := v.MapOpen.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-open: %w", err)
		}
		enc_0 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 0, true, enc_0)
		return enc_0, nil
	case MAPDialoguePDUChoiceMapAccept:
		if v.MapAccept == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-accept is nil")
		}
		enc_1, err := v.MapAccept.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-accept: %w", err)
		}
		enc_1 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 1, true, enc_1)
		return enc_1, nil
	case MAPDialoguePDUChoiceMapClose:
		if v.MapClose == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-close is nil")
		}
		enc_2, err := v.MapClose.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-close: %w", err)
		}
		enc_2 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 2, true, enc_2)
		return enc_2, nil
	case MAPDialoguePDUChoiceMapRefuse:
		if v.MapRefuse == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-refuse is nil")
		}
		enc_3, err := v.MapRefuse.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-refuse: %w", err)
		}
		enc_3 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 3, true, enc_3)
		return enc_3, nil
	case MAPDialoguePDUChoiceMapUserAbort:
		if v.MapUserAbort == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-userAbort is nil")
		}
		enc_4, err := v.MapUserAbort.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-userAbort: %w", err)
		}
		enc_4 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 4, true, enc_4)
		return enc_4, nil
	case MAPDialoguePDUChoiceMapProviderAbort:
		if v.MapProviderAbort == nil {
			return nil, fmt.Errorf("choice MAPDialoguePDU: map-providerAbort is nil")
		}
		enc_5, err := v.MapProviderAbort.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding map-providerAbort: %w", err)
		}
		enc_5 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 5, true, enc_5)
		return enc_5, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for MAPDialoguePDU", v.Choice)
	}
}

// MarshalDER encodes MAPDialoguePDU to DER format.
func (v *MAPDialoguePDU) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPDialoguePDU from BER/DER format.
func (v *MAPDialoguePDU) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for MAPDialoguePDU CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for MAPDialoguePDU: %w", peekErr)
	}

	if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 0 {
		v.Choice = MAPDialoguePDUChoiceMapOpen
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-open: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPOpenInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-open: %w", unmErr)
		}
		v.MapOpen = &dec
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 1 {
		v.Choice = MAPDialoguePDUChoiceMapAccept
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-accept: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPAcceptInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-accept: %w", unmErr)
		}
		v.MapAccept = &dec
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 2 {
		v.Choice = MAPDialoguePDUChoiceMapClose
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-close: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPCloseInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-close: %w", unmErr)
		}
		v.MapClose = &dec
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 3 {
		v.Choice = MAPDialoguePDUChoiceMapRefuse
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-refuse: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPRefuseInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-refuse: %w", unmErr)
		}
		v.MapRefuse = &dec
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 4 {
		v.Choice = MAPDialoguePDUChoiceMapUserAbort
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-userAbort: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPUserAbortInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-userAbort: %w", unmErr)
		}
		v.MapUserAbort = &dec
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 5 {
		v.Choice = MAPDialoguePDUChoiceMapProviderAbort
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding map-providerAbort: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec MAPProviderAbortInfo
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding map-providerAbort: %w", unmErr)
		}
		v.MapProviderAbort = &dec
	} else {
		return fmt.Errorf("unknown tag %s for MAPDialoguePDU CHOICE", peekTag)
	}
	return nil
}

// MarshalBER encodes MAPOpenInfo to BER format.
func (v *MAPOpenInfo) MarshalBER() ([]byte, error) {
	var children []byte
	if v.DestinationReference != nil {
		enc_destinationreference := ber.EncodeOctetString([]byte(*v.DestinationReference))
		enc_destinationreference = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 0, false, enc_destinationreference)
		children = append(children, enc_destinationreference...)
	}
	if v.OriginationReference != nil {
		enc_originationreference := ber.EncodeOctetString([]byte(*v.OriginationReference))
		enc_originationreference = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 1, false, enc_originationreference)
		children = append(children, enc_originationreference...)
	}
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPOpenInfo to DER format.
func (v *MAPOpenInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPOpenInfo from BER/DER format.
func (v *MAPOpenInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPOpenInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode destinationReference
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 0 {
				_, n_destinationreference, rawVal_destinationreference, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding destinationReference: %w", err)
				}
				tmp_destinationreference := AddressString(rawVal_destinationreference)
				v.DestinationReference = &tmp_destinationreference
				offset += n_destinationreference
			}
		}
	}
	// Decode originationReference
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 1 {
				_, n_originationreference, rawVal_originationreference, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding originationReference: %w", err)
				}
				tmp_originationreference := AddressString(rawVal_originationreference)
				v.OriginationReference = &tmp_originationreference
				offset += n_originationreference
			}
		}
	}
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	return nil
}

// MarshalBER encodes MAPProviderAbortInfo to BER format.
func (v *MAPProviderAbortInfo) MarshalBER() ([]byte, error) {
	var children []byte
	enc_mapproviderabortreason := ber.EncodeEnumerated(int64(v.MapProviderAbortReason))
	children = append(children, enc_mapproviderabortreason...)
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPProviderAbortInfo to DER format.
func (v *MAPProviderAbortInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPProviderAbortInfo from BER/DER format.
func (v *MAPProviderAbortInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPProviderAbortInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode map-ProviderAbortReason
	if offset >= len(content) {
		return fmt.Errorf("missing required field map-ProviderAbortReason")
	}
	val_mapproviderabortreason, n, err := ber.DecodeInteger(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding map-ProviderAbortReason: %w", err)
	}
	v.MapProviderAbortReason = MAPProviderAbortReason(val_mapproviderabortreason)
	offset += n
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	return nil
}

// MarshalBER encodes MAPRefuseInfo to BER format.
func (v *MAPRefuseInfo) MarshalBER() ([]byte, error) {
	var children []byte
	enc_reason := ber.EncodeEnumerated(int64(v.Reason))
	children = append(children, enc_reason...)
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	if v.AlternativeApplicationContext != nil {
		enc_alternativeapplicationcontext := ber.EncodeObjectIdentifier([]uint64(v.AlternativeApplicationContext))
		children = append(children, enc_alternativeapplicationcontext...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPRefuseInfo to DER format.
func (v *MAPRefuseInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPRefuseInfo from BER/DER format.
func (v *MAPRefuseInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPRefuseInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode reason
	if offset >= len(content) {
		return fmt.Errorf("missing required field reason")
	}
	val_reason, n, err := ber.DecodeInteger(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding reason: %w", err)
	}
	v.Reason = Reason(val_reason)
	offset += n
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	// Decode alternativeApplicationContext
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 6 {
				val_alternativeapplicationcontext, n, err := ber.DecodeObjectIdentifier(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding alternativeApplicationContext: %w", err)
				}
				tmp_alternativeapplicationcontext := runtime.ObjectIdentifier(val_alternativeapplicationcontext)
				v.AlternativeApplicationContext = tmp_alternativeapplicationcontext
				offset += n
			}
		}
	}
	return nil
}

// MarshalBER encodes MAPUserAbortChoice to BER format.
func (v *MAPUserAbortChoice) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case MAPUserAbortChoiceChoiceUserSpecificReason:
		enc_0 := ber.EncodeNull()
		enc_0 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 0, false, enc_0)
		return enc_0, nil
	case MAPUserAbortChoiceChoiceUserResourceLimitation:
		enc_1 := ber.EncodeNull()
		enc_1 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 1, false, enc_1)
		return enc_1, nil
	case MAPUserAbortChoiceChoiceResourceUnavailable:
		enc_2 := ber.EncodeEnumerated(int64(*v.ResourceUnavailable))
		enc_2 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 2, false, enc_2)
		return enc_2, nil
	case MAPUserAbortChoiceChoiceApplicationProcedureCancellation:
		enc_3 := ber.EncodeEnumerated(int64(*v.ApplicationProcedureCancellation))
		enc_3 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 3, false, enc_3)
		return enc_3, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for MAPUserAbortChoice", v.Choice)
	}
}

// MarshalDER encodes MAPUserAbortChoice to DER format.
func (v *MAPUserAbortChoice) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPUserAbortChoice from BER/DER format.
func (v *MAPUserAbortChoice) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for MAPUserAbortChoice CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for MAPUserAbortChoice: %w", peekErr)
	}

	if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 0 {
		v.Choice = MAPUserAbortChoiceChoiceUserSpecificReason
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding userSpecificReason: %w", tlvErr)
		}
		_ = rawVal // NULL has no content
		v.UserSpecificReason = &struct{}{}
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 1 {
		v.Choice = MAPUserAbortChoiceChoiceUserResourceLimitation
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding userResourceLimitation: %w", tlvErr)
		}
		_ = rawVal // NULL has no content
		v.UserResourceLimitation = &struct{}{}
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 2 {
		v.Choice = MAPUserAbortChoiceChoiceResourceUnavailable
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding resourceUnavailable: %w", tlvErr)
		}
		decVal, intErr := ber.DecodeIntegerValue(rawVal)
		if intErr != nil {
			return fmt.Errorf("decoding resourceUnavailable: %w", intErr)
		}
		tmp := ResourceUnavailableReason(decVal)
		v.ResourceUnavailable = &tmp
	} else if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 3 {
		v.Choice = MAPUserAbortChoiceChoiceApplicationProcedureCancellation
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding applicationProcedureCancellation: %w", tlvErr)
		}
		decVal, intErr := ber.DecodeIntegerValue(rawVal)
		if intErr != nil {
			return fmt.Errorf("decoding applicationProcedureCancellation: %w", intErr)
		}
		tmp := ProcedureCancellationReason(decVal)
		v.ApplicationProcedureCancellation = &tmp
	} else {
		return fmt.Errorf("unknown tag %s for MAPUserAbortChoice CHOICE", peekTag)
	}
	return nil
}

// MarshalBER encodes MAPUserAbortInfo to BER format.
func (v *MAPUserAbortInfo) MarshalBER() ([]byte, error) {
	var children []byte
	enc_mapuserabortchoice, err := v.MapUserAbortChoice.MarshalBER()
	if err != nil {
		return nil, fmt.Errorf("encoding map-UserAbortChoice: %w", err)
	}
	children = append(children, enc_mapuserabortchoice...)
	if v.ExtensionContainer != nil {
		enc_extensioncontainer, err := v.ExtensionContainer.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding extensionContainer: %w", err)
		}
		children = append(children, enc_extensioncontainer...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes MAPUserAbortInfo to DER format.
func (v *MAPUserAbortInfo) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes MAPUserAbortInfo from BER/DER format.
func (v *MAPUserAbortInfo) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding MAPUserAbortInfo SEQUENCE: %w", err)
	}
	offset := 0
	// Decode map-UserAbortChoice
	if offset >= len(content) {
		return fmt.Errorf("missing required field map-UserAbortChoice")
	}
	// Decode nested CHOICE (MAPUserAbortChoice)
	_, n_mapuserabortchoice, _, tlvErr_mapuserabortchoice := ber.DecodeTLV(content[offset:])
	if tlvErr_mapuserabortchoice != nil {
		return fmt.Errorf("decoding map-UserAbortChoice: %w", tlvErr_mapuserabortchoice)
	}
	if unmErr := v.MapUserAbortChoice.UnmarshalBER(content[offset : offset+n_mapuserabortchoice]); unmErr != nil {
		return fmt.Errorf("decoding map-UserAbortChoice: %w", unmErr)
	}
	offset += n_mapuserabortchoice
	// Decode extensionContainer
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassUniversal && peekTag.Number == 16 {
				// Decode nested SEQUENCE (ExtensionContainer)
				_, n_extensioncontainer, _, tlvErr_extensioncontainer := ber.DecodeTLV(content[offset:])
				if tlvErr_extensioncontainer != nil {
					return fmt.Errorf("decoding extensionContainer: %w", tlvErr_extensioncontainer)
				}
				var dec_extensioncontainer ExtensionContainer
				if unmErr := dec_extensioncontainer.UnmarshalBER(content[offset : offset+n_extensioncontainer]); unmErr != nil {
					return fmt.Errorf("decoding extensionContainer: %w", unmErr)
				}
				v.ExtensionContainer = &dec_extensioncontainer
				offset += n_extensioncontainer
			}
		}
	}
	return nil
}
