// Code generated by asn1c-go from ASN.1 module "MAP-Errors". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// AbsentSubscriber is the integer constant for absentSubscriber.
	AbsentSubscriber int64 = 27

	// AbsentSubscriberSM is the integer constant for absentSubscriberSM.
	AbsentSubscriberSM int64 = 6

	// AtiNotAllowed is the integer constant for ati-NotAllowed.
	AtiNotAllowed int64 = 49

	// AtmNotAllowed is the integer constant for atm-NotAllowed.
	AtmNotAllowed int64 = 61

	// AtsiNotAllowed is the integer constant for atsi-NotAllowed.
	AtsiNotAllowed int64 = 60

	// BearerServiceNotProvisioned is the integer constant for bearerServiceNotProvisioned.
	BearerServiceNotProvisioned int64 = 10

	// BusySubscriber is the integer constant for busySubscriber.
	BusySubscriber int64 = 45

	// CallBarred is the integer constant for callBarred.
	CallBarred int64 = 13

	// CugReject is the integer constant for cug-Reject.
	CugReject int64 = 15

	// DataMissing is the integer constant for dataMissing.
	DataMissing int64 = 35

	// FacilityNotSupported is the integer constant for facilityNotSupported.
	FacilityNotSupported int64 = 21

	// ForwardingFailed is the integer constant for forwardingFailed.
	ForwardingFailed int64 = 47

	// ForwardingViolation is the integer constant for forwardingViolation.
	ForwardingViolation int64 = 14

	// IllegalEquipment is the integer constant for illegalEquipment.
	IllegalEquipment int64 = 12

	// IllegalSSOperation is the integer constant for illegalSS-Operation.
	IllegalSSOperation int64 = 16

	// IllegalSubscriber is the integer constant for illegalSubscriber.
	IllegalSubscriber int64 = 9

	// IncompatibleTerminal is the integer constant for incompatibleTerminal.
	IncompatibleTerminal int64 = 28

	// InformationNotAvailable is the integer constant for informationNotAvailable.
	InformationNotAvailable int64 = 62

	// LongTermDenial is the integer constant for longTermDenial.
	LongTermDenial int64 = 30

	// MessageWaitingListFull is the integer constant for messageWaitingListFull.
	MessageWaitingListFull int64 = 33

	// MmEventNotSupported is the integer constant for mm-EventNotSupported.
	MmEventNotSupported int64 = 59

	// NegativePWCheck is the integer constant for negativePW-Check.
	NegativePWCheck int64 = 38

	// NoGroupCallNumberAvailable is the integer constant for noGroupCallNumberAvailable.
	NoGroupCallNumberAvailable int64 = 50

	// NoHandoverNumberAvailable is the integer constant for noHandoverNumberAvailable.
	NoHandoverNumberAvailable int64 = 25

	// NoRoamingNumberAvailable is the integer constant for noRoamingNumberAvailable.
	NoRoamingNumberAvailable int64 = 39

	// NoSubscriberReply is the integer constant for noSubscriberReply.
	NoSubscriberReply int64 = 46

	// NumberChanged is the integer constant for numberChanged.
	NumberChanged int64 = 44

	// NumberOfPWAttemptsViolation is the integer constant for numberOfPW-AttemptsViolation.
	NumberOfPWAttemptsViolation int64 = 43

	// OngoingGroupCall is the integer constant for ongoingGroupCall.
	OngoingGroupCall int64 = 22

	// OrNotAllowed is the integer constant for or-NotAllowed.
	OrNotAllowed int64 = 48

	// PositionMethodFailure is the integer constant for positionMethodFailure.
	PositionMethodFailure int64 = 54

	// PwRegistrationFailure is the integer constant for pw-RegistrationFailure.
	PwRegistrationFailure int64 = 37

	// ResourceLimitation is the integer constant for resourceLimitation.
	ResourceLimitation int64 = 51

	// RoamingNotAllowed is the integer constant for roamingNotAllowed.
	RoamingNotAllowed int64 = 8

	// ShortTermDenial is the integer constant for shortTermDenial.
	ShortTermDenial int64 = 29

	// SmDeliveryFailure is the integer constant for sm-DeliveryFailure.
	SmDeliveryFailure int64 = 32

	// SsErrorStatus is the integer constant for ss-ErrorStatus.
	SsErrorStatus int64 = 17

	// SsIncompatibility is the integer constant for ss-Incompatibility.
	SsIncompatibility int64 = 20

	// SsNotAvailable is the integer constant for ss-NotAvailable.
	SsNotAvailable int64 = 18

	// SsSubscriptionViolation is the integer constant for ss-SubscriptionViolation.
	SsSubscriptionViolation int64 = 19

	// SubscriberBusyForMTSMS is the integer constant for subscriberBusyForMT-SMS.
	SubscriberBusyForMTSMS int64 = 31

	// SubsequentHandoverFailure is the integer constant for subsequentHandoverFailure.
	SubsequentHandoverFailure int64 = 26

	// SystemFailure is the integer constant for systemFailure.
	SystemFailure int64 = 34

	// TargetCellOutsideGroupCallArea is the integer constant for targetCellOutsideGroupCallArea.
	TargetCellOutsideGroupCallArea int64 = 42

	// TeleserviceNotProvisioned is the integer constant for teleserviceNotProvisioned.
	TeleserviceNotProvisioned int64 = 11

	// TracingBufferFull is the integer constant for tracingBufferFull.
	TracingBufferFull int64 = 40

	// UnauthorizedLCSClient is the integer constant for unauthorizedLCSClient.
	UnauthorizedLCSClient int64 = 53

	// UnauthorizedRequestingNetwork is the integer constant for unauthorizedRequestingNetwork.
	UnauthorizedRequestingNetwork int64 = 52

	// UnexpectedDataValue is the integer constant for unexpectedDataValue.
	UnexpectedDataValue int64 = 36

	// UnidentifiedSubscriber is the integer constant for unidentifiedSubscriber.
	UnidentifiedSubscriber int64 = 5

	// UnknownAlphabet is the integer constant for unknownAlphabet.
	UnknownAlphabet int64 = 71

	// UnknownEquipment is the integer constant for unknownEquipment.
	UnknownEquipment int64 = 7

	// UnknownMSC is the integer constant for unknownMSC.
	UnknownMSC int64 = 3

	// UnknownOrUnreachableLCSClient is the integer constant for unknownOrUnreachableLCSClient.
	UnknownOrUnreachableLCSClient int64 = 58

	// UnknownSubscriber is the integer constant for unknownSubscriber.
	UnknownSubscriber int64 = 1

	// UssdBusy is the integer constant for ussd-Busy.
	UssdBusy int64 = 72
)
