// Code generated by asn1c-go from ASN.1 module "MAP-Frame". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// ZZZZDummy represents the ASN.1 type ZZZZ-Dummy (NULL).
type ZZZZDummy = struct{}
