// Code generated by asn1c-go from ASN.1 module "MAP-Group-Call-Operations". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// ForwardGroupCallSignalling is the integer constant for forwardGroupCallSignalling.
	ForwardGroupCallSignalling int64 = 42

	// PrepareGroupCall is the integer constant for prepareGroupCall.
	PrepareGroupCall int64 = 39

	// ProcessGroupCallSignalling is the integer constant for processGroupCallSignalling.
	ProcessGroupCallSignalling int64 = 41

	// SendGroupCallEndSignal is the integer constant for sendGroupCallEndSignal.
	SendGroupCallEndSignal int64 = 40

	// SendGroupCallInfo is the integer constant for sendGroupCallInfo.
	SendGroupCallInfo int64 = 84
)
