// Code generated by asn1c-go from ASN.1 module "MAP-Group-Call-Operations". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// ForwardGroupCallSignalling is the integer value for forwardGroupCallSignalling.
const ForwardGroupCallSignalling int64 = 42

// PrepareGroupCall is the integer value for prepareGroupCall.
const PrepareGroupCall int64 = 39

// ProcessGroupCallSignalling is the integer value for processGroupCallSignalling.
const ProcessGroupCallSignalling int64 = 41

// SendGroupCallEndSignal is the integer value for sendGroupCallEndSignal.
const SendGroupCallEndSignal int64 = 40

// SendGroupCallInfo is the integer value for sendGroupCallInfo.
const SendGroupCallInfo int64 = 84
