// Code generated by asn1c-go from ASN.1 module "MAP-MobileServiceOperations". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// AnyTimeInterrogation is the integer constant for anyTimeInterrogation.
	AnyTimeInterrogation int64 = 71

	// AnyTimeModification is the integer constant for anyTimeModification.
	AnyTimeModification int64 = 65

	// AnyTimeSubscriptionInterrogation is the integer constant for anyTimeSubscriptionInterrogation.
	AnyTimeSubscriptionInterrogation int64 = 62

	// AuthenticationFailureReport is the integer constant for authenticationFailureReport.
	AuthenticationFailureReport int64 = 15

	// CancelLocation is the integer constant for cancelLocation.
	CancelLocation int64 = 3

	// CancelVcsgLocation is the integer constant for cancelVcsgLocation.
	CancelVcsgLocation int64 = 36

	// CheckIMEI is the integer constant for checkIMEI.
	CheckIMEI int64 = 43

	// DeleteSubscriberData is the integer constant for deleteSubscriberData.
	DeleteSubscriberData int64 = 8

	// FailureReport is the integer constant for failureReport.
	FailureReport int64 = 25

	// ForwardAccessSignalling is the integer constant for forwardAccessSignalling.
	ForwardAccessSignalling int64 = 34

	// ForwardCheckSSIndication is the integer constant for forwardCheckSS-Indication.
	ForwardCheckSSIndication int64 = 38

	// InsertSubscriberData is the integer constant for insertSubscriberData.
	InsertSubscriberData int64 = 7

	// NoteMMEvent is the integer constant for noteMM-Event.
	NoteMMEvent int64 = 89

	// NoteMsPresentForGprs is the integer constant for noteMsPresentForGprs.
	NoteMsPresentForGprs int64 = 26

	// NoteSubscriberDataModified is the integer constant for noteSubscriberDataModified.
	NoteSubscriberDataModified int64 = 5

	// PrepareHandover is the integer constant for prepareHandover.
	PrepareHandover int64 = 68

	// PrepareSubsequentHandover is the integer constant for prepareSubsequentHandover.
	PrepareSubsequentHandover int64 = 69

	// ProcessAccessSignalling is the integer constant for processAccessSignalling.
	ProcessAccessSignalling int64 = 33

	// ProvideSubscriberInfo is the integer constant for provideSubscriberInfo.
	ProvideSubscriberInfo int64 = 70

	// PurgeMS is the integer constant for purgeMS.
	PurgeMS int64 = 67

	// Reset is the integer constant for reset.
	Reset int64 = 37

	// RestoreData is the integer constant for restoreData.
	RestoreData int64 = 57

	// SendAuthenticationInfo is the integer constant for sendAuthenticationInfo.
	SendAuthenticationInfo int64 = 56

	// SendEndSignal is the integer constant for sendEndSignal.
	SendEndSignal int64 = 29

	// SendIdentification is the integer constant for sendIdentification.
	SendIdentification int64 = 55

	// SendRoutingInfoForGprs is the integer constant for sendRoutingInfoForGprs.
	SendRoutingInfoForGprs int64 = 24

	// UpdateGprsLocation is the integer constant for updateGprsLocation.
	UpdateGprsLocation int64 = 23

	// UpdateLocation is the integer constant for updateLocation.
	UpdateLocation int64 = 2

	// UpdateVcsgLocation is the integer constant for updateVcsgLocation.
	UpdateVcsgLocation int64 = 53
)
