// Code generated by asn1c-go from ASN.1 module "MAP-SupplementaryServiceOperations". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// ActivateSS is the integer constant for activateSS.
	ActivateSS int64 = 12

	// DeactivateSS is the integer constant for deactivateSS.
	DeactivateSS int64 = 13

	// EraseCCEntry is the integer constant for eraseCC-Entry.
	EraseCCEntry int64 = 77

	// EraseSS is the integer constant for eraseSS.
	EraseSS int64 = 11

	// GetPassword is the integer constant for getPassword.
	GetPassword int64 = 18

	// InterrogateSS is the integer constant for interrogateSS.
	InterrogateSS int64 = 14

	// ProcessUnstructuredSSRequest is the integer constant for processUnstructuredSS-Request.
	ProcessUnstructuredSSRequest int64 = 59

	// RegisterCCEntry is the integer constant for registerCC-Entry.
	RegisterCCEntry int64 = 76

	// RegisterPassword is the integer constant for registerPassword.
	RegisterPassword int64 = 17

	// RegisterSS is the integer constant for registerSS.
	RegisterSS int64 = 10

	// SsInvocationNotification is the integer constant for ss-InvocationNotification.
	SsInvocationNotification int64 = 72

	// UnstructuredSSNotify is the integer constant for unstructuredSS-Notify.
	UnstructuredSSNotify int64 = 61

	// UnstructuredSSRequest is the integer constant for unstructuredSS-Request.
	UnstructuredSSRequest int64 = 60
)
