// Code generated by asn1c-go from ASN.1 module "MAP-SS-Code". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// AllAdditionalInfoTransferSS is the octet string constant for allAdditionalInfoTransferSS.
	AllAdditionalInfoTransferSS = "\x80"

	// AllBarringSS is the octet string constant for allBarringSS.
	AllBarringSS = "\x90"

	// AllCallCompletionSS is the octet string constant for allCallCompletionSS.
	AllCallCompletionSS = "\x40"

	// AllCallOfferingSS is the octet string constant for allCallOfferingSS.
	AllCallOfferingSS = "\x30"

	// AllCallPrioritySS is the octet string constant for allCallPrioritySS.
	AllCallPrioritySS = "\xa0"

	// AllChargingSS is the octet string constant for allChargingSS.
	AllChargingSS = "\x70"

	// AllCommunityOfInterestSS is the octet string constant for allCommunityOfInterest-SS.
	AllCommunityOfInterestSS = "\x60"

	// AllCondForwardingSS is the octet string constant for allCondForwardingSS.
	AllCondForwardingSS = "\x28"

	// AllForwardingSS is the octet string constant for allForwardingSS.
	AllForwardingSS = "\x20"

	// AllLCSPrivacyException is the octet string constant for allLCSPrivacyException.
	AllLCSPrivacyException = "\xb0"

	// AllLineIdentificationSS is the octet string constant for allLineIdentificationSS.
	AllLineIdentificationSS = "\x10"

	// AllMOLRSS is the octet string constant for allMOLR-SS.
	AllMOLRSS = "\xc0"

	// AllMultiPartySS is the octet string constant for allMultiPartySS.
	AllMultiPartySS = "\x50"

	// AllNameIdentificationSS is the octet string constant for allNameIdentificationSS.
	AllNameIdentificationSS = "\x18"

	// AllPLMNSpecificSS is the octet string constant for allPLMN-specificSS.
	AllPLMNSpecificSS = "\xf0"

	// AllSS is the octet string constant for allSS.
	AllSS = "\x00"

	// Aocc is the octet string constant for aocc.
	Aocc = "\x72"

	// Aoci is the octet string constant for aoci.
	Aoci = "\x71"

	// AutonomousSelfLocation is the octet string constant for autonomousSelfLocation.
	AutonomousSelfLocation = "\xc2"

	// Baic is the octet string constant for baic.
	Baic = "\x9a"

	// Baoc is the octet string constant for baoc.
	Baoc = "\x92"

	// BarringOfIncomingCalls is the octet string constant for barringOfIncomingCalls.
	BarringOfIncomingCalls = "\x99"

	// BarringOfOutgoingCalls is the octet string constant for barringOfOutgoingCalls.
	BarringOfOutgoingCalls = "\x91"

	// BasicSelfLocation is the octet string constant for basicSelfLocation.
	BasicSelfLocation = "\xc1"

	// BicRoam is the octet string constant for bicRoam.
	BicRoam = "\x9b"

	// Boic is the octet string constant for boic.
	Boic = "\x93"

	// BoicExHC is the octet string constant for boicExHC.
	BoicExHC = "\x94"

	// CallSessionRelated is the octet string constant for callSessionRelated.
	CallSessionRelated = "\xb2"

	// CallSessionUnrelated is the octet string constant for callSessionUnrelated.
	CallSessionUnrelated = "\xb3"

	// CcbsA is the octet string constant for ccbs-A.
	CcbsA = "\x43"

	// CcbsB is the octet string constant for ccbs-B.
	CcbsB = "\x44"

	// Cd is the octet string constant for cd.
	Cd = "\x24"

	// Cfb is the octet string constant for cfb.
	Cfb = "\x29"

	// Cfnrc is the octet string constant for cfnrc.
	Cfnrc = "\x2b"

	// Cfnry is the octet string constant for cfnry.
	Cfnry = "\x2a"

	// Cfu is the octet string constant for cfu.
	Cfu = "\x21"

	// Clip is the octet string constant for clip.
	Clip = "\x11"

	// Clir is the octet string constant for clir.
	Clir = "\x12"

	// Cnap is the octet string constant for cnap.
	Cnap = "\x19"

	// Colp is the octet string constant for colp.
	Colp = "\x13"

	// Colr is the octet string constant for colr.
	Colr = "\x14"

	// Cug is the octet string constant for cug.
	Cug = "\x61"

	// Cw is the octet string constant for cw.
	Cw = "\x41"

	// Ect is the octet string constant for ect.
	Ect = "\x31"

	// Emlpp is the octet string constant for emlpp.
	Emlpp = "\xa1"

	// Hold is the octet string constant for hold.
	Hold = "\x42"

	// Mah is the octet string constant for mah.
	Mah = "\x32"

	// Mc is the octet string constant for mc.
	Mc = "\x45"

	// Mci is the octet string constant for mci.
	Mci = "\x15"

	// MultiPTY is the octet string constant for multiPTY.
	MultiPTY = "\x51"

	// PlmnSpecificSS1 is the octet string constant for plmn-specificSS-1.
	PlmnSpecificSS1 = "\xf1"

	// PlmnSpecificSS2 is the octet string constant for plmn-specificSS-2.
	PlmnSpecificSS2 = "\xf2"

	// PlmnSpecificSS3 is the octet string constant for plmn-specificSS-3.
	PlmnSpecificSS3 = "\xf3"

	// PlmnSpecificSS4 is the octet string constant for plmn-specificSS-4.
	PlmnSpecificSS4 = "\xf4"

	// PlmnSpecificSS5 is the octet string constant for plmn-specificSS-5.
	PlmnSpecificSS5 = "\xf5"

	// PlmnSpecificSS6 is the octet string constant for plmn-specificSS-6.
	PlmnSpecificSS6 = "\xf6"

	// PlmnSpecificSS7 is the octet string constant for plmn-specificSS-7.
	PlmnSpecificSS7 = "\xf7"

	// PlmnSpecificSS8 is the octet string constant for plmn-specificSS-8.
	PlmnSpecificSS8 = "\xf8"

	// PlmnSpecificSS9 is the octet string constant for plmn-specificSS-9.
	PlmnSpecificSS9 = "\xf9"

	// PlmnSpecificSSA is the octet string constant for plmn-specificSS-A.
	PlmnSpecificSSA = "\xfa"

	// PlmnSpecificSSB is the octet string constant for plmn-specificSS-B.
	PlmnSpecificSSB = "\xfb"

	// PlmnSpecificSSC is the octet string constant for plmn-specificSS-C.
	PlmnSpecificSSC = "\xfc"

	// PlmnSpecificSSD is the octet string constant for plmn-specificSS-D.
	PlmnSpecificSSD = "\xfd"

	// PlmnSpecificSSE is the octet string constant for plmn-specificSS-E.
	PlmnSpecificSSE = "\xfe"

	// PlmnSpecificSSF is the octet string constant for plmn-specificSS-F.
	PlmnSpecificSSF = "\xff"

	// Plmnoperator is the octet string constant for plmnoperator.
	Plmnoperator = "\xb4"

	// ServiceTypeValue is the octet string constant for serviceType.
	ServiceTypeValue = "\xb5"

	// TransferToThirdParty is the octet string constant for transferToThirdParty.
	TransferToThirdParty = "\xc3"

	// Universal is the octet string constant for universal.
	Universal = "\xb1"

	// Uus1 is the octet string constant for uus1.
	Uus1 = "\x81"

	// Uus2 is the octet string constant for uus2.
	Uus2 = "\x82"

	// Uus3 is the octet string constant for uus3.
	Uus3 = "\x83"
)

// SSCode represents the ASN.1 type SS-Code (OCTET_STRING).
type SSCode = []byte
