// Code generated by asn1c-go from ASN.1 module "MobileDomainDefinitions". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// AcId is the integer value for ac-Id.
const AcId int64 = 0

// AsId is the integer value for as-Id.
const AsId int64 = 1

// AseId is the integer value for ase-Id.
const AseId int64 = 2

// ErId is the integer value for er-Id.
const ErId int64 = 4

// GsmAccessId is the OID value for gsm-AccessId.
var GsmAccessId = []uint64{0, 4, 0, 0, 2}

// GsmMessagingId is the OID value for gsm-MessagingId.
var GsmMessagingId = []uint64{0, 4, 0, 0, 4}

// GsmNetworkId is the OID value for gsm-NetworkId.
var GsmNetworkId = []uint64{0, 4, 0, 0, 1}

// GsmOperationAndMaintenanceId is the OID value for gsm-OperationAndMaintenanceId.
var GsmOperationAndMaintenanceId = []uint64{0, 4, 0, 0, 3}

// MobileDomainId is the OID value for mobileDomainId.
var MobileDomainId = []uint64{0, 4, 0, 0}

// ModuleId is the integer value for moduleId.
const ModuleId int64 = 3

// CommonComponentId represents the ASN.1 type CommonComponentId (INTEGER).
type CommonComponentId = int64
