// Code generated by asn1c-go from ASN.1 module "MobileDomainDefinitions". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// AcId is the integer constant for ac-Id.
	AcId int64 = 0

	// AsId is the integer constant for as-Id.
	AsId int64 = 1

	// AseId is the integer constant for ase-Id.
	AseId int64 = 2

	// ErId is the integer constant for er-Id.
	ErId int64 = 4

	// ModuleId is the integer constant for moduleId.
	ModuleId int64 = 3
)

var (

	// GsmAccessId is the OID value for gsm-AccessId.
	GsmAccessId = []uint64{0, 4, 0, 0, 2}

	// GsmMessagingId is the OID value for gsm-MessagingId.
	GsmMessagingId = []uint64{0, 4, 0, 0, 4}

	// GsmNetworkId is the OID value for gsm-NetworkId.
	GsmNetworkId = []uint64{0, 4, 0, 0, 1}

	// GsmOperationAndMaintenanceId is the OID value for gsm-OperationAndMaintenanceId.
	GsmOperationAndMaintenanceId = []uint64{0, 4, 0, 0, 3}

	// MobileDomainId is the OID value for mobileDomainId.
	MobileDomainId = []uint64{0, 4, 0, 0}
)

// CommonComponentId represents the ASN.1 type CommonComponentId (INTEGER).
type CommonComponentId = int64
