// Code generated by asn1c-go from ASN.1 module "MobileDomainDefinitions". DO NOT EDIT.

package gsm_map

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

const (

	// AcId is the integer constant for ac-Id.
	AcId int64 = 0

	// AsId is the integer constant for as-Id.
	AsId int64 = 1

	// AseId is the integer constant for ase-Id.
	AseId int64 = 2

	// ErId is the integer constant for er-Id.
	ErId int64 = 4

	// ModuleId is the integer constant for moduleId.
	ModuleId int64 = 3
)

// GsmAccessId returns the OID value for gsm-AccessId.
func GsmAccessId() runtime.ObjectIdentifier { return runtime.ObjectIdentifier{0, 4, 0, 0, 2} }

// GsmMessagingId returns the OID value for gsm-MessagingId.
func GsmMessagingId() runtime.ObjectIdentifier { return runtime.ObjectIdentifier{0, 4, 0, 0, 4} }

// GsmNetworkId returns the OID value for gsm-NetworkId.
func GsmNetworkId() runtime.ObjectIdentifier { return runtime.ObjectIdentifier{0, 4, 0, 0, 1} }

// GsmOperationAndMaintenanceId returns the OID value for gsm-OperationAndMaintenanceId.
func GsmOperationAndMaintenanceId() runtime.ObjectIdentifier {
	return runtime.ObjectIdentifier{0, 4, 0, 0, 3}
}

// MobileDomainId returns the OID value for mobileDomainId.
func MobileDomainId() runtime.ObjectIdentifier { return runtime.ObjectIdentifier{0, 4, 0, 0} }

// CommonComponentId represents the ASN.1 type CommonComponentId (INTEGER).
type CommonComponentId = int64
