// Code generated by asn1c-go from ASN.1 module "S1AP-Constants". DO NOT EDIT.

package s1ap

import (
	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/per"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = per.NewBitBuffer
)

// IdAdditionalCSFallbackIndicator is the integer value for id-AdditionalCSFallbackIndicator.
const IdAdditionalCSFallbackIndicator int64 = 187

// IdAdditionalRRMPriorityIndex is the integer value for id-AdditionalRRMPriorityIndex.
const IdAdditionalRRMPriorityIndex int64 = 299

// IdAdditionalGUTI is the integer value for id-Additional-GUTI.
const IdAdditionalGUTI int64 = 224

// IdAerialUEsubscriptionInformation is the integer value for id-AerialUEsubscriptionInformation.
const IdAerialUEsubscriptionInformation int64 = 277

// IdAssistanceDataForPaging is the integer value for id-AssistanceDataForPaging.
const IdAssistanceDataForPaging int64 = 211

// IdBearerType is the integer value for id-BearerType.
const IdBearerType int64 = 233

// IdBearersSubjectToEarlyStatusTransferItem is the integer value for id-Bearers-SubjectToEarlyStatusTransfer-Item.
const IdBearersSubjectToEarlyStatusTransferItem int64 = 322

// IdBearersSubjectToStatusTransferItem is the integer value for id-Bearers-SubjectToStatusTransfer-Item.
const IdBearersSubjectToStatusTransferItem int64 = 89

// IdBluetoothMeasurementConfiguration is the integer value for id-BluetoothMeasurementConfiguration.
const IdBluetoothMeasurementConfiguration int64 = 284

// IdBroadcastCancelledAreaList is the integer value for id-BroadcastCancelledAreaList.
const IdBroadcastCancelledAreaList int64 = 141

// IdBroadcastCompletedAreaList is the integer value for id-BroadcastCompletedAreaList.
const IdBroadcastCompletedAreaList int64 = 120

// IdCEModeBRestricted is the integer value for id-CE-ModeBRestricted.
const IdCEModeBRestricted int64 = 271

// IdCEModeBSupportIndicator is the integer value for id-CE-mode-B-SupportIndicator.
const IdCEModeBSupportIndicator int64 = 242

// IdCNDomain is the integer value for id-CNDomain.
const IdCNDomain int64 = 109

// IdCNTypeRestrictions is the integer value for id-CNTypeRestrictions.
const IdCNTypeRestrictions int64 = 282

// IdCSFallbackIndicator is the integer value for id-CSFallbackIndicator.
const IdCSFallbackIndicator int64 = 108

// IdCSGMembershipInfo is the integer value for id-CSGMembershipInfo.
const IdCSGMembershipInfo int64 = 226

// IdCSGMembershipStatus is the integer value for id-CSGMembershipStatus.
const IdCSGMembershipStatus int64 = 146

// IdCSGId is the integer value for id-CSG-Id.
const IdCSGId int64 = 127

// IdCSGIdList is the integer value for id-CSG-IdList.
const IdCSGIdList int64 = 128

// IdCause is the integer value for id-Cause.
const IdCause int64 = 2

// IdCellAccessMode is the integer value for id-CellAccessMode.
const IdCellAccessMode int64 = 145

// IdCellIdentifierAndCELevelForCECapableUEs is the integer value for id-CellIdentifierAndCELevelForCECapableUEs.
const IdCellIdentifierAndCELevelForCECapableUEs int64 = 212

// IdCellTrafficTrace is the integer value for id-CellTrafficTrace.
const IdCellTrafficTrace int64 = 42

// IdConcurrentWarningMessageIndicator is the integer value for id-ConcurrentWarningMessageIndicator.
const IdConcurrentWarningMessageIndicator int64 = 142

// IdConnectedengNBList is the integer value for id-ConnectedengNBList.
const IdConnectedengNBList int64 = 291

// IdConnectedengNBToAddList is the integer value for id-ConnectedengNBToAddList.
const IdConnectedengNBToAddList int64 = 292

// IdConnectedengNBToRemoveList is the integer value for id-ConnectedengNBToRemoveList.
const IdConnectedengNBToRemoveList int64 = 293

// IdConnectionEstablishmentIndication is the integer value for id-ConnectionEstablishmentIndication.
const IdConnectionEstablishmentIndication int64 = 54

// IdContextatSource is the integer value for id-ContextatSource.
const IdContextatSource int64 = 300

// IdCorrelationID is the integer value for id-Correlation-ID.
const IdCorrelationID int64 = 156

// IdCoverageLevel is the integer value for id-Coverage-Level.
const IdCoverageLevel int64 = 250

// IdCriticalityDiagnostics is the integer value for id-CriticalityDiagnostics.
const IdCriticalityDiagnostics int64 = 58

// IdDAPSRequestInfo is the integer value for id-DAPSRequestInfo.
const IdDAPSRequestInfo int64 = 317

// IdDAPSResponseInfoItem is the integer value for id-DAPSResponseInfoItem.
const IdDAPSResponseInfoItem int64 = 319

// IdDAPSResponseInfoList is the integer value for id-DAPSResponseInfoList.
const IdDAPSResponseInfoList int64 = 318

// IdDCNID is the integer value for id-DCN-ID.
const IdDCNID int64 = 246

// IdDLCOUNTValueExtended is the integer value for id-DLCOUNTValueExtended.
const IdDLCOUNTValueExtended int64 = 180

// IdDLCOUNTValuePDCPSNlength18 is the integer value for id-DLCOUNTValuePDCP-SNlength18.
const IdDLCOUNTValuePDCPSNlength18 int64 = 218

// IdDLNASPDUDeliveryAckRequest is the integer value for id-DLNASPDUDeliveryAckRequest.
const IdDLNASPDUDeliveryAckRequest int64 = 249

// IdDLCPSecurityInformation is the integer value for id-DL-CP-SecurityInformation.
const IdDLCPSecurityInformation int64 = 253

// IdDataCodingScheme is the integer value for id-DataCodingScheme.
const IdDataCodingScheme int64 = 118

// IdDataSize is the integer value for id-DataSize.
const IdDataSize int64 = 304

// IdDataForwardingNotPossible is the integer value for id-Data-Forwarding-Not-Possible.
const IdDataForwardingNotPossible int64 = 143

// IdDeactivateTrace is the integer value for id-DeactivateTrace.
const IdDeactivateTrace int64 = 26

// IdDefaultPagingDRX is the integer value for id-DefaultPagingDRX.
const IdDefaultPagingDRX int64 = 137

// IdDirectForwardingPathAvailability is the integer value for id-Direct-Forwarding-Path-Availability.
const IdDirectForwardingPathAvailability int64 = 79

// IdDownlinkPacketLossRate is the integer value for id-DownlinkPacketLossRate.
const IdDownlinkPacketLossRate int64 = 273

// IdDownlinkS1cdma2000tunnelling is the integer value for id-DownlinkS1cdma2000tunnelling.
const IdDownlinkS1cdma2000tunnelling int64 = 19

// IdECGIListForRestart is the integer value for id-ECGIListForRestart.
const IdECGIListForRestart int64 = 182

// IdEDTSession is the integer value for id-EDT-Session.
const IdEDTSession int64 = 281

// IdENBConfigurationUpdate is the integer value for id-ENBConfigurationUpdate.
const IdENBConfigurationUpdate int64 = 29

// IdENDCSONConfigurationTransferECT is the integer value for id-EN-DCSONConfigurationTransfer-ECT.
const IdENDCSONConfigurationTransferECT int64 = 294

// IdENDCSONConfigurationTransferMCT is the integer value for id-EN-DCSONConfigurationTransfer-MCT.
const IdENDCSONConfigurationTransferMCT int64 = 295

// IdEUTRANRoundTripDelayEstimationInfo is the integer value for id-EUTRANRoundTripDelayEstimationInfo.
const IdEUTRANRoundTripDelayEstimationInfo int64 = 140

// IdEUTRANCGI is the integer value for id-EUTRAN-CGI.
const IdEUTRANCGI int64 = 100

// IdERABAdmittedItem is the integer value for id-E-RABAdmittedItem.
const IdERABAdmittedItem int64 = 20

// IdERABAdmittedList is the integer value for id-E-RABAdmittedList.
const IdERABAdmittedList int64 = 18

// IdERABDataForwardingItem is the integer value for id-E-RABDataForwardingItem.
const IdERABDataForwardingItem int64 = 14

// IdERABFailedToBeReleasedList is the integer value for id-E-RABFailedToBeReleasedList.
const IdERABFailedToBeReleasedList int64 = 103

// IdERABFailedToModifyList is the integer value for id-E-RABFailedToModifyList.
const IdERABFailedToModifyList int64 = 32

// IdERABFailedToModifyListBearerModConf is the integer value for id-E-RABFailedToModifyListBearerModConf.
const IdERABFailedToModifyListBearerModConf int64 = 205

// IdERABFailedToReleaseList is the integer value for id-E-RABFailedToReleaseList.
const IdERABFailedToReleaseList int64 = 34

// IdERABFailedToResumeItemResumeReq is the integer value for id-E-RABFailedToResumeItemResumeReq.
const IdERABFailedToResumeItemResumeReq int64 = 236

// IdERABFailedToResumeItemResumeRes is the integer value for id-E-RABFailedToResumeItemResumeRes.
const IdERABFailedToResumeItemResumeRes int64 = 238

// IdERABFailedToResumeListResumeReq is the integer value for id-E-RABFailedToResumeListResumeReq.
const IdERABFailedToResumeListResumeReq int64 = 235

// IdERABFailedToResumeListResumeRes is the integer value for id-E-RABFailedToResumeListResumeRes.
const IdERABFailedToResumeListResumeRes int64 = 237

// IdERABFailedToSetupListBearerSURes is the integer value for id-E-RABFailedToSetupListBearerSURes.
const IdERABFailedToSetupListBearerSURes int64 = 29

// IdERABFailedToSetupListCtxtSURes is the integer value for id-E-RABFailedToSetupListCtxtSURes.
const IdERABFailedToSetupListCtxtSURes int64 = 48

// IdERABFailedToSetupListHOReqAck is the integer value for id-E-RABFailedToSetupListHOReqAck.
const IdERABFailedToSetupListHOReqAck int64 = 19

// IdERABFailedtoSetupItemHOReqAck is the integer value for id-E-RABFailedtoSetupItemHOReqAck.
const IdERABFailedtoSetupItemHOReqAck int64 = 21

// IdERABInformationListItem is the integer value for id-E-RABInformationListItem.
const IdERABInformationListItem int64 = 78

// IdERABItem is the integer value for id-E-RABItem.
const IdERABItem int64 = 35

// IdERABModificationIndication is the integer value for id-E-RABModificationIndication.
const IdERABModificationIndication int64 = 50

// IdERABModify is the integer value for id-E-RABModify.
const IdERABModify int64 = 6

// IdERABModifyItemBearerModConf is the integer value for id-E-RABModifyItemBearerModConf.
const IdERABModifyItemBearerModConf int64 = 204

// IdERABModifyItemBearerModRes is the integer value for id-E-RABModifyItemBearerModRes.
const IdERABModifyItemBearerModRes int64 = 37

// IdERABModifyListBearerModConf is the integer value for id-E-RABModifyListBearerModConf.
const IdERABModifyListBearerModConf int64 = 203

// IdERABModifyListBearerModRes is the integer value for id-E-RABModifyListBearerModRes.
const IdERABModifyListBearerModRes int64 = 31

// IdERABNotToBeModifiedItemBearerModInd is the integer value for id-E-RABNotToBeModifiedItemBearerModInd.
const IdERABNotToBeModifiedItemBearerModInd int64 = 202

// IdERABNotToBeModifiedListBearerModInd is the integer value for id-E-RABNotToBeModifiedListBearerModInd.
const IdERABNotToBeModifiedListBearerModInd int64 = 201

// IdERABRelease is the integer value for id-E-RABRelease.
const IdERABRelease int64 = 7

// IdERABReleaseIndication is the integer value for id-E-RABReleaseIndication.
const IdERABReleaseIndication int64 = 8

// IdERABReleaseItem is the integer value for id-E-RABReleaseItem.
const IdERABReleaseItem int64 = 38

// IdERABReleaseItemBearerRelComp is the integer value for id-E-RABReleaseItemBearerRelComp.
const IdERABReleaseItemBearerRelComp int64 = 15

// IdERABReleaseItemHOCmd is the integer value for id-E-RABReleaseItemHOCmd.
const IdERABReleaseItemHOCmd int64 = 49

// IdERABReleaseListBearerRelComp is the integer value for id-E-RABReleaseListBearerRelComp.
const IdERABReleaseListBearerRelComp int64 = 69

// IdERABReleasedList is the integer value for id-E-RABReleasedList.
const IdERABReleasedList int64 = 110

// IdERABSecurityResultItem is the integer value for id-E-RABSecurityResultItem.
const IdERABSecurityResultItem int64 = 334

// IdERABSecurityResultList is the integer value for id-E-RABSecurityResultList.
const IdERABSecurityResultList int64 = 335

// IdERABSetup is the integer value for id-E-RABSetup.
const IdERABSetup int64 = 5

// IdERABSetupItemBearerSURes is the integer value for id-E-RABSetupItemBearerSURes.
const IdERABSetupItemBearerSURes int64 = 39

// IdERABSetupItemCtxtSURes is the integer value for id-E-RABSetupItemCtxtSURes.
const IdERABSetupItemCtxtSURes int64 = 50

// IdERABSetupListBearerSURes is the integer value for id-E-RABSetupListBearerSURes.
const IdERABSetupListBearerSURes int64 = 28

// IdERABSetupListCtxtSURes is the integer value for id-E-RABSetupListCtxtSURes.
const IdERABSetupListCtxtSURes int64 = 51

// IdERABSubjecttoDataForwardingList is the integer value for id-E-RABSubjecttoDataForwardingList.
const IdERABSubjecttoDataForwardingList int64 = 12

// IdERABToBeModifiedItemBearerModInd is the integer value for id-E-RABToBeModifiedItemBearerModInd.
const IdERABToBeModifiedItemBearerModInd int64 = 200

// IdERABToBeModifiedItemBearerModReq is the integer value for id-E-RABToBeModifiedItemBearerModReq.
const IdERABToBeModifiedItemBearerModReq int64 = 36

// IdERABToBeModifiedListBearerModInd is the integer value for id-E-RABToBeModifiedListBearerModInd.
const IdERABToBeModifiedListBearerModInd int64 = 199

// IdERABToBeModifiedListBearerModReq is the integer value for id-E-RABToBeModifiedListBearerModReq.
const IdERABToBeModifiedListBearerModReq int64 = 30

// IdERABToBeReleasedList is the integer value for id-E-RABToBeReleasedList.
const IdERABToBeReleasedList int64 = 33

// IdERABToBeReleasedListBearerModConf is the integer value for id-E-RABToBeReleasedListBearerModConf.
const IdERABToBeReleasedListBearerModConf int64 = 210

// IdERABToBeSetupItemBearerSUReq is the integer value for id-E-RABToBeSetupItemBearerSUReq.
const IdERABToBeSetupItemBearerSUReq int64 = 17

// IdERABToBeSetupItemCtxtSUReq is the integer value for id-E-RABToBeSetupItemCtxtSUReq.
const IdERABToBeSetupItemCtxtSUReq int64 = 52

// IdERABToBeSetupItemHOReq is the integer value for id-E-RABToBeSetupItemHOReq.
const IdERABToBeSetupItemHOReq int64 = 27

// IdERABToBeSetupListBearerSUReq is the integer value for id-E-RABToBeSetupListBearerSUReq.
const IdERABToBeSetupListBearerSUReq int64 = 16

// IdERABToBeSetupListCtxtSUReq is the integer value for id-E-RABToBeSetupListCtxtSUReq.
const IdERABToBeSetupListCtxtSUReq int64 = 24

// IdERABToBeSetupListHOReq is the integer value for id-E-RABToBeSetupListHOReq.
const IdERABToBeSetupListHOReq int64 = 53

// IdERABToBeSwitchedDLItem is the integer value for id-E-RABToBeSwitchedDLItem.
const IdERABToBeSwitchedDLItem int64 = 23

// IdERABToBeSwitchedDLList is the integer value for id-E-RABToBeSwitchedDLList.
const IdERABToBeSwitchedDLList int64 = 22

// IdERABToBeSwitchedULItem is the integer value for id-E-RABToBeSwitchedULItem.
const IdERABToBeSwitchedULItem int64 = 94

// IdERABToBeSwitchedULList is the integer value for id-E-RABToBeSwitchedULList.
const IdERABToBeSwitchedULList int64 = 95

// IdERABToBeUpdatedItem is the integer value for id-E-RABToBeUpdatedItem.
const IdERABToBeUpdatedItem int64 = 342

// IdERABToBeUpdatedList is the integer value for id-E-RABToBeUpdatedList.
const IdERABToBeUpdatedList int64 = 341

// IdERABUsageReportItem is the integer value for id-E-RABUsageReportItem.
const IdERABUsageReportItem int64 = 267

// IdERABtoReleaseListHOCmd is the integer value for id-E-RABtoReleaseListHOCmd.
const IdERABtoReleaseListHOCmd int64 = 13

// IdEUTRANTraceID is the integer value for id-E-UTRAN-Trace-ID.
const IdEUTRANTraceID int64 = 86

// IdEmergencyAreaIDListForRestart is the integer value for id-EmergencyAreaIDListForRestart.
const IdEmergencyAreaIDListForRestart int64 = 190

// IdEmergencyIndicator is the integer value for id-EmergencyIndicator.
const IdEmergencyIndicator int64 = 326

// IdEndIndication is the integer value for id-EndIndication.
const IdEndIndication int64 = 280

// IdEnhancedCoverageRestricted is the integer value for id-EnhancedCoverageRestricted.
const IdEnhancedCoverageRestricted int64 = 251

// IdErrorIndication is the integer value for id-ErrorIndication.
const IdErrorIndication int64 = 15

// IdEthernetType is the integer value for id-Ethernet-Type.
const IdEthernetType int64 = 305

// IdExpectedUEBehaviour is the integer value for id-ExpectedUEBehaviour.
const IdExpectedUEBehaviour int64 = 196

// IdExtendedRepetitionPeriod is the integer value for id-ExtendedRepetitionPeriod.
const IdExtendedRepetitionPeriod int64 = 144

// IdGERANtoLTEHOInformationRes is the integer value for id-GERANtoLTEHOInformationRes.
const IdGERANtoLTEHOInformationRes int64 = 55

// IdGUMMEIList is the integer value for id-GUMMEIList.
const IdGUMMEIList int64 = 154

// IdGUMMEIType is the integer value for id-GUMMEIType.
const IdGUMMEIType int64 = 170

// IdGUMMEIID is the integer value for id-GUMMEI-ID.
const IdGUMMEIID int64 = 75

// IdGWContextReleaseIndication is the integer value for id-GWContextReleaseIndication.
const IdGWContextReleaseIndication int64 = 164

// IdGWTransportLayerAddress is the integer value for id-GW-TransportLayerAddress.
const IdGWTransportLayerAddress int64 = 155

// IdGlobalENBID is the integer value for id-Global-ENB-ID.
const IdGlobalENBID int64 = 59

// IdHOCause is the integer value for id-HO-Cause.
const IdHOCause int64 = 168

// IdHandoverCancel is the integer value for id-HandoverCancel.
const IdHandoverCancel int64 = 4

// IdHandoverFlag is the integer value for id-HandoverFlag.
const IdHandoverFlag int64 = 266

// IdHandoverNotification is the integer value for id-HandoverNotification.
const IdHandoverNotification int64 = 2

// IdHandoverPreparation is the integer value for id-HandoverPreparation.
const IdHandoverPreparation int64 = 0

// IdHandoverResourceAllocation is the integer value for id-HandoverResourceAllocation.
const IdHandoverResourceAllocation int64 = 1

// IdHandoverRestrictionList is the integer value for id-HandoverRestrictionList.
const IdHandoverRestrictionList int64 = 41

// IdHandoverSuccess is the integer value for id-HandoverSuccess.
const IdHandoverSuccess int64 = 64

// IdHandoverType is the integer value for id-HandoverType.
const IdHandoverType int64 = 1

// IdIABAuthorized is the integer value for id-IAB-Authorized.
const IdIABAuthorized int64 = 301

// IdIABNodeIndication is the integer value for id-IAB-Node-Indication.
const IdIABNodeIndication int64 = 302

// IdIABSupported is the integer value for id-IAB-Supported.
const IdIABSupported int64 = 303

// IdIMSvoiceEPSfallbackfrom5G is the integer value for id-IMSvoiceEPSfallbackfrom5G.
const IdIMSvoiceEPSfallbackfrom5G int64 = 296

// IdInformationOnRecommendedCellsAndENBsForPaging is the integer value for id-InformationOnRecommendedCellsAndENBsForPaging.
const IdInformationOnRecommendedCellsAndENBsForPaging int64 = 213

// IdInitialContextSetup is the integer value for id-InitialContextSetup.
const IdInitialContextSetup int64 = 9

// IdInterSystemInformationTransferTypeEDT is the integer value for id-Inter-SystemInformationTransferTypeEDT.
const IdInterSystemInformationTransferTypeEDT int64 = 121

// IdInterSystemInformationTransferTypeMDT is the integer value for id-Inter-SystemInformationTransferTypeMDT.
const IdInterSystemInformationTransferTypeMDT int64 = 122

// IdIntersystemMeasurementConfiguration is the integer value for id-IntersystemMeasurementConfiguration.
const IdIntersystemMeasurementConfiguration int64 = 311

// IdIntersystemSONConfigurationTransferECT is the integer value for id-IntersystemSONConfigurationTransferECT.
const IdIntersystemSONConfigurationTransferECT int64 = 310

// IdIntersystemSONConfigurationTransferMCT is the integer value for id-IntersystemSONConfigurationTransferMCT.
const IdIntersystemSONConfigurationTransferMCT int64 = 309

// IdKill is the integer value for id-Kill.
const IdKill int64 = 43

// IdKillAllWarningMessages is the integer value for id-KillAllWarningMessages.
const IdKillAllWarningMessages int64 = 191

// IdLHNID is the integer value for id-LHN-ID.
const IdLHNID int64 = 186

// IdLPPaPDU is the integer value for id-LPPa-PDU.
const IdLPPaPDU int64 = 147

// IdLTEMIndication is the integer value for id-LTE-M-Indication.
const IdLTEMIndication int64 = 272

// IdLTENTNTAIInformation is the integer value for id-LTE-NTN-TAI-Information.
const IdLTENTNTAIInformation int64 = 339

// IdLastNGRANPLMNIdentity is the integer value for id-LastNG-RANPLMNIdentity.
const IdLastNGRANPLMNIdentity int64 = 290

// IdLocationReport is the integer value for id-LocationReport.
const IdLocationReport int64 = 33

// IdLocationReportingControl is the integer value for id-LocationReportingControl.
const IdLocationReportingControl int64 = 31

// IdLocationReportingFailureIndication is the integer value for id-LocationReportingFailureIndication.
const IdLocationReportingFailureIndication int64 = 32

// IdLoggedMBSFNMDT is the integer value for id-LoggedMBSFNMDT.
const IdLoggedMBSFNMDT int64 = 197

// IdLoggedMDTTrigger is the integer value for id-LoggedMDTTrigger.
const IdLoggedMDTTrigger int64 = 344

// IdM3Configuration is the integer value for id-M3Configuration.
const IdM3Configuration int64 = 171

// IdM4Configuration is the integer value for id-M4Configuration.
const IdM4Configuration int64 = 172

// IdM5Configuration is the integer value for id-M5Configuration.
const IdM5Configuration int64 = 173

// IdM6Configuration is the integer value for id-M6Configuration.
const IdM6Configuration int64 = 220

// IdM7Configuration is the integer value for id-M7Configuration.
const IdM7Configuration int64 = 221

// IdMDTConfiguration is the integer value for id-MDTConfiguration.
const IdMDTConfiguration int64 = 162

// IdMDTConfigurationNR is the integer value for id-MDTConfigurationNR.
const IdMDTConfigurationNR int64 = 316

// IdMDTLocationInfo is the integer value for id-MDT-Location-Info.
const IdMDTLocationInfo int64 = 174

// IdMMECPRelocationIndication is the integer value for id-MMECPRelocationIndication.
const IdMMECPRelocationIndication int64 = 61

// IdMMEConfigurationTransfer is the integer value for id-MMEConfigurationTransfer.
const IdMMEConfigurationTransfer int64 = 41

// IdMMEConfigurationUpdate is the integer value for id-MMEConfigurationUpdate.
const IdMMEConfigurationUpdate int64 = 30

// IdMMEDirectInformationTransfer is the integer value for id-MMEDirectInformationTransfer.
const IdMMEDirectInformationTransfer int64 = 38

// IdMMEEarlyStatusTransfer is the integer value for id-MMEEarlyStatusTransfer.
const IdMMEEarlyStatusTransfer int64 = 66

// IdMMERelaySupportIndicator is the integer value for id-MMERelaySupportIndicator.
const IdMMERelaySupportIndicator int64 = 163

// IdMMEStatusTransfer is the integer value for id-MMEStatusTransfer.
const IdMMEStatusTransfer int64 = 25

// IdMMEGroupID is the integer value for id-MME-Group-ID.
const IdMMEGroupID int64 = 223

// IdMMEUES1APID is the integer value for id-MME-UE-S1AP-ID.
const IdMMEUES1APID int64 = 0

// IdMMEUES1APID2 is the integer value for id-MME-UE-S1AP-ID-2.
const IdMMEUES1APID2 int64 = 158

// IdMMEname is the integer value for id-MMEname.
const IdMMEname int64 = 61

// IdMSClassmark2 is the integer value for id-MSClassmark2.
const IdMSClassmark2 int64 = 132

// IdMSClassmark3 is the integer value for id-MSClassmark3.
const IdMSClassmark3 int64 = 133

// IdManagementBasedMDTAllowed is the integer value for id-ManagementBasedMDTAllowed.
const IdManagementBasedMDTAllowed int64 = 165

// IdManagementBasedMDTPLMNList is the integer value for id-ManagementBasedMDTPLMNList.
const IdManagementBasedMDTPLMNList int64 = 177

// IdMaskedIMEISV is the integer value for id-Masked-IMEISV.
const IdMaskedIMEISV int64 = 192

// IdMessageIdentifier is the integer value for id-MessageIdentifier.
const IdMessageIdentifier int64 = 111

// IdMobilityInformation is the integer value for id-MobilityInformation.
const IdMobilityInformation int64 = 175

// IdMutingAvailabilityIndication is the integer value for id-Muting-Availability-Indication.
const IdMutingAvailabilityIndication int64 = 207

// IdMutingPatternInformation is the integer value for id-Muting-Pattern-Information.
const IdMutingPatternInformation int64 = 208

// IdNASDeliveryIndication is the integer value for id-NASDeliveryIndication.
const IdNASDeliveryIndication int64 = 57

// IdNASNonDeliveryIndication is the integer value for id-NASNonDeliveryIndication.
const IdNASNonDeliveryIndication int64 = 16

// IdNASSecurityParametersfromEUTRAN is the integer value for id-NASSecurityParametersfromE-UTRAN.
const IdNASSecurityParametersfromEUTRAN int64 = 135

// IdNASSecurityParameterstoEUTRAN is the integer value for id-NASSecurityParameterstoE-UTRAN.
const IdNASSecurityParameterstoEUTRAN int64 = 136

// IdNASDownlinkCount is the integer value for id-NAS-DownlinkCount.
const IdNASDownlinkCount int64 = 126

// IdNASPDU is the integer value for id-NAS-PDU.
const IdNASPDU int64 = 26

// IdNBIoTDefaultPagingDRX is the integer value for id-NB-IoT-DefaultPagingDRX.
const IdNBIoTDefaultPagingDRX int64 = 234

// IdNBIoTPagingDRX is the integer value for id-NB-IoT-PagingDRX.
const IdNBIoTPagingDRX int64 = 324

// IdNBIoTPagingEDRXInformation is the integer value for id-NB-IoT-Paging-eDRXInformation.
const IdNBIoTPagingEDRXInformation int64 = 239

// IdNBIoTRLFReportContainer is the integer value for id-NB-IoT-RLF-Report-Container.
const IdNBIoTRLFReportContainer int64 = 313

// IdNBIoTUEIdentityIndexValue is the integer value for id-NB-IoT-UEIdentityIndexValue.
const IdNBIoTUEIdentityIndexValue int64 = 244

// IdNRUESecurityCapabilities is the integer value for id-NRUESecurityCapabilities.
const IdNRUESecurityCapabilities int64 = 269

// IdNRUESidelinkAggregateMaximumBitrate is the integer value for id-NRUESidelinkAggregateMaximumBitrate.
const IdNRUESidelinkAggregateMaximumBitrate int64 = 307

// IdNRV2XServicesAuthorized is the integer value for id-NRV2XServicesAuthorized.
const IdNRV2XServicesAuthorized int64 = 306

// IdNRrestrictionin5GS is the integer value for id-NRrestrictionin5GS.
const IdNRrestrictionin5GS int64 = 287

// IdNRrestrictioninEPSasSecondaryRAT is the integer value for id-NRrestrictioninEPSasSecondaryRAT.
const IdNRrestrictioninEPSasSecondaryRAT int64 = 261

// IdNotifySourceeNB is the integer value for id-NotifySourceeNB.
const IdNotifySourceeNB int64 = 320

// IdNumberofBroadcastRequest is the integer value for id-NumberofBroadcastRequest.
const IdNumberofBroadcastRequest int64 = 115

// IdOverloadResponse is the integer value for id-OverloadResponse.
const IdOverloadResponse int64 = 101

// IdOverloadStart is the integer value for id-OverloadStart.
const IdOverloadStart int64 = 34

// IdOverloadStop is the integer value for id-OverloadStop.
const IdOverloadStop int64 = 35

// IdPC5QoSParameters is the integer value for id-PC5QoSParameters.
const IdPC5QoSParameters int64 = 308

// IdPSCellInformation is the integer value for id-PSCellInformation.
const IdPSCellInformation int64 = 288

// IdPSServiceNotAvailable is the integer value for id-PS-ServiceNotAvailable.
const IdPSServiceNotAvailable int64 = 150

// IdPWSFailureIndication is the integer value for id-PWSFailureIndication.
const IdPWSFailureIndication int64 = 51

// IdPWSRestartIndication is the integer value for id-PWSRestartIndication.
const IdPWSRestartIndication int64 = 49

// IdPWSfailedECGIList is the integer value for id-PWSfailedECGIList.
const IdPWSfailedECGIList int64 = 222

// IdPaging is the integer value for id-Paging.
const IdPaging int64 = 10

// IdPagingCause is the integer value for id-PagingCause.
const IdPagingCause int64 = 331

// IdPagingPriority is the integer value for id-PagingPriority.
const IdPagingPriority int64 = 151

// IdPagingEDRXInformation is the integer value for id-Paging-eDRXInformation.
const IdPagingEDRXInformation int64 = 227

// IdPathSwitchRequest is the integer value for id-PathSwitchRequest.
const IdPathSwitchRequest int64 = 3

// IdPendingDataIndication is the integer value for id-PendingDataIndication.
const IdPendingDataIndication int64 = 283

// IdPrivacyIndicator is the integer value for id-PrivacyIndicator.
const IdPrivacyIndicator int64 = 166

// IdPrivateMessage is the integer value for id-PrivateMessage.
const IdPrivateMessage int64 = 39

// IdProSeAuthorized is the integer value for id-ProSeAuthorized.
const IdProSeAuthorized int64 = 195

// IdProSeUEtoNetworkRelaying is the integer value for id-ProSeUEtoNetworkRelaying.
const IdProSeUEtoNetworkRelaying int64 = 216

// IdRACSIndication is the integer value for id-RACSIndication.
const IdRACSIndication int64 = 330

// IdRATRestrictions is the integer value for id-RAT-Restrictions.
const IdRATRestrictions int64 = 336

// IdRATType is the integer value for id-RAT-Type.
const IdRATType int64 = 232

// IdRRCEstablishmentCause is the integer value for id-RRC-Establishment-Cause.
const IdRRCEstablishmentCause int64 = 134

// IdRRCResumeCause is the integer value for id-RRC-Resume-Cause.
const IdRRCResumeCause int64 = 245

// IdReceiveStatusOfULPDCPSDUsExtended is the integer value for id-ReceiveStatusOfULPDCPSDUsExtended.
const IdReceiveStatusOfULPDCPSDUsExtended int64 = 181

// IdReceiveStatusOfULPDCPSDUsPDCPSNlength18 is the integer value for id-ReceiveStatusOfULPDCPSDUsPDCP-SNlength18.
const IdReceiveStatusOfULPDCPSDUsPDCPSNlength18 int64 = 219

// IdRecommendedCellItem is the integer value for id-RecommendedCellItem.
const IdRecommendedCellItem int64 = 214

// IdRecommendedENBItem is the integer value for id-RecommendedENBItem.
const IdRecommendedENBItem int64 = 215

// IdRegisteredLAI is the integer value for id-RegisteredLAI.
const IdRegisteredLAI int64 = 159

// IdRelativeMMECapacity is the integer value for id-RelativeMMECapacity.
const IdRelativeMMECapacity int64 = 87

// IdRelayNodeIndicator is the integer value for id-RelayNode-Indicator.
const IdRelayNodeIndicator int64 = 160

// IdRepetitionPeriod is the integer value for id-RepetitionPeriod.
const IdRepetitionPeriod int64 = 114

// IdRequestType is the integer value for id-RequestType.
const IdRequestType int64 = 98

// IdRequestTypeAdditionalInfo is the integer value for id-RequestTypeAdditionalInfo.
const IdRequestTypeAdditionalInfo int64 = 298

// IdRerouteNASRequest is the integer value for id-RerouteNASRequest.
const IdRerouteNASRequest int64 = 52

// IdReset is the integer value for id-Reset.
const IdReset int64 = 14

// IdResetType is the integer value for id-ResetType.
const IdResetType int64 = 92

// IdRetrieveUEInformation is the integer value for id-RetrieveUEInformation.
const IdRetrieveUEInformation int64 = 58

// IdRoutingID is the integer value for id-Routing-ID.
const IdRoutingID int64 = 148

// IdS1Setup is the integer value for id-S1Setup.
const IdS1Setup int64 = 17

// IdS1Message is the integer value for id-S1-Message.
const IdS1Message int64 = 225

// IdSIPTOCorrelationID is the integer value for id-SIPTO-Correlation-ID.
const IdSIPTOCorrelationID int64 = 183

// IdSIPTOLGWTransportLayerAddress is the integer value for id-SIPTO-L-GW-TransportLayerAddress.
const IdSIPTOLGWTransportLayerAddress int64 = 184

// IdSONConfigurationTransferECT is the integer value for id-SONConfigurationTransferECT.
const IdSONConfigurationTransferECT int64 = 129

// IdSONConfigurationTransferMCT is the integer value for id-SONConfigurationTransferMCT.
const IdSONConfigurationTransferMCT int64 = 130

// IdSONInformationReport is the integer value for id-SON-Information-Report.
const IdSONInformationReport int64 = 206

// IdSRVCCHOIndication is the integer value for id-SRVCCHOIndication.
const IdSRVCCHOIndication int64 = 125

// IdSRVCCOperationNotPossible is the integer value for id-SRVCCOperationNotPossible.
const IdSRVCCOperationNotPossible int64 = 243

// IdSRVCCOperationPossible is the integer value for id-SRVCCOperationPossible.
const IdSRVCCOperationPossible int64 = 124

// IdSTMSI is the integer value for id-S-TMSI.
const IdSTMSI int64 = 96

// IdSecondaryRATDataUsageReport is the integer value for id-SecondaryRATDataUsageReport.
const IdSecondaryRATDataUsageReport int64 = 62

// IdSecondaryRATDataUsageReportItem is the integer value for id-SecondaryRATDataUsageReportItem.
const IdSecondaryRATDataUsageReportItem int64 = 265

// IdSecondaryRATDataUsageReportList is the integer value for id-SecondaryRATDataUsageReportList.
const IdSecondaryRATDataUsageReportList int64 = 264

// IdSecondaryRATDataUsageRequest is the integer value for id-SecondaryRATDataUsageRequest.
const IdSecondaryRATDataUsageRequest int64 = 268

// IdSecurityContext is the integer value for id-SecurityContext.
const IdSecurityContext int64 = 40

// IdSecurityIndication is the integer value for id-SecurityIndication.
const IdSecurityIndication int64 = 332

// IdSecurityKey is the integer value for id-SecurityKey.
const IdSecurityKey int64 = 73

// IdSecurityResult is the integer value for id-SecurityResult.
const IdSecurityResult int64 = 333

// IdSensorMeasurementConfiguration is the integer value for id-SensorMeasurementConfiguration.
const IdSensorMeasurementConfiguration int64 = 345

// IdSerialNumber is the integer value for id-SerialNumber.
const IdSerialNumber int64 = 112

// IdServedDCNs is the integer value for id-ServedDCNs.
const IdServedDCNs int64 = 247

// IdServedGUMMEIs is the integer value for id-ServedGUMMEIs.
const IdServedGUMMEIs int64 = 105

// IdServedPLMNs is the integer value for id-ServedPLMNs.
const IdServedPLMNs int64 = 63

// IdSignallingBasedMDTPLMNList is the integer value for id-SignallingBasedMDTPLMNList.
const IdSignallingBasedMDTPLMNList int64 = 178

// IdSourceID is the integer value for id-SourceID.
const IdSourceID int64 = 3

// IdSourceMMEGUMMEI is the integer value for id-SourceMME-GUMMEI.
const IdSourceMMEGUMMEI int64 = 157

// IdSourceMMEUES1APID is the integer value for id-SourceMME-UE-S1AP-ID.
const IdSourceMMEUES1APID int64 = 88

// IdSourceNodeID is the integer value for id-SourceNodeID.
const IdSourceNodeID int64 = 312

// IdSourceNodeTransportLayerAddress is the integer value for id-SourceNodeTransportLayerAddress.
const IdSourceNodeTransportLayerAddress int64 = 340

// IdSourceSNID is the integer value for id-SourceSNID.
const IdSourceSNID int64 = 343

// IdSourceTransportLayerAddress is the integer value for id-SourceTransportLayerAddress.
const IdSourceTransportLayerAddress int64 = 328

// IdSourceToTargetTransparentContainer is the integer value for id-Source-ToTarget-TransparentContainer.
const IdSourceToTargetTransparentContainer int64 = 104

// IdSourceToTargetTransparentContainerSecondary is the integer value for id-Source-ToTarget-TransparentContainer-Secondary.
const IdSourceToTargetTransparentContainerSecondary int64 = 138

// IdSubscriberProfileIDforRFP is the integer value for id-SubscriberProfileIDforRFP.
const IdSubscriberProfileIDforRFP int64 = 106

// IdSubscriptionBasedUEDifferentiationInfo is the integer value for id-Subscription-Based-UE-DifferentiationInfo.
const IdSubscriptionBasedUEDifferentiationInfo int64 = 278

// IdSupportedTAs is the integer value for id-SupportedTAs.
const IdSupportedTAs int64 = 64

// IdSynchronisationInformation is the integer value for id-Synchronisation-Information.
const IdSynchronisationInformation int64 = 209

// IdTAI is the integer value for id-TAI.
const IdTAI int64 = 67

// IdTAIItem is the integer value for id-TAIItem.
const IdTAIItem int64 = 47

// IdTAIList is the integer value for id-TAIList.
const IdTAIList int64 = 46

// IdTAIListForRestart is the integer value for id-TAIListForRestart.
const IdTAIListForRestart int64 = 188

// IdTargetID is the integer value for id-TargetID.
const IdTargetID int64 = 4

// IdTargetToSourceTransparentContainer is the integer value for id-Target-ToSource-TransparentContainer.
const IdTargetToSourceTransparentContainer int64 = 123

// IdTargetToSourceTransparentContainerSecondary is the integer value for id-Target-ToSource-TransparentContainer-Secondary.
const IdTargetToSourceTransparentContainerSecondary int64 = 139

// IdTimeSinceSecondaryNodeRelease is the integer value for id-TimeSinceSecondaryNodeRelease.
const IdTimeSinceSecondaryNodeRelease int64 = 297

// IdTimeToWait is the integer value for id-TimeToWait.
const IdTimeToWait int64 = 65

// IdTimeSynchronisationInfo is the integer value for id-Time-Synchronisation-Info.
const IdTimeSynchronisationInfo int64 = 149

// IdTimeUEStayedInCellEnhancedGranularity is the integer value for id-Time-UE-StayedInCell-EnhancedGranularity.
const IdTimeUEStayedInCellEnhancedGranularity int64 = 167

// IdTraceActivation is the integer value for id-TraceActivation.
const IdTraceActivation int64 = 25

// IdTraceCollectionEntityIPAddress is the integer value for id-TraceCollectionEntityIPAddress.
const IdTraceCollectionEntityIPAddress int64 = 131

// IdTraceCollectionEntityURI is the integer value for id-TraceCollectionEntityURI.
const IdTraceCollectionEntityURI int64 = 325

// IdTraceFailureIndication is the integer value for id-TraceFailureIndication.
const IdTraceFailureIndication int64 = 28

// IdTraceStart is the integer value for id-TraceStart.
const IdTraceStart int64 = 27

// IdTrafficLoadReductionIndication is the integer value for id-TrafficLoadReductionIndication.
const IdTrafficLoadReductionIndication int64 = 161

// IdTransportInformation is the integer value for id-TransportInformation.
const IdTransportInformation int64 = 185

// IdTunnelInformationForBBF is the integer value for id-Tunnel-Information-for-BBF.
const IdTunnelInformationForBBF int64 = 176

// IdUEAppLayerMeasConfig is the integer value for id-UEAppLayerMeasConfig.
const IdUEAppLayerMeasConfig int64 = 262

// IdUECapabilityInfoIndication is the integer value for id-UECapabilityInfoIndication.
const IdUECapabilityInfoIndication int64 = 22

// IdUECapabilityInfoRequest is the integer value for id-UECapabilityInfoRequest.
const IdUECapabilityInfoRequest int64 = 275

// IdUEContextModification is the integer value for id-UEContextModification.
const IdUEContextModification int64 = 21

// IdUEContextModificationIndication is the integer value for id-UEContextModificationIndication.
const IdUEContextModificationIndication int64 = 53

// IdUEContextReferenceatSourceeNB is the integer value for id-UEContextReferenceatSourceeNB.
const IdUEContextReferenceatSourceeNB int64 = 337

// IdUEContextRelease is the integer value for id-UEContextRelease.
const IdUEContextRelease int64 = 23

// IdUEContextReleaseRequest is the integer value for id-UEContextReleaseRequest.
const IdUEContextReleaseRequest int64 = 18

// IdUEContextResume is the integer value for id-UEContextResume.
const IdUEContextResume int64 = 56

// IdUEContextSuspend is the integer value for id-UEContextSuspend.
const IdUEContextSuspend int64 = 55

// IdUEIdentityIndexValue is the integer value for id-UEIdentityIndexValue.
const IdUEIdentityIndexValue int64 = 80

// IdUEInformationTransfer is the integer value for id-UEInformationTransfer.
const IdUEInformationTransfer int64 = 59

// IdUEPagingID is the integer value for id-UEPagingID.
const IdUEPagingID int64 = 43

// IdUERadioCapability is the integer value for id-UERadioCapability.
const IdUERadioCapability int64 = 74

// IdUERadioCapabilityForPaging is the integer value for id-UERadioCapabilityForPaging.
const IdUERadioCapabilityForPaging int64 = 198

// IdUERadioCapabilityForPagingNRFormat is the integer value for id-UERadioCapabilityForPaging-NR-Format.
const IdUERadioCapabilityForPagingNRFormat int64 = 327

// IdUERadioCapabilityID is the integer value for id-UERadioCapabilityID.
const IdUERadioCapabilityID int64 = 314

// IdUERadioCapabilityIDMapping is the integer value for id-UERadioCapabilityIDMapping.
const IdUERadioCapabilityIDMapping int64 = 63

// IdUERadioCapabilityMatch is the integer value for id-UERadioCapabilityMatch.
const IdUERadioCapabilityMatch int64 = 48

// IdUERadioCapabilityNRFormat is the integer value for id-UERadioCapability-NR-Format.
const IdUERadioCapabilityNRFormat int64 = 315

// IdUESecurityCapabilities is the integer value for id-UESecurityCapabilities.
const IdUESecurityCapabilities int64 = 107

// IdUESidelinkAggregateMaximumBitrate is the integer value for id-UESidelinkAggregateMaximumBitrate.
const IdUESidelinkAggregateMaximumBitrate int64 = 248

// IdUEUserPlaneCIoTSupportIndicator is the integer value for id-UEUserPlaneCIoTSupportIndicator.
const IdUEUserPlaneCIoTSupportIndicator int64 = 241

// IdUEApplicationLayerMeasurementCapability is the integer value for id-UE-Application-Layer-Measurement-Capability.
const IdUEApplicationLayerMeasurementCapability int64 = 263

// IdUELevelQoSParameters is the integer value for id-UE-Level-QoS-Parameters.
const IdUELevelQoSParameters int64 = 252

// IdUERetentionInformation is the integer value for id-UE-RetentionInformation.
const IdUERetentionInformation int64 = 228

// IdUES1APIDs is the integer value for id-UE-S1AP-IDs.
const IdUES1APIDs int64 = 99

// IdUEUsageType is the integer value for id-UE-Usage-Type.
const IdUEUsageType int64 = 230

// IdUEAssociatedLogicalS1ConnectionItem is the integer value for id-UE-associatedLogicalS1-ConnectionItem.
const IdUEAssociatedLogicalS1ConnectionItem int64 = 91

// IdUEAssociatedLogicalS1ConnectionListResAck is the integer value for id-UE-associatedLogicalS1-ConnectionListResAck.
const IdUEAssociatedLogicalS1ConnectionListResAck int64 = 93

// IdULCOUNTValueExtended is the integer value for id-ULCOUNTValueExtended.
const IdULCOUNTValueExtended int64 = 179

// IdULCOUNTValuePDCPSNlength18 is the integer value for id-ULCOUNTValuePDCP-SNlength18.
const IdULCOUNTValuePDCPSNlength18 int64 = 217

// IdULCPSecurityInformation is the integer value for id-UL-CP-SecurityInformation.
const IdULCPSecurityInformation int64 = 254

// IdUTRANtoLTEHOInformationRes is the integer value for id-UTRANtoLTEHOInformationRes.
const IdUTRANtoLTEHOInformationRes int64 = 57

// IdUnlicensedSpectrumRestriction is the integer value for id-UnlicensedSpectrumRestriction.
const IdUnlicensedSpectrumRestriction int64 = 270

// IdUplinkPacketLossRate is the integer value for id-UplinkPacketLossRate.
const IdUplinkPacketLossRate int64 = 274

// IdUplinkS1cdma2000tunnelling is the integer value for id-UplinkS1cdma2000tunnelling.
const IdUplinkS1cdma2000tunnelling int64 = 20

// IdUserLocationInformation is the integer value for id-UserLocationInformation.
const IdUserLocationInformation int64 = 189

// IdV2XServicesAuthorized is the integer value for id-V2XServicesAuthorized.
const IdV2XServicesAuthorized int64 = 240

// IdVoiceSupportMatchIndicator is the integer value for id-VoiceSupportMatchIndicator.
const IdVoiceSupportMatchIndicator int64 = 169

// IdWLANMeasurementConfiguration is the integer value for id-WLANMeasurementConfiguration.
const IdWLANMeasurementConfiguration int64 = 285

// IdWUSAssistanceInformation is the integer value for id-WUS-Assistance-Information.
const IdWUSAssistanceInformation int64 = 323

// IdWarningAreaCoordinates is the integer value for id-WarningAreaCoordinates.
const IdWarningAreaCoordinates int64 = 286

// IdWarningAreaList is the integer value for id-WarningAreaList.
const IdWarningAreaList int64 = 113

// IdWarningMessageContents is the integer value for id-WarningMessageContents.
const IdWarningMessageContents int64 = 119

// IdWarningSecurityInfo is the integer value for id-WarningSecurityInfo.
const IdWarningSecurityInfo int64 = 117

// IdWarningType is the integer value for id-WarningType.
const IdWarningType int64 = 116

// IdWriteReplaceWarning is the integer value for id-WriteReplaceWarning.
const IdWriteReplaceWarning int64 = 36

// IdCdma2000HORequiredIndication is the integer value for id-cdma2000HORequiredIndication.
const IdCdma2000HORequiredIndication int64 = 84

// IdCdma2000HOStatus is the integer value for id-cdma2000HOStatus.
const IdCdma2000HOStatus int64 = 83

// IdCdma2000OneXRAND is the integer value for id-cdma2000OneXRAND.
const IdCdma2000OneXRAND int64 = 97

// IdCdma2000OneXSRVCCInfo is the integer value for id-cdma2000OneXSRVCCInfo.
const IdCdma2000OneXSRVCCInfo int64 = 102

// IdCdma2000PDU is the integer value for id-cdma2000PDU.
const IdCdma2000PDU int64 = 70

// IdCdma2000RATType is the integer value for id-cdma2000RATType.
const IdCdma2000RATType int64 = 71

// IdCdma2000SectorID is the integer value for id-cdma2000SectorID.
const IdCdma2000SectorID int64 = 72

// IdDownlinkNASTransport is the integer value for id-downlinkNASTransport.
const IdDownlinkNASTransport int64 = 11

// IdDownlinkNonUEAssociatedLPPaTransport is the integer value for id-downlinkNonUEAssociatedLPPaTransport.
const IdDownlinkNonUEAssociatedLPPaTransport int64 = 46

// IdDownlinkUEAssociatedLPPaTransport is the integer value for id-downlinkUEAssociatedLPPaTransport.
const IdDownlinkUEAssociatedLPPaTransport int64 = 44

// IdENBCPRelocationIndication is the integer value for id-eNBCPRelocationIndication.
const IdENBCPRelocationIndication int64 = 60

// IdENBConfigurationTransfer is the integer value for id-eNBConfigurationTransfer.
const IdENBConfigurationTransfer int64 = 40

// IdENBDirectInformationTransfer is the integer value for id-eNBDirectInformationTransfer.
const IdENBDirectInformationTransfer int64 = 37

// IdENBEarlyStatusTransfer is the integer value for id-eNBEarlyStatusTransfer.
const IdENBEarlyStatusTransfer int64 = 65

// IdENBIndirectX2TransportLayerAddresses is the integer value for id-eNBIndirectX2TransportLayerAddresses.
const IdENBIndirectX2TransportLayerAddresses int64 = 193

// IdENBStatusTransfer is the integer value for id-eNBStatusTransfer.
const IdENBStatusTransfer int64 = 24

// IdENBX2ExtendedTransportLayerAddresses is the integer value for id-eNBX2ExtendedTransportLayerAddresses.
const IdENBX2ExtendedTransportLayerAddresses int64 = 153

// IdENBEarlyStatusTransferTransparentContainer is the integer value for id-eNB-EarlyStatusTransfer-TransparentContainer.
const IdENBEarlyStatusTransferTransparentContainer int64 = 321

// IdENBStatusTransferTransparentContainer is the integer value for id-eNB-StatusTransfer-TransparentContainer.
const IdENBStatusTransferTransparentContainer int64 = 90

// IdENBUES1APID is the integer value for id-eNB-UE-S1AP-ID.
const IdENBUES1APID int64 = 8

// IdENBname is the integer value for id-eNBname.
const IdENBname int64 = 60

// IdExtendedUEIdentityIndexValue is the integer value for id-extended-UEIdentityIndexValue.
const IdExtendedUEIdentityIndexValue int64 = 231

// IdExtendedERABGuaranteedBitrateDL is the integer value for id-extended-e-RAB-GuaranteedBitrateDL.
const IdExtendedERABGuaranteedBitrateDL int64 = 257

// IdExtendedERABGuaranteedBitrateUL is the integer value for id-extended-e-RAB-GuaranteedBitrateUL.
const IdExtendedERABGuaranteedBitrateUL int64 = 258

// IdExtendedERABMaximumBitrateDL is the integer value for id-extended-e-RAB-MaximumBitrateDL.
const IdExtendedERABMaximumBitrateDL int64 = 255

// IdExtendedERABMaximumBitrateUL is the integer value for id-extended-e-RAB-MaximumBitrateUL.
const IdExtendedERABMaximumBitrateUL int64 = 256

// IdExtendedUEaggregateMaximumBitRateDL is the integer value for id-extended-uEaggregateMaximumBitRateDL.
const IdExtendedUEaggregateMaximumBitRateDL int64 = 259

// IdExtendedUEaggregateMaximumBitRateUL is the integer value for id-extended-uEaggregateMaximumBitRateUL.
const IdExtendedUEaggregateMaximumBitRateUL int64 = 260

// IdInitialUEMessage is the integer value for id-initialUEMessage.
const IdInitialUEMessage int64 = 12

// IdLastVisitedPSCellList is the integer value for id-lastVisitedPSCellList.
const IdLastVisitedPSCellList int64 = 329

// IdPagingDRX is the integer value for id-pagingDRX.
const IdPagingDRX int64 = 44

// IdServiceType is the integer value for id-serviceType.
const IdServiceType int64 = 276

// IdUEHistoryInformationFromTheUE is the integer value for id-uE-HistoryInformationFromTheUE.
const IdUEHistoryInformationFromTheUE int64 = 194

// IdUEaggregateMaximumBitrate is the integer value for id-uEaggregateMaximumBitrate.
const IdUEaggregateMaximumBitrate int64 = 66

// IdUplinkNASTransport is the integer value for id-uplinkNASTransport.
const IdUplinkNASTransport int64 = 13

// IdUplinkNonUEAssociatedLPPaTransport is the integer value for id-uplinkNonUEAssociatedLPPaTransport.
const IdUplinkNonUEAssociatedLPPaTransport int64 = 47

// IdUplinkUEAssociatedLPPaTransport is the integer value for id-uplinkUEAssociatedLPPaTransport.
const IdUplinkUEAssociatedLPPaTransport int64 = 45

// IdX2TNLConfigurationInfo is the integer value for id-x2TNLConfigurationInfo.
const IdX2TNLConfigurationInfo int64 = 152

// MaxEARFCN is the integer value for maxEARFCN.
const MaxEARFCN int64 = 262143

// MaxNARFCN is the integer value for maxNARFCN.
const MaxNARFCN int64 = 3.279165e+06

// MaxPrivateIEs is the integer value for maxPrivateIEs.
const MaxPrivateIEs int64 = 65535

// MaxProtocolExtensions is the integer value for maxProtocolExtensions.
const MaxProtocolExtensions int64 = 65535

// MaxProtocolIEs is the integer value for maxProtocolIEs.
const MaxProtocolIEs int64 = 65535

// MaxRSIndexCellQual is the integer value for maxRS-IndexCellQual.
const MaxRSIndexCellQual int64 = 16

// MaxnoofBPLMNs is the integer value for maxnoofBPLMNs.
const MaxnoofBPLMNs int64 = 6

// MaxnoofBluetoothName is the integer value for maxnoofBluetoothName.
const MaxnoofBluetoothName int64 = 4

// MaxnoofCSGs is the integer value for maxnoofCSGs.
const MaxnoofCSGs int64 = 256

// MaxnoofCellID is the integer value for maxnoofCellID.
const MaxnoofCellID int64 = 65535

// MaxnoofCellIDforMDT is the integer value for maxnoofCellIDforMDT.
const MaxnoofCellIDforMDT int64 = 32

// MaxnoofCellIDforQMC is the integer value for maxnoofCellIDforQMC.
const MaxnoofCellIDforQMC int64 = 32

// MaxnoofCellinEAI is the integer value for maxnoofCellinEAI.
const MaxnoofCellinEAI int64 = 65535

// MaxnoofCellinTAI is the integer value for maxnoofCellinTAI.
const MaxnoofCellinTAI int64 = 65535

// MaxnoofCellsforRestart is the integer value for maxnoofCellsforRestart.
const MaxnoofCellsforRestart int64 = 256

// MaxnoofCellsinUEHistoryInfo is the integer value for maxnoofCellsinUEHistoryInfo.
const MaxnoofCellsinUEHistoryInfo int64 = 16

// MaxnoofCellsineNB is the integer value for maxnoofCellsineNB.
const MaxnoofCellsineNB int64 = 256

// MaxnoofConnectedengNBs is the integer value for maxnoofConnectedengNBs.
const MaxnoofConnectedengNBs int64 = 256

// MaxnoofDCNs is the integer value for maxnoofDCNs.
const MaxnoofDCNs int64 = 32

// MaxnoofEPLMNs is the integer value for maxnoofEPLMNs.
const MaxnoofEPLMNs int64 = 15

// MaxnoofEPLMNsPlusOne is the integer value for maxnoofEPLMNsPlusOne.
const MaxnoofEPLMNsPlusOne int64 = 16

// MaxnoofERABs is the integer value for maxnoofE-RABs.
const MaxnoofERABs int64 = 256

// MaxnoofEmergencyAreaID is the integer value for maxnoofEmergencyAreaID.
const MaxnoofEmergencyAreaID int64 = 65535

// MaxnoofErrors is the integer value for maxnoofErrors.
const MaxnoofErrors int64 = 256

// MaxnoofForbLACs is the integer value for maxnoofForbLACs.
const MaxnoofForbLACs int64 = 4096

// MaxnoofForbTACs is the integer value for maxnoofForbTACs.
const MaxnoofForbTACs int64 = 4096

// MaxnoofGroupIDs is the integer value for maxnoofGroupIDs.
const MaxnoofGroupIDs int64 = 65535

// MaxnoofIndividualS1ConnectionsToReset is the integer value for maxnoofIndividualS1ConnectionsToReset.
const MaxnoofIndividualS1ConnectionsToReset int64 = 256

// MaxnoofMBSFNAreaMDT is the integer value for maxnoofMBSFNAreaMDT.
const MaxnoofMBSFNAreaMDT int64 = 8

// MaxnoofMDTPLMNs is the integer value for maxnoofMDTPLMNs.
const MaxnoofMDTPLMNs int64 = 16

// MaxnoofMMECs is the integer value for maxnoofMMECs.
const MaxnoofMMECs int64 = 256

// MaxnoofPC5QoSFlows is the integer value for maxnoofPC5QoSFlows.
const MaxnoofPC5QoSFlows int64 = 2048

// MaxnoofPLMNforQMC is the integer value for maxnoofPLMNforQMC.
const MaxnoofPLMNforQMC int64 = 16

// MaxnoofPLMNsPerMME is the integer value for maxnoofPLMNsPerMME.
const MaxnoofPLMNsPerMME int64 = 32

// MaxnoofPSCellsPerPrimaryCellinUEHistoryInfo is the integer value for maxnoofPSCellsPerPrimaryCellinUEHistoryInfo.
const MaxnoofPSCellsPerPrimaryCellinUEHistoryInfo int64 = 8

// MaxnoofRATs is the integer value for maxnoofRATs.
const MaxnoofRATs int64 = 8

// MaxnoofRecommendedCells is the integer value for maxnoofRecommendedCells.
const MaxnoofRecommendedCells int64 = 16

// MaxnoofRecommendedENBs is the integer value for maxnoofRecommendedENBs.
const MaxnoofRecommendedENBs int64 = 16

// MaxnoofRestartEmergencyAreaIDs is the integer value for maxnoofRestartEmergencyAreaIDs.
const MaxnoofRestartEmergencyAreaIDs int64 = 256

// MaxnoofRestartTAIs is the integer value for maxnoofRestartTAIs.
const MaxnoofRestartTAIs int64 = 2048

// MaxnoofSensorName is the integer value for maxnoofSensorName.
const MaxnoofSensorName int64 = 3

// MaxnoofTACs is the integer value for maxnoofTACs.
const MaxnoofTACs int64 = 256

// MaxnoofTACsInNTN is the integer value for maxnoofTACsInNTN.
const MaxnoofTACsInNTN int64 = 12

// MaxnoofTAIforWarning is the integer value for maxnoofTAIforWarning.
const MaxnoofTAIforWarning int64 = 65535

// MaxnoofTAIs is the integer value for maxnoofTAIs.
const MaxnoofTAIs int64 = 256

// MaxnoofTAforMDT is the integer value for maxnoofTAforMDT.
const MaxnoofTAforMDT int64 = 8

// MaxnoofTAforQMC is the integer value for maxnoofTAforQMC.
const MaxnoofTAforQMC int64 = 8

// MaxnoofWLANName is the integer value for maxnoofWLANName.
const MaxnoofWLANName int64 = 4

// MaxnoofeNBX2ExtTLAs is the integer value for maxnoofeNBX2ExtTLAs.
const MaxnoofeNBX2ExtTLAs int64 = 16

// MaxnoofeNBX2GTPTLAs is the integer value for maxnoofeNBX2GTPTLAs.
const MaxnoofeNBX2GTPTLAs int64 = 16

// MaxnoofeNBX2TLAs is the integer value for maxnoofeNBX2TLAs.
const MaxnoofeNBX2TLAs int64 = 2

// Maxnooffrequencies is the integer value for maxnooffrequencies.
const Maxnooffrequencies int64 = 64

// Maxnooftimeperiods is the integer value for maxnooftimeperiods.
const Maxnooftimeperiods int64 = 2
