// Code generated by asn1c-go. DO NOT EDIT.

package tcap

import "fmt"

// ErrorCode is a typed alias for MAP error codes.
type ErrorCode int64

const (
	// Refuse is the error code for refuse.
	Refuse ErrorCode = -1
)

// String returns the ASN.1 name of the error code.
func (c ErrorCode) String() string {
	switch c {
	case -1:
		return "refuse"
	default:
		return fmt.Sprintf("ErrorCode(%d)", int64(c))
	}
}
