// Code generated by asn1c-go from ASN.1 module "TCAPMessages". DO NOT EDIT.

package tcap

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// Abort represents the ASN.1 type Abort (SEQUENCE).
type Abort struct {
	Dtid   DestTransactionID `asn1:""`
	Reason *AbortReason      `asn1:",optional" json:"Reason,omitempty"`
}

// Begin represents the ASN.1 type Begin (SEQUENCE).
type Begin struct {
	Otid             OrigTransactionID `asn1:""`
	DialoguePortion  *DialoguePortion  `asn1:",optional" json:"DialoguePortion,omitempty"`
	Components       ComponentPortion  `asn1:",optional" json:"Components,omitempty"`
	ComponentsIndef_ bool              `asn1:"-" json:"-"`
}

// Component choice constants.
const (
	ComponentChoiceBasicROS            = 1
	ComponentChoiceReturnResultNotLast = 2
)

// Component represents the ASN.1 CHOICE type Component.
type Component struct {
	Choice              int
	BasicROS            *ROS `json:"BasicROS,omitempty"`
	ReturnResultNotLast *ROS `json:"ReturnResultNotLast,omitempty"`
}

// NewComponentBasicROS creates a Component with the basicROS alternative.
func NewComponentBasicROS(v ROS) Component {
	return Component{
		Choice:   ComponentChoiceBasicROS,
		BasicROS: &v,
	}
}

// NewComponentReturnResultNotLast creates a Component with the returnResultNotLast alternative.
func NewComponentReturnResultNotLast(v ROS) Component {
	return Component{
		Choice:              ComponentChoiceReturnResultNotLast,
		ReturnResultNotLast: &v,
	}
}

// ComponentPortion represents the ASN.1 type ComponentPortion (SEQUENCE_OF).
type ComponentPortion = []Component

// Continue represents the ASN.1 type Continue (SEQUENCE).
type Continue struct {
	Otid             OrigTransactionID `asn1:""`
	Dtid             DestTransactionID `asn1:""`
	DialoguePortion  *DialoguePortion  `asn1:",optional" json:"DialoguePortion,omitempty"`
	Components       ComponentPortion  `asn1:",optional" json:"Components,omitempty"`
	ComponentsIndef_ bool              `asn1:"-" json:"-"`
}

// DestTransactionID represents the ASN.1 type DestTransactionID (OCTET_STRING).
type DestTransactionID = []byte

// DialoguePortion represents the ASN.1 type DialoguePortion (EXTERNAL).
type DialoguePortion = runtime.RawValue

// End represents the ASN.1 type End (SEQUENCE).
type End struct {
	Dtid             DestTransactionID `asn1:""`
	DialoguePortion  *DialoguePortion  `asn1:",optional" json:"DialoguePortion,omitempty"`
	Components       ComponentPortion  `asn1:",optional" json:"Components,omitempty"`
	ComponentsIndef_ bool              `asn1:"-" json:"-"`
}

// OrigTransactionID represents the ASN.1 type OrigTransactionID (OCTET_STRING).
type OrigTransactionID = []byte

// PAbortCause represents the ASN.1 INTEGER type P-AbortCause with named numbers.
type PAbortCause = int64

const (
	PAbortCauseUnrecognizedMessageType          PAbortCause = 0
	PAbortCauseUnrecognizedTransactionID        PAbortCause = 1
	PAbortCauseBadlyFormattedTransactionPortion PAbortCause = 2
	PAbortCauseIncorrectTransactionPortion      PAbortCause = 3
	PAbortCauseResourceLimitation               PAbortCause = 4
)

// TCMessage choice constants.
const (
	TCMessageChoiceUnidirectional = 1
	TCMessageChoiceBegin          = 2
	TCMessageChoiceEnd            = 3
	TCMessageChoiceContinue       = 4
	TCMessageChoiceAbort          = 5
)

// TCMessage represents the ASN.1 CHOICE type TCMessage.
type TCMessage struct {
	Choice         int
	Unidirectional *Unidirectional `json:"Unidirectional,omitempty"`
	Begin          *Begin          `json:"Begin,omitempty"`
	End            *End            `json:"End,omitempty"`
	Continue       *Continue       `json:"Continue,omitempty"`
	Abort          *Abort          `json:"Abort,omitempty"`
}

// NewTCMessageUnidirectional creates a TCMessage with the unidirectional alternative.
func NewTCMessageUnidirectional(v Unidirectional) TCMessage {
	return TCMessage{
		Choice:         TCMessageChoiceUnidirectional,
		Unidirectional: &v,
	}
}

// NewTCMessageBegin creates a TCMessage with the begin alternative.
func NewTCMessageBegin(v Begin) TCMessage {
	return TCMessage{
		Choice: TCMessageChoiceBegin,
		Begin:  &v,
	}
}

// NewTCMessageEnd creates a TCMessage with the end alternative.
func NewTCMessageEnd(v End) TCMessage {
	return TCMessage{
		Choice: TCMessageChoiceEnd,
		End:    &v,
	}
}

// NewTCMessageContinue creates a TCMessage with the continue alternative.
func NewTCMessageContinue(v Continue) TCMessage {
	return TCMessage{
		Choice:   TCMessageChoiceContinue,
		Continue: &v,
	}
}

// NewTCMessageAbort creates a TCMessage with the abort alternative.
func NewTCMessageAbort(v Abort) TCMessage {
	return TCMessage{
		Choice: TCMessageChoiceAbort,
		Abort:  &v,
	}
}

// Unidirectional represents the ASN.1 type Unidirectional (SEQUENCE).
type Unidirectional struct {
	DialoguePortion  *DialoguePortion `asn1:",optional" json:"DialoguePortion,omitempty"`
	Components       ComponentPortion `asn1:""`
	ComponentsIndef_ bool             `asn1:"-" json:"-"`
}

// AbortReason choice constants.
const (
	AbortReasonChoicePAbortCause = 1
	AbortReasonChoiceUAbortCause = 2
)

// AbortReason represents the ASN.1 CHOICE type Abort-reason.
type AbortReason struct {
	Choice      int
	PAbortCause *PAbortCause     `json:"PAbortCause,omitempty"`
	UAbortCause *DialoguePortion `json:"UAbortCause,omitempty"`
}

// NewAbortReasonPAbortCause creates a Abort-reason with the p-abortCause alternative.
func NewAbortReasonPAbortCause(v PAbortCause) AbortReason {
	return AbortReason{
		Choice:      AbortReasonChoicePAbortCause,
		PAbortCause: &v,
	}
}

// NewAbortReasonUAbortCause creates a Abort-reason with the u-abortCause alternative.
func NewAbortReasonUAbortCause(v DialoguePortion) AbortReason {
	return AbortReason{
		Choice:      AbortReasonChoiceUAbortCause,
		UAbortCause: &v,
	}
}

// MarshalBER encodes Abort to BER format.
func (v *Abort) MarshalBER() ([]byte, error) {
	var children []byte
	enc_dtid := ber.EncodeOctetString([]byte(v.Dtid))
	enc_dtid = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 9, false, enc_dtid)
	children = append(children, enc_dtid...)
	if v.Reason != nil {
		enc_reason, err := v.Reason.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding reason: %w", err)
		}
		children = append(children, enc_reason...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes Abort to DER format.
func (v *Abort) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes Abort from BER/DER format.
func (v *Abort) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding Abort SEQUENCE: %w", err)
	}
	offset := 0
	// Decode dtid
	if offset >= len(content) {
		return fmt.Errorf("missing required field dtid")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 9 {
			return fmt.Errorf("expected tag [%s %d] for dtid, got %s", "APPLICATION", 9, reqTag_)
		}
	}
	_, n_dtid, rawVal_dtid, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding dtid: %w", err)
	}
	v.Dtid = DestTransactionID(rawVal_dtid)
	offset += n_dtid
	// Decode reason
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if (peekTag.Class == tag.ClassApplication && peekTag.Number == 10) || (peekTag.Class == tag.ClassApplication && peekTag.Number == 11) {
				// Decode nested CHOICE (AbortReason)
				_, n_reason, _, tlvErr_reason := ber.DecodeTLV(content[offset:])
				if tlvErr_reason != nil {
					return fmt.Errorf("decoding reason: %w", tlvErr_reason)
				}
				var dec_reason AbortReason
				if unmErr := dec_reason.UnmarshalBER(content[offset : offset+n_reason]); unmErr != nil {
					return fmt.Errorf("decoding reason: %w", unmErr)
				}
				v.Reason = &dec_reason
				offset += n_reason
			}
		}
	}
	return nil
}

// MarshalBER encodes Begin to BER format.
func (v *Begin) MarshalBER() ([]byte, error) {
	var children []byte
	enc_otid := ber.EncodeOctetString([]byte(v.Otid))
	enc_otid = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 8, false, enc_otid)
	children = append(children, enc_otid...)
	if v.DialoguePortion != nil {
		enc_dialogueportion := v.DialoguePortion.Bytes
		enc_dialogueportion = ber.EncodeExplicitTagWithClass(tag.ClassApplication, 11, enc_dialogueportion)
		children = append(children, enc_dialogueportion...)
	}
	if v.Components != nil {
		enc_components, err := marshalBERComponentPortion(v.Components)
		if err != nil {
			return nil, fmt.Errorf("encoding components: %w", err)
		}
		if v.ComponentsIndef_ {
			// Strip the outer SEQUENCE tag from marshalBER output to get raw children.
			_, _, seqContent_, tlvErr_ := ber.DecodeTLV(enc_components)
			if tlvErr_ != nil {
				return nil, tlvErr_
			}
			enc_components = ber.EncodeConstructedIndefinite(tag.Tag{Class: tag.ClassApplication, Number: 12}, seqContent_)
		} else {
			enc_components = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 12, true, enc_components)
		}
		children = append(children, enc_components...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes Begin to DER format.
func (v *Begin) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes Begin from BER/DER format.
func (v *Begin) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding Begin SEQUENCE: %w", err)
	}
	offset := 0
	// Decode otid
	if offset >= len(content) {
		return fmt.Errorf("missing required field otid")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 8 {
			return fmt.Errorf("expected tag [%s %d] for otid, got %s", "APPLICATION", 8, reqTag_)
		}
	}
	_, n_otid, rawVal_otid, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding otid: %w", err)
	}
	v.Otid = OrigTransactionID(rawVal_otid)
	offset += n_otid
	// Decode dialoguePortion
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 11 {
				_, n_dialogueportion, innerData_dialogueportion, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding dialoguePortion: %w", err)
				}
				// Decode inner value from explicit tag wrapper
				tmp_dialogueportion := runtime.RawValue{Bytes: innerData_dialogueportion}
				v.DialoguePortion = &tmp_dialogueportion
				offset += n_dialogueportion
			}
		}
	}
	// Decode components
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 12 {
				_, n_components, rawVal_components, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding components: %w", err)
				}
				reconstructed_components := ber.EncodeSequence(rawVal_components)
				dec_components, unmErr := unmarshalBERComponentPortion(reconstructed_components)
				if unmErr != nil {
					return fmt.Errorf("decoding components: %w", unmErr)
				}
				v.Components = dec_components
				{
					_, tagSz_, _ := ber.DecodeTag(content[offset:])
					if offset+tagSz_ < len(content) && content[offset+tagSz_] == 0x80 {
						v.ComponentsIndef_ = true
					}
				}
				offset += n_components
			}
		}
	}
	return nil
}

// MarshalBER encodes Component to BER format.
func (v *Component) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case ComponentChoiceBasicROS:
		if v.BasicROS == nil {
			return nil, fmt.Errorf("choice Component: basicROS is nil")
		}
		enc_0, err := v.BasicROS.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding basicROS: %w", err)
		}
		return enc_0, nil
	case ComponentChoiceReturnResultNotLast:
		if v.ReturnResultNotLast == nil {
			return nil, fmt.Errorf("choice Component: returnResultNotLast is nil")
		}
		enc_1, err := v.ReturnResultNotLast.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding returnResultNotLast: %w", err)
		}
		enc_1 = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 7, true, enc_1)
		return enc_1, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for Component", v.Choice)
	}
}

// MarshalDER encodes Component to DER format.
func (v *Component) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes Component from BER/DER format.
func (v *Component) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for Component CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for Component: %w", peekErr)
	}

	if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 7 {
		v.Choice = ComponentChoiceReturnResultNotLast
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding returnResultNotLast: %w", tlvErr)
		}
		reconstructed := rawVal
		var dec ROS
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding returnResultNotLast: %w", unmErr)
		}
		v.ReturnResultNotLast = &dec
	} else {
		v.Choice = ComponentChoiceBasicROS
		var dec ROS
		if unmErr := dec.UnmarshalBER(data); unmErr != nil {
			return fmt.Errorf("decoding basicROS: %w", unmErr)
		}
		v.BasicROS = &dec
	}
	return nil
}

// marshalBERComponentPortion encodes a ComponentPortion list to BER.
func marshalBERComponentPortion(list ComponentPortion) ([]byte, error) {
	var children []byte
	for _, elem := range list {
		enc, err := elem.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding element: %w", err)
		}
		children = append(children, enc...)
	}
	return ber.EncodeSequence(children), nil
}

// unmarshalBERComponentPortion decodes a ComponentPortion list from BER.
func unmarshalBERComponentPortion(data []byte) (ComponentPortion, error) {
	_, content, _, err := ber.DecodeConstructedContent(data)
	if err != nil {
		return nil, fmt.Errorf("decoding ComponentPortion: %w", err)
	}
	var result ComponentPortion
	offset := 0
	for offset < len(content) {
		var elem Component
		_, n, _, tlvErr := ber.DecodeTLV(content[offset:])
		if tlvErr != nil {
			return nil, fmt.Errorf("decoding element TLV: %w", tlvErr)
		}
		if unmErr := elem.UnmarshalBER(content[offset : offset+n]); unmErr != nil {
			return nil, fmt.Errorf("decoding element: %w", unmErr)
		}
		result = append(result, elem)
		offset += n
	}
	return result, nil
}

// MarshalBER encodes Continue to BER format.
func (v *Continue) MarshalBER() ([]byte, error) {
	var children []byte
	enc_otid := ber.EncodeOctetString([]byte(v.Otid))
	enc_otid = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 8, false, enc_otid)
	children = append(children, enc_otid...)
	enc_dtid := ber.EncodeOctetString([]byte(v.Dtid))
	enc_dtid = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 9, false, enc_dtid)
	children = append(children, enc_dtid...)
	if v.DialoguePortion != nil {
		enc_dialogueportion := v.DialoguePortion.Bytes
		enc_dialogueportion = ber.EncodeExplicitTagWithClass(tag.ClassApplication, 11, enc_dialogueportion)
		children = append(children, enc_dialogueportion...)
	}
	if v.Components != nil {
		enc_components, err := marshalBERComponentPortion(v.Components)
		if err != nil {
			return nil, fmt.Errorf("encoding components: %w", err)
		}
		if v.ComponentsIndef_ {
			// Strip the outer SEQUENCE tag from marshalBER output to get raw children.
			_, _, seqContent_, tlvErr_ := ber.DecodeTLV(enc_components)
			if tlvErr_ != nil {
				return nil, tlvErr_
			}
			enc_components = ber.EncodeConstructedIndefinite(tag.Tag{Class: tag.ClassApplication, Number: 12}, seqContent_)
		} else {
			enc_components = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 12, true, enc_components)
		}
		children = append(children, enc_components...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes Continue to DER format.
func (v *Continue) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes Continue from BER/DER format.
func (v *Continue) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding Continue SEQUENCE: %w", err)
	}
	offset := 0
	// Decode otid
	if offset >= len(content) {
		return fmt.Errorf("missing required field otid")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 8 {
			return fmt.Errorf("expected tag [%s %d] for otid, got %s", "APPLICATION", 8, reqTag_)
		}
	}
	_, n_otid, rawVal_otid, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding otid: %w", err)
	}
	v.Otid = OrigTransactionID(rawVal_otid)
	offset += n_otid
	// Decode dtid
	if offset >= len(content) {
		return fmt.Errorf("missing required field dtid")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 9 {
			return fmt.Errorf("expected tag [%s %d] for dtid, got %s", "APPLICATION", 9, reqTag_)
		}
	}
	_, n_dtid, rawVal_dtid, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding dtid: %w", err)
	}
	v.Dtid = DestTransactionID(rawVal_dtid)
	offset += n_dtid
	// Decode dialoguePortion
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 11 {
				_, n_dialogueportion, innerData_dialogueportion, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding dialoguePortion: %w", err)
				}
				// Decode inner value from explicit tag wrapper
				tmp_dialogueportion := runtime.RawValue{Bytes: innerData_dialogueportion}
				v.DialoguePortion = &tmp_dialogueportion
				offset += n_dialogueportion
			}
		}
	}
	// Decode components
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 12 {
				_, n_components, rawVal_components, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding components: %w", err)
				}
				reconstructed_components := ber.EncodeSequence(rawVal_components)
				dec_components, unmErr := unmarshalBERComponentPortion(reconstructed_components)
				if unmErr != nil {
					return fmt.Errorf("decoding components: %w", unmErr)
				}
				v.Components = dec_components
				{
					_, tagSz_, _ := ber.DecodeTag(content[offset:])
					if offset+tagSz_ < len(content) && content[offset+tagSz_] == 0x80 {
						v.ComponentsIndef_ = true
					}
				}
				offset += n_components
			}
		}
	}
	return nil
}

// MarshalBER encodes End to BER format.
func (v *End) MarshalBER() ([]byte, error) {
	var children []byte
	enc_dtid := ber.EncodeOctetString([]byte(v.Dtid))
	enc_dtid = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 9, false, enc_dtid)
	children = append(children, enc_dtid...)
	if v.DialoguePortion != nil {
		enc_dialogueportion := v.DialoguePortion.Bytes
		enc_dialogueportion = ber.EncodeExplicitTagWithClass(tag.ClassApplication, 11, enc_dialogueportion)
		children = append(children, enc_dialogueportion...)
	}
	if v.Components != nil {
		enc_components, err := marshalBERComponentPortion(v.Components)
		if err != nil {
			return nil, fmt.Errorf("encoding components: %w", err)
		}
		if v.ComponentsIndef_ {
			// Strip the outer SEQUENCE tag from marshalBER output to get raw children.
			_, _, seqContent_, tlvErr_ := ber.DecodeTLV(enc_components)
			if tlvErr_ != nil {
				return nil, tlvErr_
			}
			enc_components = ber.EncodeConstructedIndefinite(tag.Tag{Class: tag.ClassApplication, Number: 12}, seqContent_)
		} else {
			enc_components = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 12, true, enc_components)
		}
		children = append(children, enc_components...)
	}
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes End to DER format.
func (v *End) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes End from BER/DER format.
func (v *End) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding End SEQUENCE: %w", err)
	}
	offset := 0
	// Decode dtid
	if offset >= len(content) {
		return fmt.Errorf("missing required field dtid")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 9 {
			return fmt.Errorf("expected tag [%s %d] for dtid, got %s", "APPLICATION", 9, reqTag_)
		}
	}
	_, n_dtid, rawVal_dtid, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding dtid: %w", err)
	}
	v.Dtid = DestTransactionID(rawVal_dtid)
	offset += n_dtid
	// Decode dialoguePortion
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 11 {
				_, n_dialogueportion, innerData_dialogueportion, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding dialoguePortion: %w", err)
				}
				// Decode inner value from explicit tag wrapper
				tmp_dialogueportion := runtime.RawValue{Bytes: innerData_dialogueportion}
				v.DialoguePortion = &tmp_dialogueportion
				offset += n_dialogueportion
			}
		}
	}
	// Decode components
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 12 {
				_, n_components, rawVal_components, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding components: %w", err)
				}
				reconstructed_components := ber.EncodeSequence(rawVal_components)
				dec_components, unmErr := unmarshalBERComponentPortion(reconstructed_components)
				if unmErr != nil {
					return fmt.Errorf("decoding components: %w", unmErr)
				}
				v.Components = dec_components
				{
					_, tagSz_, _ := ber.DecodeTag(content[offset:])
					if offset+tagSz_ < len(content) && content[offset+tagSz_] == 0x80 {
						v.ComponentsIndef_ = true
					}
				}
				offset += n_components
			}
		}
	}
	return nil
}

// MarshalBER encodes TCMessage to BER format.
func (v *TCMessage) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case TCMessageChoiceUnidirectional:
		if v.Unidirectional == nil {
			return nil, fmt.Errorf("choice TCMessage: unidirectional is nil")
		}
		enc_0, err := v.Unidirectional.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding unidirectional: %w", err)
		}
		enc_0 = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 1, true, enc_0)
		return enc_0, nil
	case TCMessageChoiceBegin:
		if v.Begin == nil {
			return nil, fmt.Errorf("choice TCMessage: begin is nil")
		}
		enc_1, err := v.Begin.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding begin: %w", err)
		}
		enc_1 = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 2, true, enc_1)
		return enc_1, nil
	case TCMessageChoiceEnd:
		if v.End == nil {
			return nil, fmt.Errorf("choice TCMessage: end is nil")
		}
		enc_2, err := v.End.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding end: %w", err)
		}
		enc_2 = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 4, true, enc_2)
		return enc_2, nil
	case TCMessageChoiceContinue:
		if v.Continue == nil {
			return nil, fmt.Errorf("choice TCMessage: continue is nil")
		}
		enc_3, err := v.Continue.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding continue: %w", err)
		}
		enc_3 = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 5, true, enc_3)
		return enc_3, nil
	case TCMessageChoiceAbort:
		if v.Abort == nil {
			return nil, fmt.Errorf("choice TCMessage: abort is nil")
		}
		enc_4, err := v.Abort.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding abort: %w", err)
		}
		enc_4 = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 7, true, enc_4)
		return enc_4, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for TCMessage", v.Choice)
	}
}

// MarshalDER encodes TCMessage to DER format.
func (v *TCMessage) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes TCMessage from BER/DER format.
func (v *TCMessage) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for TCMessage CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for TCMessage: %w", peekErr)
	}

	if peekTag.Class == tag.ClassApplication && peekTag.Number == 1 {
		v.Choice = TCMessageChoiceUnidirectional
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding unidirectional: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec Unidirectional
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding unidirectional: %w", unmErr)
		}
		v.Unidirectional = &dec
	} else if peekTag.Class == tag.ClassApplication && peekTag.Number == 2 {
		v.Choice = TCMessageChoiceBegin
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding begin: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec Begin
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding begin: %w", unmErr)
		}
		v.Begin = &dec
	} else if peekTag.Class == tag.ClassApplication && peekTag.Number == 4 {
		v.Choice = TCMessageChoiceEnd
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding end: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec End
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding end: %w", unmErr)
		}
		v.End = &dec
	} else if peekTag.Class == tag.ClassApplication && peekTag.Number == 5 {
		v.Choice = TCMessageChoiceContinue
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding continue: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec Continue
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding continue: %w", unmErr)
		}
		v.Continue = &dec
	} else if peekTag.Class == tag.ClassApplication && peekTag.Number == 7 {
		v.Choice = TCMessageChoiceAbort
		_, _, rawVal, tlvErr := ber.DecodeTLV(data)
		if tlvErr != nil {
			return fmt.Errorf("decoding abort: %w", tlvErr)
		}
		reconstructed := ber.EncodeSequence(rawVal)
		var dec Abort
		if unmErr := dec.UnmarshalBER(reconstructed); unmErr != nil {
			return fmt.Errorf("decoding abort: %w", unmErr)
		}
		v.Abort = &dec
	} else {
		return fmt.Errorf("unknown tag %s for TCMessage CHOICE", peekTag)
	}
	return nil
}

// MarshalBER encodes Unidirectional to BER format.
func (v *Unidirectional) MarshalBER() ([]byte, error) {
	var children []byte
	if v.DialoguePortion != nil {
		enc_dialogueportion := v.DialoguePortion.Bytes
		enc_dialogueportion = ber.EncodeExplicitTagWithClass(tag.ClassApplication, 11, enc_dialogueportion)
		children = append(children, enc_dialogueportion...)
	}
	enc_components, err := marshalBERComponentPortion(v.Components)
	if err != nil {
		return nil, fmt.Errorf("encoding components: %w", err)
	}
	if v.ComponentsIndef_ {
		// Strip the outer SEQUENCE tag from marshalBER output to get raw children.
		_, _, seqContent_, tlvErr_ := ber.DecodeTLV(enc_components)
		if tlvErr_ != nil {
			return nil, tlvErr_
		}
		enc_components = ber.EncodeConstructedIndefinite(tag.Tag{Class: tag.ClassApplication, Number: 12}, seqContent_)
	} else {
		enc_components = ber.EncodeImplicitTagWithClass(tag.ClassApplication, 12, true, enc_components)
	}
	children = append(children, enc_components...)
	return ber.EncodeSequence(children), nil
}

// MarshalDER encodes Unidirectional to DER format.
func (v *Unidirectional) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes Unidirectional from BER/DER format.
func (v *Unidirectional) UnmarshalBER(data []byte) error {
	content, _, err := ber.DecodeSequenceContent(data)
	if err != nil {
		return fmt.Errorf("decoding Unidirectional SEQUENCE: %w", err)
	}
	offset := 0
	// Decode dialoguePortion
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassApplication && peekTag.Number == 11 {
				_, n_dialogueportion, innerData_dialogueportion, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding dialoguePortion: %w", err)
				}
				// Decode inner value from explicit tag wrapper
				tmp_dialogueportion := runtime.RawValue{Bytes: innerData_dialogueportion}
				v.DialoguePortion = &tmp_dialogueportion
				offset += n_dialogueportion
			}
		}
	}
	// Decode components
	if offset >= len(content) {
		return fmt.Errorf("missing required field components")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassApplication || reqTag_.Number != 12 {
			return fmt.Errorf("expected tag [%s %d] for components, got %s", "APPLICATION", 12, reqTag_)
		}
	}
	_, n_components, rawVal_components, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding components: %w", err)
	}
	reconstructed_components := ber.EncodeSequence(rawVal_components)
	dec_components, unmErr := unmarshalBERComponentPortion(reconstructed_components)
	if unmErr != nil {
		return fmt.Errorf("decoding components: %w", unmErr)
	}
	v.Components = dec_components
	{
		_, tagSz_, _ := ber.DecodeTag(content[offset:])
		if offset+tagSz_ < len(content) && content[offset+tagSz_] == 0x80 {
			v.ComponentsIndef_ = true
		}
	}
	offset += n_components
	return nil
}

// MarshalBER encodes AbortReason to BER format.
func (v *AbortReason) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case AbortReasonChoicePAbortCause:
		if v.PAbortCause == nil {
			return nil, fmt.Errorf("choice AbortReason: p-abortCause is nil")
		}
		enc_0 := ber.EncodeInteger(int64(*v.PAbortCause))
		return enc_0, nil
	case AbortReasonChoiceUAbortCause:
		enc_1 := v.UAbortCause.Bytes
		return enc_1, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for AbortReason", v.Choice)
	}
}

// MarshalDER encodes AbortReason to DER format.
func (v *AbortReason) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes AbortReason from BER/DER format.
func (v *AbortReason) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for AbortReason CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for AbortReason: %w", peekErr)
	}

	if peekTag.Class == tag.ClassApplication && peekTag.Number == 10 {
		v.Choice = AbortReasonChoicePAbortCause
		decVal, _, intErr := ber.DecodeInteger(data)
		if intErr != nil {
			return fmt.Errorf("decoding p-abortCause: %w", intErr)
		}
		v.PAbortCause = &decVal
	} else if peekTag.Class == tag.ClassApplication && peekTag.Number == 11 {
		v.Choice = AbortReasonChoiceUAbortCause
		tmpRaw := runtime.RawValue{Bytes: data}
		v.UAbortCause = &tmpRaw
	} else {
		return fmt.Errorf("unknown tag %s for AbortReason CHOICE", peekTag)
	}
	return nil
}
