// Code generated by asn1c-go from ASN.1 module "UnidialoguePDUs". DO NOT EDIT.

package tcap

import (
	"fmt"

	"github.com/gomaja/go-asn1/runtime"
	"github.com/gomaja/go-asn1/runtime/ber"
	"github.com/gomaja/go-asn1/runtime/tag"
)

// Ensure imports are used.
var (
	_ runtime.BitString
	_ = ber.EncodeTLV
	_ = tag.ClassUniversal
)

// UniDialogueAsId is the OID value for uniDialogue-as-id.
var UniDialogueAsId = []uint64{0, 0, 17, 773, 1, 2, 1}

// AUDTApdu represents the ASN.1 type AUDT-apdu (SEQUENCE).
type AUDTApdu struct {
	ProtocolVersion        *runtime.BitString       `asn1:"tag:0,context,implicit,optional" json:"ProtocolVersion,omitempty"`
	ApplicationContextName runtime.ObjectIdentifier `asn1:"tag:1,context,explicit"`
	UserInformation        AUDTApduUserInformation  `asn1:"tag:30,context,implicit,optional" json:"UserInformation,omitempty"`
	UserInformationIndef_  bool                     `asn1:"-" json:"-"`
}

// UniDialoguePDU choice constants.
const (
	UniDialoguePDUChoiceUnidialoguePDU = 1
)

// UniDialoguePDU represents the ASN.1 CHOICE type UniDialoguePDU.
type UniDialoguePDU struct {
	Choice         int
	UnidialoguePDU *AUDTApdu `json:"UnidialoguePDU,omitempty"`
}

// NewUniDialoguePDUUnidialoguePDU creates a UniDialoguePDU with the unidialoguePDU alternative.
func NewUniDialoguePDUUnidialoguePDU(v AUDTApdu) UniDialoguePDU {
	return UniDialoguePDU{
		Choice:         UniDialoguePDUChoiceUnidialoguePDU,
		UnidialoguePDU: &v,
	}
}

// AUDTApduUserInformation represents the ASN.1 type AUDT-apdu-user-information (SEQUENCE_OF).
type AUDTApduUserInformation = []runtime.RawValue

// MarshalBER encodes AUDTApdu to BER format.
func (v *AUDTApdu) MarshalBER() ([]byte, error) {
	var children []byte
	if v.ProtocolVersion != nil {
		enc_protocolversion := ber.EncodeBitString(v.ProtocolVersion.Bytes, (8-(v.ProtocolVersion.BitLength%8))%8)
		enc_protocolversion = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 0, false, enc_protocolversion)
		children = append(children, enc_protocolversion...)
	}
	enc_applicationcontextname := ber.EncodeObjectIdentifier([]uint64(v.ApplicationContextName))
	enc_applicationcontextname = ber.EncodeExplicitTagWithClass(tag.ClassContextSpecific, 1, enc_applicationcontextname)
	children = append(children, enc_applicationcontextname...)
	if v.UserInformation != nil {
		enc_userinformation, err := marshalBERAUDTApduUserInformation(v.UserInformation)
		if err != nil {
			return nil, fmt.Errorf("encoding user-information: %w", err)
		}
		if v.UserInformationIndef_ {
			// Strip the outer SEQUENCE tag from marshalBER output to get raw children.
			_, _, seqContent_, tlvErr_ := ber.DecodeTLV(enc_userinformation)
			if tlvErr_ != nil {
				return nil, tlvErr_
			}
			enc_userinformation = ber.EncodeConstructedIndefinite(tag.Tag{Class: tag.ClassContextSpecific, Number: 30}, seqContent_)
		} else {
			enc_userinformation = ber.EncodeImplicitTagWithClass(tag.ClassContextSpecific, 30, true, enc_userinformation)
		}
		children = append(children, enc_userinformation...)
	}
	return ber.EncodeConstructed(tag.Tag{Class: tag.ClassApplication, Number: 0, Constructed: true}, children), nil
}

// MarshalDER encodes AUDTApdu to DER format.
func (v *AUDTApdu) MarshalDER() ([]byte, error) {
	// DER is a subset of BER; our BER encoder already uses DER-compatible encoding.
	return v.MarshalBER()
}

// UnmarshalBER decodes AUDTApdu from BER/DER format.
func (v *AUDTApdu) UnmarshalBER(data []byte) error {
	_, content, _, err := ber.DecodeConstructedContent(data)
	if err != nil {
		return fmt.Errorf("decoding AUDTApdu: %w", err)
	}
	offset := 0
	// Decode protocol-version
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 0 {
				_, n_protocolversion, rawVal_protocolversion, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding protocol-version: %w", err)
				}
				bsBytes_protocolversion, bsUnused_protocolversion, bsErr := ber.DecodeBitStringValue(rawVal_protocolversion)
				if bsErr != nil {
					return fmt.Errorf("decoding protocol-version: %w", bsErr)
				}
				tmp_protocolversion := runtime.BitString{Bytes: bsBytes_protocolversion, BitLength: len(bsBytes_protocolversion)*8 - bsUnused_protocolversion}
				v.ProtocolVersion = &tmp_protocolversion
				offset += n_protocolversion
			}
		}
	}
	// Decode application-context-name
	if offset >= len(content) {
		return fmt.Errorf("missing required field application-context-name")
	}
	if reqTag_, reqErr_ := ber.PeekTag(content[offset:]); reqErr_ == nil {
		if reqTag_.Class != tag.ClassContextSpecific || reqTag_.Number != 1 {
			return fmt.Errorf("expected tag [%s %d] for application-context-name, got %s", "CONTEXT", 1, reqTag_)
		}
	}
	_, n_applicationcontextname, innerData_applicationcontextname, err := ber.DecodeTLV(content[offset:])
	if err != nil {
		return fmt.Errorf("decoding application-context-name: %w", err)
	}
	// Decode inner value from explicit tag wrapper
	val_applicationcontextname, _, oidErr := ber.DecodeObjectIdentifier(innerData_applicationcontextname)
	if oidErr != nil {
		return fmt.Errorf("decoding application-context-name: %w", oidErr)
	}
	v.ApplicationContextName = runtime.ObjectIdentifier(val_applicationcontextname)
	offset += n_applicationcontextname
	// Decode user-information
	if offset < len(content) {
		peekTag, peekErr := ber.PeekTag(content[offset:])
		if peekErr == nil {
			if peekTag.Class == tag.ClassContextSpecific && peekTag.Number == 30 {
				_, n_userinformation, rawVal_userinformation, err := ber.DecodeTLV(content[offset:])
				if err != nil {
					return fmt.Errorf("decoding user-information: %w", err)
				}
				reconstructed_userinformation := ber.EncodeSequence(rawVal_userinformation)
				dec_userinformation, unmErr := unmarshalBERAUDTApduUserInformation(reconstructed_userinformation)
				if unmErr != nil {
					return fmt.Errorf("decoding user-information: %w", unmErr)
				}
				v.UserInformation = dec_userinformation
				{
					_, tagSz_, _ := ber.DecodeTag(content[offset:])
					if offset+tagSz_ < len(content) && content[offset+tagSz_] == 0x80 {
						v.UserInformationIndef_ = true
					}
				}
				offset += n_userinformation
			}
		}
	}
	return nil
}

// MarshalBER encodes UniDialoguePDU to BER format.
func (v *UniDialoguePDU) MarshalBER() ([]byte, error) {
	switch v.Choice {
	case UniDialoguePDUChoiceUnidialoguePDU:
		if v.UnidialoguePDU == nil {
			return nil, fmt.Errorf("choice UniDialoguePDU: unidialoguePDU is nil")
		}
		enc_0, err := v.UnidialoguePDU.MarshalBER()
		if err != nil {
			return nil, fmt.Errorf("encoding unidialoguePDU: %w", err)
		}
		return enc_0, nil
	default:
		return nil, fmt.Errorf("unknown choice %d for UniDialoguePDU", v.Choice)
	}
}

// MarshalDER encodes UniDialoguePDU to DER format.
func (v *UniDialoguePDU) MarshalDER() ([]byte, error) {
	return v.MarshalBER()
}

// UnmarshalBER decodes UniDialoguePDU from BER/DER format.
func (v *UniDialoguePDU) UnmarshalBER(data []byte) error {
	if len(data) == 0 {
		return fmt.Errorf("empty data for UniDialoguePDU CHOICE")
	}
	peekTag, peekErr := ber.PeekTag(data)
	if peekErr != nil {
		return fmt.Errorf("peeking tag for UniDialoguePDU: %w", peekErr)
	}

	if peekTag.Class == tag.ClassApplication && peekTag.Number == 0 {
		v.Choice = UniDialoguePDUChoiceUnidialoguePDU
		var dec AUDTApdu
		if unmErr := dec.UnmarshalBER(data); unmErr != nil {
			return fmt.Errorf("decoding unidialoguePDU: %w", unmErr)
		}
		v.UnidialoguePDU = &dec
	} else {
		return fmt.Errorf("unknown tag %s for UniDialoguePDU CHOICE", peekTag)
	}
	return nil
}

// marshalBERAUDTApduUserInformation encodes a AUDTApduUserInformation list to BER.
func marshalBERAUDTApduUserInformation(list AUDTApduUserInformation) ([]byte, error) {
	var children []byte
	for _, elem := range list {
		children = append(children, elem.Bytes...)
	}
	return ber.EncodeSequence(children), nil
}

// unmarshalBERAUDTApduUserInformation decodes a AUDTApduUserInformation list from BER.
func unmarshalBERAUDTApduUserInformation(data []byte) (AUDTApduUserInformation, error) {
	_, content, _, err := ber.DecodeConstructedContent(data)
	if err != nil {
		return nil, fmt.Errorf("decoding AUDTApduUserInformation: %w", err)
	}
	var result AUDTApduUserInformation
	offset := 0
	for offset < len(content) {
		_, n, _, tlvErr := ber.DecodeTLV(content[offset:])
		if tlvErr != nil {
			return nil, fmt.Errorf("decoding element: %w", tlvErr)
		}
		result = append(result, runtime.RawValue{Bytes: content[offset : offset+n]})
		offset += n
	}
	return result, nil
}
